// WARNING in sk_stream_kill_queues (3)
// https://syzkaller.appspot.com/bug?id=1557fb40b5ed0a1ed2ba18268e04da194674d770
// status:open
// autogenerated by syzkaller (http://github.com/google/syzkaller)

#define _GNU_SOURCE
#include <arpa/inet.h>
#include <endian.h>
#include <errno.h>
#include <errno.h>
#include <errno.h>
#include <fcntl.h>
#include <linux/futex.h>
#include <linux/if.h>
#include <linux/if_ether.h>
#include <linux/if_tun.h>
#include <linux/ip.h>
#include <linux/tcp.h>
#include <net/if_arp.h>
#include <pthread.h>
#include <sched.h>
#include <signal.h>
#include <signal.h>
#include <stdarg.h>
#include <stdarg.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdio.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdlib.h>
#include <sys/ioctl.h>
#include <sys/prctl.h>
#include <sys/prctl.h>
#include <sys/resource.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/time.h>
#include <sys/time.h>
#include <sys/uio.h>
#include <sys/wait.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

__attribute__((noreturn)) static void doexit(int status)
{
  volatile unsigned i;
  syscall(__NR_exit_group, status);
  for (i = 0;; i++) {
  }
}
#include <errno.h>
#include <setjmp.h>
#include <signal.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <string.h>

const int kFailStatus = 67;
const int kRetryStatus = 69;

static void fail(const char* msg, ...)
{
  int e = errno;
  va_list args;
  va_start(args, msg);
  vfprintf(stderr, msg, args);
  va_end(args);
  fprintf(stderr, " (errno %d)\n", e);
  doexit((e == ENOMEM || e == EAGAIN) ? kRetryStatus : kFailStatus);
}

static __thread int skip_segv;
static __thread jmp_buf segv_env;

static void segv_handler(int sig, siginfo_t* info, void* uctx)
{
  uintptr_t addr = (uintptr_t)info->si_addr;
  const uintptr_t prog_start = 1 << 20;
  const uintptr_t prog_end = 100 << 20;
  if (__atomic_load_n(&skip_segv, __ATOMIC_RELAXED) &&
      (addr < prog_start || addr > prog_end)) {
    _longjmp(segv_env, 1);
  }
  doexit(sig);
}

static void install_segv_handler()
{
  struct sigaction sa;

  memset(&sa, 0, sizeof(sa));
  sa.sa_handler = SIG_IGN;
  syscall(SYS_rt_sigaction, 0x20, &sa, NULL, 8);
  syscall(SYS_rt_sigaction, 0x21, &sa, NULL, 8);

  memset(&sa, 0, sizeof(sa));
  sa.sa_sigaction = segv_handler;
  sa.sa_flags = SA_NODEFER | SA_SIGINFO;
  sigaction(SIGSEGV, &sa, NULL);
  sigaction(SIGBUS, &sa, NULL);
}

#define NONFAILING(...)                                                        \
  {                                                                            \
    __atomic_fetch_add(&skip_segv, 1, __ATOMIC_SEQ_CST);                       \
    if (_setjmp(segv_env) == 0) {                                              \
      __VA_ARGS__;                                                             \
    }                                                                          \
    __atomic_fetch_sub(&skip_segv, 1, __ATOMIC_SEQ_CST);                       \
  }

static uint64_t current_time_ms()
{
  struct timespec ts;

  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    fail("clock_gettime failed");
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

static void vsnprintf_check(char* str, size_t size, const char* format,
                            va_list args)
{
  int rv;

  rv = vsnprintf(str, size, format, args);
  if (rv < 0)
    fail("tun: snprintf failed");
  if ((size_t)rv >= size)
    fail("tun: string '%s...' doesn't fit into buffer", str);
}

#define COMMAND_MAX_LEN 128
#define PATH_PREFIX                                                            \
  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin "
#define PATH_PREFIX_LEN (sizeof(PATH_PREFIX) - 1)

static void execute_command(bool panic, const char* format, ...)
{
  va_list args;
  char command[PATH_PREFIX_LEN + COMMAND_MAX_LEN];
  int rv;

  va_start(args, format);
  memcpy(command, PATH_PREFIX, PATH_PREFIX_LEN);
  vsnprintf_check(command + PATH_PREFIX_LEN, COMMAND_MAX_LEN, format, args);
  va_end(args);
  rv = system(command);
  if (rv) {
    if (panic)
      fail("command '%s' failed: %d", &command[0], rv);
  }
}

#define DEV_IPV4 "172.20.20.%d"
#define DEV_IPV6 "fe80::%02hx"
#define DEV_MAC "aa:aa:aa:aa:aa:%02hx"

static void snprintf_check(char* str, size_t size, const char* format, ...)
{
  va_list args;

  va_start(args, format);
  vsnprintf_check(str, size, format, args);
  va_end(args);
}

static void initialize_netdevices(void)
{
  unsigned i;
  const char* devtypes[] = {"ip6gretap", "bridge", "vcan", "bond", "team"};
  const char* devnames[] = {"lo",
                            "sit0",
                            "bridge0",
                            "vcan0",
                            "tunl0",
                            "gre0",
                            "gretap0",
                            "ip_vti0",
                            "ip6_vti0",
                            "ip6tnl0",
                            "ip6gre0",
                            "ip6gretap0",
                            "erspan0",
                            "bond0",
                            "veth0",
                            "veth1",
                            "team0",
                            "veth0_to_bridge",
                            "veth1_to_bridge",
                            "veth0_to_bond",
                            "veth1_to_bond",
                            "veth0_to_team",
                            "veth1_to_team"};
  const char* devmasters[] = {"bridge", "bond", "team"};

  for (i = 0; i < sizeof(devtypes) / (sizeof(devtypes[0])); i++)
    execute_command(0, "ip link add dev %s0 type %s", devtypes[i], devtypes[i]);
  execute_command(0, "ip link add type veth");

  for (i = 0; i < sizeof(devmasters) / (sizeof(devmasters[0])); i++) {
    execute_command(
        0, "ip link add name %s_slave_0 type veth peer name veth0_to_%s",
        devmasters[i], devmasters[i]);
    execute_command(
        0, "ip link add name %s_slave_1 type veth peer name veth1_to_%s",
        devmasters[i], devmasters[i]);
    execute_command(0, "ip link set %s_slave_0 master %s0", devmasters[i],
                    devmasters[i]);
    execute_command(0, "ip link set %s_slave_1 master %s0", devmasters[i],
                    devmasters[i]);
    execute_command(0, "ip link set veth0_to_%s up", devmasters[i]);
    execute_command(0, "ip link set veth1_to_%s up", devmasters[i]);
  }
  execute_command(0, "ip link set bridge_slave_0 up");
  execute_command(0, "ip link set bridge_slave_1 up");

  for (i = 0; i < sizeof(devnames) / (sizeof(devnames[0])); i++) {
    char addr[32];
    snprintf_check(addr, sizeof(addr), DEV_IPV4, i + 10);
    execute_command(0, "ip -4 addr add %s/24 dev %s", addr, devnames[i]);
    snprintf_check(addr, sizeof(addr), DEV_IPV6, i + 10);
    execute_command(0, "ip -6 addr add %s/120 dev %s", addr, devnames[i]);
    snprintf_check(addr, sizeof(addr), DEV_MAC, i + 10);
    execute_command(0, "ip link set dev %s address %s", devnames[i], addr);
    execute_command(0, "ip link set dev %s up", devnames[i]);
  }
}

static void loop();

static void sandbox_common()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  setsid();

  struct rlimit rlim;
  rlim.rlim_cur = rlim.rlim_max = 160 << 20;
  setrlimit(RLIMIT_AS, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 8 << 20;
  setrlimit(RLIMIT_MEMLOCK, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 136 << 20;
  setrlimit(RLIMIT_FSIZE, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 1 << 20;
  setrlimit(RLIMIT_STACK, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 0;
  setrlimit(RLIMIT_CORE, &rlim);

  if (unshare(CLONE_NEWNS)) {
  }
  if (unshare(CLONE_NEWIPC)) {
  }
  if (unshare(0x02000000)) {
  }
  if (unshare(CLONE_NEWUTS)) {
  }
  if (unshare(CLONE_SYSVSEM)) {
  }
}

static int do_sandbox_none(void)
{
  if (unshare(CLONE_NEWPID)) {
  }
  int pid = fork();
  if (pid < 0)
    fail("sandbox fork failed");
  if (pid)
    return pid;

  sandbox_common();
  if (unshare(CLONE_NEWNET)) {
  }
  initialize_netdevices();
  loop();
  doexit(1);
}

static void execute_one();
extern unsigned long long procid;

static void loop()
{
  int iter;
  for (iter = 0;; iter++) {
    int pid = fork();
    if (pid < 0)
      fail("clone failed");
    if (pid == 0) {
      prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
      setpgrp();
      execute_one();
      doexit(0);
    }

    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      int res = waitpid(-1, &status, __WALL | WNOHANG);
      if (res == pid) {
        break;
      }
      usleep(1000);
      if (current_time_ms() - start < 3 * 1000)
        continue;
      kill(-pid, SIGKILL);
      kill(pid, SIGKILL);
      while (waitpid(-1, &status, __WALL) != pid) {
      }
      break;
    }
  }
}

struct thread_t {
  int created, running, call;
  pthread_t th;
};

static struct thread_t threads[16];
static void execute_call(int call);
static int running;
static int collide;

static void* thr(void* arg)
{
  struct thread_t* th = (struct thread_t*)arg;
  for (;;) {
    while (!__atomic_load_n(&th->running, __ATOMIC_ACQUIRE))
      syscall(SYS_futex, &th->running, FUTEX_WAIT, 0, 0);
    execute_call(th->call);
    __atomic_fetch_sub(&running, 1, __ATOMIC_RELAXED);
    __atomic_store_n(&th->running, 0, __ATOMIC_RELEASE);
    syscall(SYS_futex, &th->running, FUTEX_WAKE);
  }
  return 0;
}

static void execute(int num_calls)
{
  int call, thread;
  running = 0;
  for (call = 0; call < num_calls; call++) {
    for (thread = 0; thread < sizeof(threads) / sizeof(threads[0]); thread++) {
      struct thread_t* th = &threads[thread];
      if (!th->created) {
        th->created = 1;
        pthread_attr_t attr;
        pthread_attr_init(&attr);
        pthread_attr_setstacksize(&attr, 128 << 10);
        pthread_create(&th->th, &attr, thr, th);
      }
      if (!__atomic_load_n(&th->running, __ATOMIC_ACQUIRE)) {
        th->call = call;
        __atomic_fetch_add(&running, 1, __ATOMIC_RELAXED);
        __atomic_store_n(&th->running, 1, __ATOMIC_RELEASE);
        syscall(SYS_futex, &th->running, FUTEX_WAKE);
        if (collide && call % 2)
          break;
        struct timespec ts;
        ts.tv_sec = 0;
        ts.tv_nsec = 20 * 1000 * 1000;
        syscall(SYS_futex, &th->running, FUTEX_WAIT, 1, &ts);
        if (running)
          usleep((call == num_calls - 1) ? 10000 : 1000);
        break;
      }
    }
  }
}

uint64_t r[3] = {0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff};
void execute_call(int call)
{
  long res;
  switch (call) {
  case 0:
    res = syscall(__NR_socket, 0xa, 1, 0);
    if (res != -1)
      r[0] = res;
    break;
  case 1:
    syscall(__NR_ioctl, r[0], 3, 0x200001c0);
    break;
  case 2:
    res = syscall(__NR_socket, 0xa, 1, 0);
    if (res != -1)
      r[1] = res;
    break;
  case 3:
    NONFAILING(*(uint32_t*)0x200000c0 = 1);
    syscall(__NR_setsockopt, r[1], 6, 0x13, 0x200000c0, 4);
    break;
  case 4:
    NONFAILING(*(uint16_t*)0x20000640 = 0xa);
    NONFAILING(*(uint16_t*)0x20000642 = htobe16(0));
    NONFAILING(*(uint32_t*)0x20000644 = 0);
    NONFAILING(*(uint8_t*)0x20000648 = 0xfe);
    NONFAILING(*(uint8_t*)0x20000649 = 0x80);
    NONFAILING(*(uint8_t*)0x2000064a = 0);
    NONFAILING(*(uint8_t*)0x2000064b = 0);
    NONFAILING(*(uint8_t*)0x2000064c = 0);
    NONFAILING(*(uint8_t*)0x2000064d = 0);
    NONFAILING(*(uint8_t*)0x2000064e = 0);
    NONFAILING(*(uint8_t*)0x2000064f = 0);
    NONFAILING(*(uint8_t*)0x20000650 = 0);
    NONFAILING(*(uint8_t*)0x20000651 = 0);
    NONFAILING(*(uint8_t*)0x20000652 = 0);
    NONFAILING(*(uint8_t*)0x20000653 = 0);
    NONFAILING(*(uint8_t*)0x20000654 = 0);
    NONFAILING(*(uint8_t*)0x20000655 = 0);
    NONFAILING(*(uint8_t*)0x20000656 = 0);
    NONFAILING(*(uint8_t*)0x20000657 = 0xbb);
    NONFAILING(*(uint32_t*)0x20000658 = 0);
    NONFAILING(*(uint16_t*)0x200006c0 = 0);
    NONFAILING(*(uint16_t*)0x200006c2 = 1);
    NONFAILING(*(uint32_t*)0x200006c4 = 0);
    NONFAILING(memcpy((void*)0x200006c8,
                      "\x0d\x77\xbd\xed\x71\x25\x33\x8d\xe4\x71\x45\xb7\x1f\x22"
                      "\x26\xc0\xb6\x95\x0f\xeb\xa5\x7b\x7d\x52\xd9\xe6\xd1\x35"
                      "\x09\xbb\x60\x2e\x48\x18\x22\x46\x96\xda\xfe\x09\xc2\x5e"
                      "\xd1\xd5\xe1\xe8\xdd\x95\x25\xd4\x42\x5e\x2c\x47\x07\xa0"
                      "\x0f\x8d\xd4\x7a\x4c\x19\xb8\x84\x28\x2e\x4f\x74\x3e\x00"
                      "\xc7\xa3\xef\xf5\x99\xb1\x3d\x51\x8d\x10",
                      80));
    syscall(__NR_setsockopt, r[1], 6, 0xe, 0x20000640, 0xd8);
    break;
  case 5:
    NONFAILING(*(uint16_t*)0x20000140 = 0xa);
    NONFAILING(*(uint16_t*)0x20000142 = htobe16(0));
    NONFAILING(*(uint32_t*)0x20000144 = 0);
    NONFAILING(*(uint64_t*)0x20000148 = htobe64(0));
    NONFAILING(*(uint64_t*)0x20000150 = htobe64(1));
    NONFAILING(*(uint32_t*)0x20000158 = 0);
    syscall(__NR_connect, r[1], 0x20000140, 0x1c);
    break;
  case 6:
    NONFAILING(memcpy((void*)0x20000340, "tls", 4));
    syscall(__NR_setsockopt, r[1], 6, 0x1f, 0x20000340, 4);
    break;
  case 7:
    NONFAILING(*(uint16_t*)0x20000100 = 0x303);
    NONFAILING(*(uint16_t*)0x20000102 = 0x33);
    syscall(__NR_setsockopt, r[1], 0x11a, 1, 0x20000100, 0x28);
    break;
  case 8:
    NONFAILING(*(uint16_t*)0x20000000 = 0xa);
    NONFAILING(*(uint16_t*)0x20000002 = htobe16(0));
    NONFAILING(*(uint32_t*)0x20000004 = 0);
    NONFAILING(*(uint8_t*)0x20000008 = 0xfe);
    NONFAILING(*(uint8_t*)0x20000009 = 0x80);
    NONFAILING(*(uint8_t*)0x2000000a = 0);
    NONFAILING(*(uint8_t*)0x2000000b = 0);
    NONFAILING(*(uint8_t*)0x2000000c = 0);
    NONFAILING(*(uint8_t*)0x2000000d = 0);
    NONFAILING(*(uint8_t*)0x2000000e = 0);
    NONFAILING(*(uint8_t*)0x2000000f = 0);
    NONFAILING(*(uint8_t*)0x20000010 = 0);
    NONFAILING(*(uint8_t*)0x20000011 = 0);
    NONFAILING(*(uint8_t*)0x20000012 = 0);
    NONFAILING(*(uint8_t*)0x20000013 = 0);
    NONFAILING(*(uint8_t*)0x20000014 = 0);
    NONFAILING(*(uint8_t*)0x20000015 = 0);
    NONFAILING(*(uint8_t*)0x20000016 = 0);
    NONFAILING(*(uint8_t*)0x20000017 = 0xbb);
    NONFAILING(*(uint32_t*)0x20000018 = 0);
    syscall(__NR_sendto, r[1], 0x200005c0, 0xfffffdef, 0, 0x20000000, 0x1c);
    break;
  case 9:
    res = syscall(__NR_socket, 2, 1, 0);
    if (res != -1)
      r[2] = res;
    break;
  case 10:
    NONFAILING(*(uint16_t*)0x20c16ff0 = 2);
    NONFAILING(*(uint16_t*)0x20c16ff2 = htobe16(1));
    NONFAILING(*(uint32_t*)0x20c16ff4 = htobe32(0xe0000001));
    NONFAILING(*(uint8_t*)0x20c16ff8 = 0);
    NONFAILING(*(uint8_t*)0x20c16ff9 = 0);
    NONFAILING(*(uint8_t*)0x20c16ffa = 0);
    NONFAILING(*(uint8_t*)0x20c16ffb = 0);
    NONFAILING(*(uint8_t*)0x20c16ffc = 0);
    NONFAILING(*(uint8_t*)0x20c16ffd = 0);
    NONFAILING(*(uint8_t*)0x20c16ffe = 0);
    NONFAILING(*(uint8_t*)0x20c16fff = 0);
    syscall(__NR_bind, r[2], 0x20c16ff0, 0x10);
    break;
  case 11:
    NONFAILING(*(uint16_t*)0x20e97fcf = 2);
    NONFAILING(*(uint16_t*)0x20e97fd1 = htobe16(1));
    NONFAILING(*(uint32_t*)0x20e97fd3 = htobe32(0x7f000001));
    NONFAILING(*(uint8_t*)0x20e97fd7 = 0);
    NONFAILING(*(uint8_t*)0x20e97fd8 = 0);
    NONFAILING(*(uint8_t*)0x20e97fd9 = 0);
    NONFAILING(*(uint8_t*)0x20e97fda = 0);
    NONFAILING(*(uint8_t*)0x20e97fdb = 0);
    NONFAILING(*(uint8_t*)0x20e97fdc = 0);
    NONFAILING(*(uint8_t*)0x20e97fdd = 0);
    NONFAILING(*(uint8_t*)0x20e97fde = 0);
    syscall(__NR_sendto, r[2], 0x20fa0fff, 0xffffffffffffffc3, 0x20020007,
            0x20e97fcf, 0x10);
    break;
  }
}

void execute_one()
{
  execute(12);
  collide = 1;
  execute(12);
}

int main()
{
  syscall(__NR_mmap, 0x20000000, 0x1000000, 3, 0x32, -1, 0);
  install_segv_handler();
  for (;;) {
    int pid = do_sandbox_none();
    int status = 0;
    while (waitpid(pid, &status, __WALL) != pid) {
    }
  }
}
