// possible deadlock in __snd_pcm_lib_xfer
// https://syzkaller.appspot.com/bug?id=6e5c88838328e99c7e1c
// status:0
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
  syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  intptr_t res = 0;
  memcpy((void*)0x20000080, "/dev/audio1\000", 12);
  res =
      syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000080ul, 0x129202ul, 0ul);
  if (res != -1)
    r[0] = res;
  *(uint32_t*)0x20000000 = 0x20;
  syscall(__NR_ioctl, r[0], 0xc0045005, 0x20000000ul);
  *(uint32_t*)0x20000040 = 0;
  syscall(__NR_ioctl, r[0], 0xc004500a, 0x20000040ul);
  syscall(__NR_mmap, 0x20ffd000ul, 0x2000ul, 0x100000aul, 0x11ul, r[0], 0ul);
  memcpy((void*)0x20000080, "/dev/dsp1\000", 10);
  res = syscall(__NR_openat, 0xffffffffffffff9cul, 0x20000080ul, 0ul, 0ul);
  if (res != -1)
    r[1] = res;
  *(uint32_t*)0x20000000 = 0;
  syscall(__NR_ioctl, r[1], 0xc004500a, 0x20000000ul);
  *(uint32_t*)0x200000c0 = 0x1000;
  syscall(__NR_ioctl, r[1], 0xc0045005, 0x200000c0ul);
  syscall(__NR_read, r[1], 0x20000780ul, 0xff2ul);
  return 0;
}
