// KASAN: use-after-free Write in __unwind_start (2)
// https://syzkaller.appspot.com/bug?id=744b8267432cf9dae35c55af4afd83bf43d8e5ec
// status:invalid
// autogenerated by syzkaller (http://github.com/google/syzkaller)

#define _GNU_SOURCE
#include <arpa/inet.h>
#include <endian.h>
#include <errno.h>
#include <errno.h>
#include <errno.h>
#include <fcntl.h>
#include <linux/futex.h>
#include <linux/if.h>
#include <linux/if_ether.h>
#include <linux/if_tun.h>
#include <linux/ip.h>
#include <linux/net.h>
#include <linux/tcp.h>
#include <net/if_arp.h>
#include <netinet/in.h>
#include <pthread.h>
#include <sched.h>
#include <signal.h>
#include <signal.h>
#include <stdarg.h>
#include <stdarg.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdio.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdlib.h>
#include <sys/ioctl.h>
#include <sys/prctl.h>
#include <sys/prctl.h>
#include <sys/resource.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/time.h>
#include <sys/time.h>
#include <sys/uio.h>
#include <sys/wait.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

__attribute__((noreturn)) static void doexit(int status)
{
  volatile unsigned i;
  syscall(__NR_exit_group, status);
  for (i = 0;; i++) {
  }
}
#include <stdint.h>
#include <string.h>

const int kFailStatus = 67;
const int kRetryStatus = 69;

static void fail(const char* msg, ...)
{
  int e = errno;
  va_list args;
  va_start(args, msg);
  vfprintf(stderr, msg, args);
  va_end(args);
  fprintf(stderr, " (errno %d)\n", e);
  doexit((e == ENOMEM || e == EAGAIN) ? kRetryStatus : kFailStatus);
}

#define BITMASK_LEN(type, bf_len) (type)((1ull << (bf_len)) - 1)

#define BITMASK_LEN_OFF(type, bf_off, bf_len)                                  \
  (type)(BITMASK_LEN(type, (bf_len)) << (bf_off))

#define STORE_BY_BITMASK(type, addr, val, bf_off, bf_len)                      \
  if ((bf_off) == 0 && (bf_len) == 0) {                                        \
    *(type*)(addr) = (type)(val);                                              \
  } else {                                                                     \
    type new_val = *(type*)(addr);                                             \
    new_val &= ~BITMASK_LEN_OFF(type, (bf_off), (bf_len));                     \
    new_val |= ((type)(val)&BITMASK_LEN(type, (bf_len))) << (bf_off);          \
    *(type*)(addr) = new_val;                                                  \
  }

struct csum_inet {
  uint32_t acc;
};

static void csum_inet_init(struct csum_inet* csum)
{
  csum->acc = 0;
}

static void csum_inet_update(struct csum_inet* csum, const uint8_t* data,
                             size_t length)
{
  if (length == 0)
    return;

  size_t i;
  for (i = 0; i < length - 1; i += 2)
    csum->acc += *(uint16_t*)&data[i];

  if (length & 1)
    csum->acc += (uint16_t)data[length - 1];

  while (csum->acc > 0xffff)
    csum->acc = (csum->acc & 0xffff) + (csum->acc >> 16);
}

static uint16_t csum_inet_digest(struct csum_inet* csum)
{
  return ~csum->acc;
}

static uint64_t current_time_ms()
{
  struct timespec ts;

  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    fail("clock_gettime failed");
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

static void vsnprintf_check(char* str, size_t size, const char* format,
                            va_list args)
{
  int rv;

  rv = vsnprintf(str, size, format, args);
  if (rv < 0)
    fail("tun: snprintf failed");
  if ((size_t)rv >= size)
    fail("tun: string '%s...' doesn't fit into buffer", str);
}

static void snprintf_check(char* str, size_t size, const char* format, ...)
{
  va_list args;

  va_start(args, format);
  vsnprintf_check(str, size, format, args);
  va_end(args);
}

#define COMMAND_MAX_LEN 128
#define PATH_PREFIX                                                            \
  "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin "
#define PATH_PREFIX_LEN (sizeof(PATH_PREFIX) - 1)

static void execute_command(bool panic, const char* format, ...)
{
  va_list args;
  char command[PATH_PREFIX_LEN + COMMAND_MAX_LEN];
  int rv;

  va_start(args, format);
  memcpy(command, PATH_PREFIX, PATH_PREFIX_LEN);
  vsnprintf_check(command + PATH_PREFIX_LEN, COMMAND_MAX_LEN, format, args);
  rv = system(command);
  if (panic && rv != 0)
    fail("tun: command \"%s\" failed with code %d", &command[0], rv);

  va_end(args);
}

static int tunfd = -1;
static int tun_frags_enabled;

#define SYZ_TUN_MAX_PACKET_SIZE 1000

#define TUN_IFACE "syz_tun"

#define LOCAL_MAC "aa:aa:aa:aa:aa:aa"
#define REMOTE_MAC "aa:aa:aa:aa:aa:bb"

#define LOCAL_IPV4 "172.20.20.170"
#define REMOTE_IPV4 "172.20.20.187"

#define LOCAL_IPV6 "fe80::aa"
#define REMOTE_IPV6 "fe80::bb"

#define IFF_NAPI 0x0010
#define IFF_NAPI_FRAGS 0x0020

static void initialize_tun(void)
{
  tunfd = open("/dev/net/tun", O_RDWR | O_NONBLOCK);
  if (tunfd == -1) {
    printf("tun: can't open /dev/net/tun: please enable CONFIG_TUN=y\n");
    printf("otherwise fuzzing or reproducing might not work as intended\n");
    return;
  }
  const int kTunFd = 252;
  if (dup2(tunfd, kTunFd) < 0)
    fail("dup2(tunfd, kTunFd) failed");
  close(tunfd);
  tunfd = kTunFd;

  struct ifreq ifr;
  memset(&ifr, 0, sizeof(ifr));
  strncpy(ifr.ifr_name, TUN_IFACE, IFNAMSIZ);
  ifr.ifr_flags = IFF_TAP | IFF_NO_PI | IFF_NAPI | IFF_NAPI_FRAGS;
  if (ioctl(tunfd, TUNSETIFF, (void*)&ifr) < 0) {
    ifr.ifr_flags = IFF_TAP | IFF_NO_PI;
    if (ioctl(tunfd, TUNSETIFF, (void*)&ifr) < 0)
      fail("tun: ioctl(TUNSETIFF) failed");
  }
  if (ioctl(tunfd, TUNGETIFF, (void*)&ifr) < 0)
    fail("tun: ioctl(TUNGETIFF) failed");
  tun_frags_enabled = (ifr.ifr_flags & IFF_NAPI_FRAGS) != 0;

  execute_command(1, "sysctl -w net.ipv6.conf.%s.accept_dad=0", TUN_IFACE);

  execute_command(1, "sysctl -w net.ipv6.conf.%s.router_solicitations=0",
                  TUN_IFACE);

  execute_command(1, "ip link set dev %s address %s", TUN_IFACE, LOCAL_MAC);
  execute_command(1, "ip addr add %s/24 dev %s", LOCAL_IPV4, TUN_IFACE);
  execute_command(1, "ip -6 addr add %s/120 dev %s", LOCAL_IPV6, TUN_IFACE);
  execute_command(1, "ip neigh add %s lladdr %s dev %s nud permanent",
                  REMOTE_IPV4, REMOTE_MAC, TUN_IFACE);
  execute_command(1, "ip -6 neigh add %s lladdr %s dev %s nud permanent",
                  REMOTE_IPV6, REMOTE_MAC, TUN_IFACE);
  execute_command(1, "ip link set dev %s up", TUN_IFACE);
}

#define DEV_IPV4 "172.20.20.%d"
#define DEV_IPV6 "fe80::%02hx"
#define DEV_MAC "aa:aa:aa:aa:aa:%02hx"

static void initialize_netdevices(void)
{
  unsigned i;
  const char* devtypes[] = {"ip6gretap", "bridge", "vcan", "bond", "veth"};
  const char* devnames[] = {"lo",       "sit0",    "bridge0", "vcan0",
                            "tunl0",    "gre0",    "gretap0", "ip_vti0",
                            "ip6_vti0", "ip6tnl0", "ip6gre0", "ip6gretap0",
                            "erspan0",  "bond0",   "veth0",   "veth1"};

  for (i = 0; i < sizeof(devtypes) / (sizeof(devtypes[0])); i++)
    execute_command(0, "ip link add dev %s0 type %s", devtypes[i], devtypes[i]);
  execute_command(0, "ip link add dev veth1 type veth");
  for (i = 0; i < sizeof(devnames) / (sizeof(devnames[0])); i++) {
    char addr[32];
    snprintf_check(addr, sizeof(addr), DEV_IPV4, i + 10);
    execute_command(0, "ip -4 addr add %s/24 dev %s", addr, devnames[i]);
    snprintf_check(addr, sizeof(addr), DEV_IPV6, i + 10);
    execute_command(0, "ip -6 addr add %s/120 dev %s", addr, devnames[i]);
    snprintf_check(addr, sizeof(addr), DEV_MAC, i + 10);
    execute_command(0, "ip link set dev %s address %s", devnames[i], addr);
    execute_command(0, "ip link set dev %s up", devnames[i]);
  }
}

static int read_tun(char* data, int size)
{
  if (tunfd < 0)
    return -1;

  int rv = read(tunfd, data, size);
  if (rv < 0) {
    if (errno == EAGAIN)
      return -1;
    if (errno == EBADFD)
      return -1;
    fail("tun: read failed with %d", rv);
  }
  return rv;
}

#define MAX_FRAGS 4
struct vnet_fragmentation {
  uint32_t full;
  uint32_t count;
  uint32_t frags[MAX_FRAGS];
};

static uintptr_t syz_emit_ethernet(uintptr_t a0, uintptr_t a1, uintptr_t a2)
{
  if (tunfd < 0)
    return (uintptr_t)-1;

  uint32_t length = a0;
  char* data = (char*)a1;

  struct vnet_fragmentation* frags = (struct vnet_fragmentation*)a2;
  struct iovec vecs[MAX_FRAGS + 1];
  uint32_t nfrags = 0;
  if (!tun_frags_enabled || frags == NULL) {
    vecs[nfrags].iov_base = data;
    vecs[nfrags].iov_len = length;
    nfrags++;
  } else {
    bool full = true;
    uint32_t i, count = 0;
    full = frags->full;
    count = frags->count;
    if (count > MAX_FRAGS)
      count = MAX_FRAGS;
    for (i = 0; i < count && length != 0; i++) {
      uint32_t size = 0;
      size = frags->frags[i];
      if (size > length)
        size = length;
      vecs[nfrags].iov_base = data;
      vecs[nfrags].iov_len = size;
      nfrags++;
      data += size;
      length -= size;
    }
    if (length != 0 && (full || nfrags == 0)) {
      vecs[nfrags].iov_base = data;
      vecs[nfrags].iov_len = length;
      nfrags++;
    }
  }
  return writev(tunfd, vecs, nfrags);
}

static void flush_tun()
{
  char data[SYZ_TUN_MAX_PACKET_SIZE];
  while (read_tun(&data[0], sizeof(data)) != -1)
    ;
}

static void loop();

static void sandbox_common()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  setsid();

  struct rlimit rlim;
  rlim.rlim_cur = rlim.rlim_max = 128 << 20;
  setrlimit(RLIMIT_AS, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 8 << 20;
  setrlimit(RLIMIT_MEMLOCK, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 1 << 20;
  setrlimit(RLIMIT_FSIZE, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 1 << 20;
  setrlimit(RLIMIT_STACK, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 0;
  setrlimit(RLIMIT_CORE, &rlim);

#define CLONE_NEWCGROUP 0x02000000

  if (unshare(CLONE_NEWNS)) {
  }
  if (unshare(CLONE_NEWIPC)) {
  }
  if (unshare(CLONE_NEWCGROUP)) {
  }
  if (unshare(CLONE_NEWUTS)) {
  }
  if (unshare(CLONE_SYSVSEM)) {
  }
}

static int do_sandbox_none(void)
{
  if (unshare(CLONE_NEWPID)) {
  }
  int pid = fork();
  if (pid < 0)
    fail("sandbox fork failed");
  if (pid)
    return pid;

  sandbox_common();
  if (unshare(CLONE_NEWNET)) {
  }
  initialize_tun();
  initialize_netdevices();

  loop();
  doexit(1);
}

#define XT_TABLE_SIZE 1536
#define XT_MAX_ENTRIES 10

struct xt_counters {
  uint64_t pcnt, bcnt;
};

struct ipt_getinfo {
  char name[32];
  unsigned int valid_hooks;
  unsigned int hook_entry[5];
  unsigned int underflow[5];
  unsigned int num_entries;
  unsigned int size;
};

struct ipt_get_entries {
  char name[32];
  unsigned int size;
  void* entrytable[XT_TABLE_SIZE / sizeof(void*)];
};

struct ipt_replace {
  char name[32];
  unsigned int valid_hooks;
  unsigned int num_entries;
  unsigned int size;
  unsigned int hook_entry[5];
  unsigned int underflow[5];
  unsigned int num_counters;
  struct xt_counters* counters;
  char entrytable[XT_TABLE_SIZE];
};

struct ipt_table_desc {
  const char* name;
  struct ipt_getinfo info;
  struct ipt_replace replace;
};

static struct ipt_table_desc ipv4_tables[] = {
    {.name = "filter"}, {.name = "nat"},      {.name = "mangle"},
    {.name = "raw"},    {.name = "security"},
};

static struct ipt_table_desc ipv6_tables[] = {
    {.name = "filter"}, {.name = "nat"},      {.name = "mangle"},
    {.name = "raw"},    {.name = "security"},
};

#define IPT_BASE_CTL 64
#define IPT_SO_SET_REPLACE (IPT_BASE_CTL)
#define IPT_SO_GET_INFO (IPT_BASE_CTL)
#define IPT_SO_GET_ENTRIES (IPT_BASE_CTL + 1)

struct arpt_getinfo {
  char name[32];
  unsigned int valid_hooks;
  unsigned int hook_entry[3];
  unsigned int underflow[3];
  unsigned int num_entries;
  unsigned int size;
};

struct arpt_get_entries {
  char name[32];
  unsigned int size;
  void* entrytable[XT_TABLE_SIZE / sizeof(void*)];
};

struct arpt_replace {
  char name[32];
  unsigned int valid_hooks;
  unsigned int num_entries;
  unsigned int size;
  unsigned int hook_entry[3];
  unsigned int underflow[3];
  unsigned int num_counters;
  struct xt_counters* counters;
  char entrytable[XT_TABLE_SIZE];
};

struct arpt_table_desc {
  const char* name;
  struct arpt_getinfo info;
  struct arpt_replace replace;
};

static struct arpt_table_desc arpt_tables[] = {
    {.name = "filter"},
};

#define ARPT_BASE_CTL 96
#define ARPT_SO_SET_REPLACE (ARPT_BASE_CTL)
#define ARPT_SO_GET_INFO (ARPT_BASE_CTL)
#define ARPT_SO_GET_ENTRIES (ARPT_BASE_CTL + 1)

static void checkpoint_iptables(struct ipt_table_desc* tables, int num_tables,
                                int family, int level)
{
  struct ipt_get_entries entries;
  socklen_t optlen;
  int fd, i;

  fd = socket(family, SOCK_STREAM, IPPROTO_TCP);
  if (fd == -1)
    fail("socket(%d, SOCK_STREAM, IPPROTO_TCP)", family);
  for (i = 0; i < num_tables; i++) {
    struct ipt_table_desc* table = &tables[i];
    strcpy(table->info.name, table->name);
    strcpy(table->replace.name, table->name);
    optlen = sizeof(table->info);
    if (getsockopt(fd, level, IPT_SO_GET_INFO, &table->info, &optlen)) {
      switch (errno) {
      case EPERM:
      case ENOENT:
      case ENOPROTOOPT:
        continue;
      }
      fail("getsockopt(IPT_SO_GET_INFO)");
    }
    if (table->info.size > sizeof(table->replace.entrytable))
      fail("table size is too large: %u", table->info.size);
    if (table->info.num_entries > XT_MAX_ENTRIES)
      fail("too many counters: %u", table->info.num_entries);
    memset(&entries, 0, sizeof(entries));
    strcpy(entries.name, table->name);
    entries.size = table->info.size;
    optlen = sizeof(entries) - sizeof(entries.entrytable) + table->info.size;
    if (getsockopt(fd, level, IPT_SO_GET_ENTRIES, &entries, &optlen))
      fail("getsockopt(IPT_SO_GET_ENTRIES)");
    table->replace.valid_hooks = table->info.valid_hooks;
    table->replace.num_entries = table->info.num_entries;
    table->replace.size = table->info.size;
    memcpy(table->replace.hook_entry, table->info.hook_entry,
           sizeof(table->replace.hook_entry));
    memcpy(table->replace.underflow, table->info.underflow,
           sizeof(table->replace.underflow));
    memcpy(table->replace.entrytable, entries.entrytable, table->info.size);
  }
  close(fd);
}

static void reset_iptables(struct ipt_table_desc* tables, int num_tables,
                           int family, int level)
{
  struct xt_counters counters[XT_MAX_ENTRIES];
  struct ipt_get_entries entries;
  struct ipt_getinfo info;
  socklen_t optlen;
  int fd, i;

  fd = socket(family, SOCK_STREAM, IPPROTO_TCP);
  if (fd == -1)
    fail("socket(%d, SOCK_STREAM, IPPROTO_TCP)", family);
  for (i = 0; i < num_tables; i++) {
    struct ipt_table_desc* table = &tables[i];
    if (table->info.valid_hooks == 0)
      continue;
    memset(&info, 0, sizeof(info));
    strcpy(info.name, table->name);
    optlen = sizeof(info);
    if (getsockopt(fd, level, IPT_SO_GET_INFO, &info, &optlen))
      fail("getsockopt(IPT_SO_GET_INFO)");
    if (memcmp(&table->info, &info, sizeof(table->info)) == 0) {
      memset(&entries, 0, sizeof(entries));
      strcpy(entries.name, table->name);
      entries.size = table->info.size;
      optlen = sizeof(entries) - sizeof(entries.entrytable) + entries.size;
      if (getsockopt(fd, level, IPT_SO_GET_ENTRIES, &entries, &optlen))
        fail("getsockopt(IPT_SO_GET_ENTRIES)");
      if (memcmp(table->replace.entrytable, entries.entrytable,
                 table->info.size) == 0)
        continue;
    }
    table->replace.num_counters = info.num_entries;
    table->replace.counters = counters;
    optlen = sizeof(table->replace) - sizeof(table->replace.entrytable) +
             table->replace.size;
    if (setsockopt(fd, level, IPT_SO_SET_REPLACE, &table->replace, optlen))
      fail("setsockopt(IPT_SO_SET_REPLACE)");
  }
  close(fd);
}

static void checkpoint_arptables(void)
{
  struct arpt_get_entries entries;
  socklen_t optlen;
  unsigned i;
  int fd;

  fd = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
  if (fd == -1)
    fail("socket(AF_INET, SOCK_STREAM, IPPROTO_TCP)");
  for (i = 0; i < sizeof(arpt_tables) / sizeof(arpt_tables[0]); i++) {
    struct arpt_table_desc* table = &arpt_tables[i];
    strcpy(table->info.name, table->name);
    strcpy(table->replace.name, table->name);
    optlen = sizeof(table->info);
    if (getsockopt(fd, SOL_IP, ARPT_SO_GET_INFO, &table->info, &optlen)) {
      switch (errno) {
      case EPERM:
      case ENOENT:
      case ENOPROTOOPT:
        continue;
      }
      fail("getsockopt(ARPT_SO_GET_INFO)");
    }
    if (table->info.size > sizeof(table->replace.entrytable))
      fail("table size is too large: %u", table->info.size);
    if (table->info.num_entries > XT_MAX_ENTRIES)
      fail("too many counters: %u", table->info.num_entries);
    memset(&entries, 0, sizeof(entries));
    strcpy(entries.name, table->name);
    entries.size = table->info.size;
    optlen = sizeof(entries) - sizeof(entries.entrytable) + table->info.size;
    if (getsockopt(fd, SOL_IP, ARPT_SO_GET_ENTRIES, &entries, &optlen))
      fail("getsockopt(ARPT_SO_GET_ENTRIES)");
    table->replace.valid_hooks = table->info.valid_hooks;
    table->replace.num_entries = table->info.num_entries;
    table->replace.size = table->info.size;
    memcpy(table->replace.hook_entry, table->info.hook_entry,
           sizeof(table->replace.hook_entry));
    memcpy(table->replace.underflow, table->info.underflow,
           sizeof(table->replace.underflow));
    memcpy(table->replace.entrytable, entries.entrytable, table->info.size);
  }
  close(fd);
}

static void reset_arptables()
{
  struct xt_counters counters[XT_MAX_ENTRIES];
  struct arpt_get_entries entries;
  struct arpt_getinfo info;
  socklen_t optlen;
  unsigned i;
  int fd;

  fd = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
  if (fd == -1)
    fail("socket(AF_INET, SOCK_STREAM, IPPROTO_TCP)");
  for (i = 0; i < sizeof(arpt_tables) / sizeof(arpt_tables[0]); i++) {
    struct arpt_table_desc* table = &arpt_tables[i];
    if (table->info.valid_hooks == 0)
      continue;
    memset(&info, 0, sizeof(info));
    strcpy(info.name, table->name);
    optlen = sizeof(info);
    if (getsockopt(fd, SOL_IP, ARPT_SO_GET_INFO, &info, &optlen))
      fail("getsockopt(ARPT_SO_GET_INFO)");
    if (memcmp(&table->info, &info, sizeof(table->info)) == 0) {
      memset(&entries, 0, sizeof(entries));
      strcpy(entries.name, table->name);
      entries.size = table->info.size;
      optlen = sizeof(entries) - sizeof(entries.entrytable) + entries.size;
      if (getsockopt(fd, SOL_IP, ARPT_SO_GET_ENTRIES, &entries, &optlen))
        fail("getsockopt(ARPT_SO_GET_ENTRIES)");
      if (memcmp(table->replace.entrytable, entries.entrytable,
                 table->info.size) == 0)
        continue;
    }
    table->replace.num_counters = info.num_entries;
    table->replace.counters = counters;
    optlen = sizeof(table->replace) - sizeof(table->replace.entrytable) +
             table->replace.size;
    if (setsockopt(fd, SOL_IP, ARPT_SO_SET_REPLACE, &table->replace, optlen))
      fail("setsockopt(ARPT_SO_SET_REPLACE)");
  }
  close(fd);
}
#include <linux/if.h>
#include <linux/netfilter_bridge/ebtables.h>

struct ebt_table_desc {
  const char* name;
  struct ebt_replace replace;
  char entrytable[XT_TABLE_SIZE];
};

static struct ebt_table_desc ebt_tables[] = {
    {.name = "filter"}, {.name = "nat"}, {.name = "broute"},
};

static void checkpoint_ebtables(void)
{
  socklen_t optlen;
  unsigned i;
  int fd;

  fd = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
  if (fd == -1)
    fail("socket(AF_INET, SOCK_STREAM, IPPROTO_TCP)");
  for (i = 0; i < sizeof(ebt_tables) / sizeof(ebt_tables[0]); i++) {
    struct ebt_table_desc* table = &ebt_tables[i];
    strcpy(table->replace.name, table->name);
    optlen = sizeof(table->replace);
    if (getsockopt(fd, SOL_IP, EBT_SO_GET_INIT_INFO, &table->replace,
                   &optlen)) {
      switch (errno) {
      case EPERM:
      case ENOENT:
      case ENOPROTOOPT:
        continue;
      }
      fail("getsockopt(EBT_SO_GET_INIT_INFO)");
    }
    if (table->replace.entries_size > sizeof(table->entrytable))
      fail("table size is too large: %u", table->replace.entries_size);
    table->replace.num_counters = 0;
    table->replace.entries = table->entrytable;
    optlen = sizeof(table->replace) + table->replace.entries_size;
    if (getsockopt(fd, SOL_IP, EBT_SO_GET_INIT_ENTRIES, &table->replace,
                   &optlen))
      fail("getsockopt(EBT_SO_GET_INIT_ENTRIES)");
  }
  close(fd);
}

static void reset_ebtables()
{
  struct ebt_replace replace;
  char entrytable[XT_TABLE_SIZE];
  socklen_t optlen;
  unsigned i, j, h;
  int fd;

  fd = socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
  if (fd == -1)
    fail("socket(AF_INET, SOCK_STREAM, IPPROTO_TCP)");
  for (i = 0; i < sizeof(ebt_tables) / sizeof(ebt_tables[0]); i++) {
    struct ebt_table_desc* table = &ebt_tables[i];
    if (table->replace.valid_hooks == 0)
      continue;
    memset(&replace, 0, sizeof(replace));
    strcpy(replace.name, table->name);
    optlen = sizeof(replace);
    if (getsockopt(fd, SOL_IP, EBT_SO_GET_INFO, &replace, &optlen))
      fail("getsockopt(EBT_SO_GET_INFO)");
    replace.num_counters = 0;
    for (h = 0; h < NF_BR_NUMHOOKS; h++)
      table->replace.hook_entry[h] = 0;
    if (memcmp(&table->replace, &replace, sizeof(table->replace)) == 0) {
      memset(&entrytable, 0, sizeof(entrytable));
      replace.entries = entrytable;
      optlen = sizeof(replace) + replace.entries_size;
      if (getsockopt(fd, SOL_IP, EBT_SO_GET_ENTRIES, &replace, &optlen))
        fail("getsockopt(EBT_SO_GET_ENTRIES)");
      if (memcmp(table->entrytable, entrytable, replace.entries_size) == 0)
        continue;
    }
    for (j = 0, h = 0; h < NF_BR_NUMHOOKS; h++) {
      if (table->replace.valid_hooks & (1 << h)) {
        table->replace.hook_entry[h] =
            (struct ebt_entries*)table->entrytable + j;
        j++;
      }
    }
    optlen = sizeof(table->replace) + table->replace.entries_size;
    if (setsockopt(fd, SOL_IP, EBT_SO_SET_ENTRIES, &table->replace, optlen))
      fail("setsockopt(EBT_SO_SET_ENTRIES)");
  }
  close(fd);
}

static void checkpoint_net_namespace(void)
{
  checkpoint_ebtables();
  checkpoint_arptables();
  checkpoint_iptables(ipv4_tables, sizeof(ipv4_tables) / sizeof(ipv4_tables[0]),
                      AF_INET, SOL_IP);
  checkpoint_iptables(ipv6_tables, sizeof(ipv6_tables) / sizeof(ipv6_tables[0]),
                      AF_INET6, SOL_IPV6);
}

static void reset_net_namespace(void)
{
  reset_ebtables();
  reset_arptables();
  reset_iptables(ipv4_tables, sizeof(ipv4_tables) / sizeof(ipv4_tables[0]),
                 AF_INET, SOL_IP);
  reset_iptables(ipv6_tables, sizeof(ipv6_tables) / sizeof(ipv6_tables[0]),
                 AF_INET6, SOL_IPV6);
}

static void test();

void loop()
{
  int iter;
  checkpoint_net_namespace();
  for (iter = 0;; iter++) {
    int pid = fork();
    if (pid < 0)
      fail("loop fork failed");
    if (pid == 0) {
      prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
      setpgrp();
      flush_tun();
      test();
      doexit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      int res = waitpid(-1, &status, __WALL | WNOHANG);
      if (res == pid)
        break;
      usleep(1000);
      if (current_time_ms() - start > 5 * 1000) {
        kill(-pid, SIGKILL);
        kill(pid, SIGKILL);
        while (waitpid(-1, &status, __WALL) != pid) {
        }
        break;
      }
    }
    reset_net_namespace();
  }
}

struct thread_t {
  int created, running, call;
  pthread_t th;
};

static struct thread_t threads[16];
static void execute_call(int call);
static int running;

static void* thr(void* arg)
{
  struct thread_t* th = (struct thread_t*)arg;
  for (;;) {
    while (!__atomic_load_n(&th->running, __ATOMIC_ACQUIRE))
      syscall(SYS_futex, &th->running, FUTEX_WAIT, 0, 0);
    execute_call(th->call);
    __atomic_fetch_sub(&running, 1, __ATOMIC_RELAXED);
    __atomic_store_n(&th->running, 0, __ATOMIC_RELEASE);
    syscall(SYS_futex, &th->running, FUTEX_WAKE);
  }
  return 0;
}

static void execute(int num_calls)
{
  int call, thread;
  running = 0;
  for (call = 0; call < num_calls; call++) {
    for (thread = 0; thread < sizeof(threads) / sizeof(threads[0]); thread++) {
      struct thread_t* th = &threads[thread];
      if (!th->created) {
        th->created = 1;
        pthread_attr_t attr;
        pthread_attr_init(&attr);
        pthread_attr_setstacksize(&attr, 128 << 10);
        pthread_create(&th->th, &attr, thr, th);
      }
      if (!__atomic_load_n(&th->running, __ATOMIC_ACQUIRE)) {
        th->call = call;
        __atomic_fetch_add(&running, 1, __ATOMIC_RELAXED);
        __atomic_store_n(&th->running, 1, __ATOMIC_RELEASE);
        syscall(SYS_futex, &th->running, FUTEX_WAKE);
        struct timespec ts;
        ts.tv_sec = 0;
        ts.tv_nsec = 20 * 1000 * 1000;
        syscall(SYS_futex, &th->running, FUTEX_WAIT, 1, &ts);
        if (running)
          usleep((call == num_calls - 1) ? 10000 : 1000);
        break;
      }
    }
  }
}

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};
uint64_t procid;
void execute_call(int call)
{
  long res;
  switch (call) {
  case 0:
    *(uint32_t*)0x2001d000 = 2;
    *(uint32_t*)0x2001d004 = 0x196;
    *(uint8_t*)0x2001d008 = 0x66;
    *(uint8_t*)0x2001d009 = 1;
    *(uint8_t*)0x2001d00a = 0;
    *(uint8_t*)0x2001d00b = 0;
    *(uint32_t*)0x2001d00c = 0;
    *(uint64_t*)0x2001d010 = 0;
    *(uint64_t*)0x2001d018 = 0;
    *(uint64_t*)0x2001d020 = 0;
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 0, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 1, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 2, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 3, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 4, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, -1, 5, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 6, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 7, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 8, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 9, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 10, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 11, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 12, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 13, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 14, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 15, 2);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 17, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 18, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 19, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 20, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 21, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 22, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 23, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 24, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 25, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 26, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 27, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 28, 1);
    STORE_BY_BITMASK(uint64_t, 0x2001d028, 0, 29, 35);
    *(uint32_t*)0x2001d030 = 0;
    *(uint32_t*)0x2001d034 = 0;
    *(uint64_t*)0x2001d038 = 0x20000000;
    *(uint64_t*)0x2001d040 = 0;
    *(uint64_t*)0x2001d048 = 0;
    *(uint64_t*)0x2001d050 = 0;
    *(uint64_t*)0x2001d058 = 0;
    *(uint32_t*)0x2001d060 = 0;
    *(uint64_t*)0x2001d068 = 0;
    *(uint32_t*)0x2001d070 = 0;
    *(uint16_t*)0x2001d074 = 0;
    *(uint16_t*)0x2001d076 = 0;
    syscall(__NR_perf_event_open, 0x2001d000, 0, -1, -1, 0);
    break;
  case 1:
    res = syscall(__NR_socket, 0xa, 0x801, 0);
    if (res != -1)
      r[0] = res;
    break;
  case 2:
    memcpy((void*)0x20000000, "\x6e\x61\x74\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                              "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                              "\x00\x00\x00\x00\x00\x00\x00\x00",
           32);
    *(uint32_t*)0x20000020 = 0x1b;
    *(uint32_t*)0x20000024 = 5;
    *(uint32_t*)0x20000028 = 0x358;
    *(uint32_t*)0x2000002c = 0;
    *(uint32_t*)0x20000030 = 0x170;
    *(uint32_t*)0x20000034 = -1;
    *(uint32_t*)0x20000038 = 0x170;
    *(uint32_t*)0x2000003c = 0x218;
    *(uint32_t*)0x20000040 = 0x2c0;
    *(uint32_t*)0x20000044 = 0x2c0;
    *(uint32_t*)0x20000048 = -1;
    *(uint32_t*)0x2000004c = 0x2c0;
    *(uint32_t*)0x20000050 = 0x2c0;
    *(uint32_t*)0x20000054 = 5;
    *(uint64_t*)0x20000058 = 0x20002fb0;
    *(uint8_t*)0x20000060 = 0;
    *(uint8_t*)0x20000061 = 0;
    *(uint8_t*)0x20000062 = 0;
    *(uint8_t*)0x20000063 = 0;
    *(uint8_t*)0x20000064 = 0;
    *(uint8_t*)0x20000065 = 0;
    *(uint8_t*)0x20000066 = 0;
    *(uint8_t*)0x20000067 = 0;
    *(uint8_t*)0x20000068 = 0;
    *(uint8_t*)0x20000069 = 0;
    *(uint8_t*)0x2000006a = 0;
    *(uint8_t*)0x2000006b = 0;
    *(uint8_t*)0x2000006c = 0;
    *(uint8_t*)0x2000006d = 0;
    *(uint8_t*)0x2000006e = 0;
    *(uint8_t*)0x2000006f = 0;
    *(uint8_t*)0x20000070 = 0;
    *(uint8_t*)0x20000071 = 0;
    *(uint8_t*)0x20000072 = 0;
    *(uint8_t*)0x20000073 = 0;
    *(uint8_t*)0x20000074 = 0;
    *(uint8_t*)0x20000075 = 0;
    *(uint8_t*)0x20000076 = 0;
    *(uint8_t*)0x20000077 = 0;
    *(uint8_t*)0x20000078 = 0;
    *(uint8_t*)0x20000079 = 0;
    *(uint8_t*)0x2000007a = 0;
    *(uint8_t*)0x2000007b = 0;
    *(uint8_t*)0x2000007c = 0;
    *(uint8_t*)0x2000007d = 0;
    *(uint8_t*)0x2000007e = 0;
    *(uint8_t*)0x2000007f = 0;
    *(uint8_t*)0x20000080 = 0;
    *(uint8_t*)0x20000081 = 0;
    *(uint8_t*)0x20000082 = 0;
    *(uint8_t*)0x20000083 = 0;
    *(uint8_t*)0x20000084 = 0;
    *(uint8_t*)0x20000085 = 0;
    *(uint8_t*)0x20000086 = 0;
    *(uint8_t*)0x20000087 = 0;
    *(uint8_t*)0x20000088 = 0;
    *(uint8_t*)0x20000089 = 0;
    *(uint8_t*)0x2000008a = 0;
    *(uint8_t*)0x2000008b = 0;
    *(uint8_t*)0x2000008c = 0;
    *(uint8_t*)0x2000008d = 0;
    *(uint8_t*)0x2000008e = 0;
    *(uint8_t*)0x2000008f = 0;
    *(uint8_t*)0x20000090 = 0;
    *(uint8_t*)0x20000091 = 0;
    *(uint8_t*)0x20000092 = 0;
    *(uint8_t*)0x20000093 = 0;
    *(uint8_t*)0x20000094 = 0;
    *(uint8_t*)0x20000095 = 0;
    *(uint8_t*)0x20000096 = 0;
    *(uint8_t*)0x20000097 = 0;
    *(uint8_t*)0x20000098 = 0;
    *(uint8_t*)0x20000099 = 0;
    *(uint8_t*)0x2000009a = 0;
    *(uint8_t*)0x2000009b = 0;
    *(uint8_t*)0x2000009c = 0;
    *(uint8_t*)0x2000009d = 0;
    *(uint8_t*)0x2000009e = 0;
    *(uint8_t*)0x2000009f = 0;
    *(uint8_t*)0x200000a0 = 0;
    *(uint8_t*)0x200000a1 = 0;
    *(uint8_t*)0x200000a2 = 0;
    *(uint8_t*)0x200000a3 = 0;
    *(uint8_t*)0x200000a4 = 0;
    *(uint8_t*)0x200000a5 = 0;
    *(uint8_t*)0x200000a6 = 0;
    *(uint8_t*)0x200000a7 = 0;
    *(uint8_t*)0x200000a8 = 0;
    *(uint8_t*)0x200000a9 = 0;
    *(uint8_t*)0x200000aa = 0;
    *(uint8_t*)0x200000ab = 0;
    *(uint8_t*)0x200000ac = 0;
    *(uint8_t*)0x200000ad = 0;
    *(uint8_t*)0x200000ae = 0;
    *(uint8_t*)0x200000af = 0;
    *(uint8_t*)0x200000b0 = 0;
    *(uint8_t*)0x200000b1 = 0;
    *(uint8_t*)0x200000b2 = 0;
    *(uint8_t*)0x200000b3 = 0;
    *(uint32_t*)0x200000b4 = 0;
    *(uint16_t*)0x200000b8 = 0x90;
    *(uint16_t*)0x200000ba = 0xc8;
    *(uint32_t*)0x200000bc = 0;
    *(uint64_t*)0x200000c0 = 0;
    *(uint64_t*)0x200000c8 = 0;
    *(uint16_t*)0x200000d0 = 0x20;
    memcpy((void*)0x200000d2, "\x73\x6f\x63\x6b\x65\x74\x00\x00\x00\x00\x00\x00"
                              "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                              "\x00\x00\x00\x00\x00",
           29);
    *(uint8_t*)0x200000ef = 0;
    *(uint16_t*)0x200000f0 = 0x38;
    memcpy((void*)0x200000f2, "\x44\x4e\x41\x54\x00\x00\x00\x00\x00\x00\x00\x00"
                              "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                              "\x00\x00\x00\x00\x00",
           29);
    *(uint8_t*)0x2000010f = 0;
    *(uint32_t*)0x20000110 = 1;
    *(uint32_t*)0x20000114 = 0;
    *(uint32_t*)0x20000118 = htobe32(0);
    *(uint8_t*)0x2000011c = 0xac;
    *(uint8_t*)0x2000011d = 0x14;
    *(uint8_t*)0x2000011e = -1;
    *(uint8_t*)0x2000011f = 0xbb;
    *(uint16_t*)0x20000120 = htobe16(0);
    *(uint16_t*)0x20000122 = htobe16(0);
    *(uint8_t*)0x20000128 = 0;
    *(uint8_t*)0x20000129 = 0;
    *(uint8_t*)0x2000012a = 0;
    *(uint8_t*)0x2000012b = 0;
    *(uint8_t*)0x2000012c = 0;
    *(uint8_t*)0x2000012d = 0;
    *(uint8_t*)0x2000012e = 0;
    *(uint8_t*)0x2000012f = 0;
    *(uint8_t*)0x20000130 = 0;
    *(uint8_t*)0x20000131 = 0;
    *(uint8_t*)0x20000132 = 0;
    *(uint8_t*)0x20000133 = 0;
    *(uint8_t*)0x20000134 = 0;
    *(uint8_t*)0x20000135 = 0;
    *(uint8_t*)0x20000136 = 0;
    *(uint8_t*)0x20000137 = 0;
    *(uint8_t*)0x20000138 = 0;
    *(uint8_t*)0x20000139 = 0;
    *(uint8_t*)0x2000013a = 0;
    *(uint8_t*)0x2000013b = 0;
    *(uint8_t*)0x2000013c = 0;
    *(uint8_t*)0x2000013d = 0;
    *(uint8_t*)0x2000013e = 0;
    *(uint8_t*)0x2000013f = 0;
    *(uint8_t*)0x20000140 = 0;
    *(uint8_t*)0x20000141 = 0;
    *(uint8_t*)0x20000142 = 0;
    *(uint8_t*)0x20000143 = 0;
    *(uint8_t*)0x20000144 = 0;
    *(uint8_t*)0x20000145 = 0;
    *(uint8_t*)0x20000146 = 0;
    *(uint8_t*)0x20000147 = 0;
    *(uint8_t*)0x20000148 = 0;
    *(uint8_t*)0x20000149 = 0;
    *(uint8_t*)0x2000014a = 0;
    *(uint8_t*)0x2000014b = 0;
    *(uint8_t*)0x2000014c = 0;
    *(uint8_t*)0x2000014d = 0;
    *(uint8_t*)0x2000014e = 0;
    *(uint8_t*)0x2000014f = 0;
    *(uint8_t*)0x20000150 = 0;
    *(uint8_t*)0x20000151 = 0;
    *(uint8_t*)0x20000152 = 0;
    *(uint8_t*)0x20000153 = 0;
    *(uint8_t*)0x20000154 = 0;
    *(uint8_t*)0x20000155 = 0;
    *(uint8_t*)0x20000156 = 0;
    *(uint8_t*)0x20000157 = 0;
    *(uint8_t*)0x20000158 = 0;
    *(uint8_t*)0x20000159 = 0;
    *(uint8_t*)0x2000015a = 0;
    *(uint8_t*)0x2000015b = 0;
    *(uint8_t*)0x2000015c = 0;
    *(uint8_t*)0x2000015d = 0;
    *(uint8_t*)0x2000015e = 0;
    *(uint8_t*)0x2000015f = 0;
    *(uint8_t*)0x20000160 = 0;
    *(uint8_t*)0x20000161 = 0;
    *(uint8_t*)0x20000162 = 0;
    *(uint8_t*)0x20000163 = 0;
    *(uint8_t*)0x20000164 = 0;
    *(uint8_t*)0x20000165 = 0;
    *(uint8_t*)0x20000166 = 0;
    *(uint8_t*)0x20000167 = 0;
    *(uint8_t*)0x20000168 = 0;
    *(uint8_t*)0x20000169 = 0;
    *(uint8_t*)0x2000016a = 0;
    *(uint8_t*)0x2000016b = 0;
    *(uint8_t*)0x2000016c = 0;
    *(uint8_t*)0x2000016d = 0;
    *(uint8_t*)0x2000016e = 0;
    *(uint8_t*)0x2000016f = 0;
    *(uint8_t*)0x20000170 = 0;
    *(uint8_t*)0x20000171 = 0;
    *(uint8_t*)0x20000172 = 0;
    *(uint8_t*)0x20000173 = 0;
    *(uint8_t*)0x20000174 = 0;
    *(uint8_t*)0x20000175 = 0;
    *(uint8_t*)0x20000176 = 0;
    *(uint8_t*)0x20000177 = 0;
    *(uint8_t*)0x20000178 = 0;
    *(uint8_t*)0x20000179 = 0;
    *(uint8_t*)0x2000017a = 0;
    *(uint8_t*)0x2000017b = 0;
    *(uint32_t*)0x2000017c = 0;
    *(uint16_t*)0x20000180 = 0x70;
    *(uint16_t*)0x20000182 = 0xa8;
    *(uint32_t*)0x20000184 = 0;
    *(uint64_t*)0x20000188 = 0;
    *(uint64_t*)0x20000190 = 0;
    *(uint16_t*)0x20000198 = 0x38;
    memcpy((void*)0x2000019a, "\x52\x45\x44\x49\x52\x45\x43\x54\x00\x00\x00\x00"
                              "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                              "\x00\x00\x00\x00\x00",
           29);
    *(uint8_t*)0x200001b7 = 0;
    *(uint32_t*)0x200001b8 = 1;
    *(uint32_t*)0x200001bc = 0;
    *(uint8_t*)0x200001c0 = 0xac;
    *(uint8_t*)0x200001c1 = 0x14;
    *(uint8_t*)0x200001c2 = -1;
    *(uint8_t*)0x200001c3 = 0xbb;
    *(uint32_t*)0x200001c4 = htobe32(0xe0000001);
    *(uint16_t*)0x200001c8 = htobe16(0);
    *(uint16_t*)0x200001ca = 0;
    *(uint8_t*)0x200001d0 = 0;
    *(uint8_t*)0x200001d1 = 0;
    *(uint8_t*)0x200001d2 = 0;
    *(uint8_t*)0x200001d3 = 0;
    *(uint8_t*)0x200001d4 = 0;
    *(uint8_t*)0x200001d5 = 0;
    *(uint8_t*)0x200001d6 = 0;
    *(uint8_t*)0x200001d7 = 0;
    *(uint8_t*)0x200001d8 = 0;
    *(uint8_t*)0x200001d9 = 0;
    *(uint8_t*)0x200001da = 0;
    *(uint8_t*)0x200001db = 0;
    *(uint8_t*)0x200001dc = 0;
    *(uint8_t*)0x200001dd = 0;
    *(uint8_t*)0x200001de = 0;
    *(uint8_t*)0x200001df = 0;
    *(uint8_t*)0x200001e0 = 0;
    *(uint8_t*)0x200001e1 = 0;
    *(uint8_t*)0x200001e2 = 0;
    *(uint8_t*)0x200001e3 = 0;
    *(uint8_t*)0x200001e4 = 0;
    *(uint8_t*)0x200001e5 = 0;
    *(uint8_t*)0x200001e6 = 0;
    *(uint8_t*)0x200001e7 = 0;
    *(uint8_t*)0x200001e8 = 0;
    *(uint8_t*)0x200001e9 = 0;
    *(uint8_t*)0x200001ea = 0;
    *(uint8_t*)0x200001eb = 0;
    *(uint8_t*)0x200001ec = 0;
    *(uint8_t*)0x200001ed = 0;
    *(uint8_t*)0x200001ee = 0;
    *(uint8_t*)0x200001ef = 0;
    *(uint8_t*)0x200001f0 = 0;
    *(uint8_t*)0x200001f1 = 0;
    *(uint8_t*)0x200001f2 = 0;
    *(uint8_t*)0x200001f3 = 0;
    *(uint8_t*)0x200001f4 = 0;
    *(uint8_t*)0x200001f5 = 0;
    *(uint8_t*)0x200001f6 = 0;
    *(uint8_t*)0x200001f7 = 0;
    *(uint8_t*)0x200001f8 = 0;
    *(uint8_t*)0x200001f9 = 0;
    *(uint8_t*)0x200001fa = 0;
    *(uint8_t*)0x200001fb = 0;
    *(uint8_t*)0x200001fc = 0;
    *(uint8_t*)0x200001fd = 0;
    *(uint8_t*)0x200001fe = 0;
    *(uint8_t*)0x200001ff = 0;
    *(uint8_t*)0x20000200 = 0;
    *(uint8_t*)0x20000201 = 0;
    *(uint8_t*)0x20000202 = 0;
    *(uint8_t*)0x20000203 = 0;
    *(uint8_t*)0x20000204 = 0;
    *(uint8_t*)0x20000205 = 0;
    *(uint8_t*)0x20000206 = 0;
    *(uint8_t*)0x20000207 = 0;
    *(uint8_t*)0x20000208 = 0;
    *(uint8_t*)0x20000209 = 0;
    *(uint8_t*)0x2000020a = 0;
    *(uint8_t*)0x2000020b = 0;
    *(uint8_t*)0x2000020c = 0;
    *(uint8_t*)0x2000020d = 0;
    *(uint8_t*)0x2000020e = 0;
    *(uint8_t*)0x2000020f = 0;
    *(uint8_t*)0x20000210 = 0;
    *(uint8_t*)0x20000211 = 0;
    *(uint8_t*)0x20000212 = 0;
    *(uint8_t*)0x20000213 = 0;
    *(uint8_t*)0x20000214 = 0;
    *(uint8_t*)0x20000215 = 0;
    *(uint8_t*)0x20000216 = 0;
    *(uint8_t*)0x20000217 = 0;
    *(uint8_t*)0x20000218 = 0;
    *(uint8_t*)0x20000219 = 0;
    *(uint8_t*)0x2000021a = 0;
    *(uint8_t*)0x2000021b = 0;
    *(uint8_t*)0x2000021c = 0;
    *(uint8_t*)0x2000021d = 0;
    *(uint8_t*)0x2000021e = 0;
    *(uint8_t*)0x2000021f = 0;
    *(uint8_t*)0x20000220 = 0;
    *(uint8_t*)0x20000221 = 0;
    *(uint8_t*)0x20000222 = 0;
    *(uint8_t*)0x20000223 = 0;
    *(uint32_t*)0x20000224 = 0;
    *(uint16_t*)0x20000228 = 0x70;
    *(uint16_t*)0x2000022a = 0xa8;
    *(uint32_t*)0x2000022c = 0;
    *(uint64_t*)0x20000230 = 0;
    *(uint64_t*)0x20000238 = 0;
    *(uint16_t*)0x20000240 = 0x38;
    memcpy((void*)0x20000242, "\x4e\x45\x54\x4d\x41\x50\x00\x00\x00\x00\x00\x00"
                              "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                              "\x00\x00\x00\x00\x00",
           29);
    *(uint8_t*)0x2000025f = 0;
    *(uint32_t*)0x20000260 = 1;
    *(uint32_t*)0x20000264 = 9;
    *(uint32_t*)0x20000268 = htobe32(0xe0000002);
    *(uint8_t*)0x2000026c = 0xac;
    *(uint8_t*)0x2000026d = 0x14;
    *(uint8_t*)0x2000026e = -1;
    *(uint8_t*)0x2000026f = 0xaa;
    *(uint16_t*)0x20000270 = htobe16(0);
    *(uint16_t*)0x20000272 = htobe16(0);
    *(uint8_t*)0x20000278 = 0;
    *(uint8_t*)0x20000279 = 0;
    *(uint8_t*)0x2000027a = 0;
    *(uint8_t*)0x2000027b = 0;
    *(uint8_t*)0x2000027c = 0;
    *(uint8_t*)0x2000027d = 0;
    *(uint8_t*)0x2000027e = 0;
    *(uint8_t*)0x2000027f = 0;
    *(uint8_t*)0x20000280 = 0;
    *(uint8_t*)0x20000281 = 0;
    *(uint8_t*)0x20000282 = 0;
    *(uint8_t*)0x20000283 = 0;
    *(uint8_t*)0x20000284 = 0;
    *(uint8_t*)0x20000285 = 0;
    *(uint8_t*)0x20000286 = 0;
    *(uint8_t*)0x20000287 = 0;
    *(uint8_t*)0x20000288 = 0;
    *(uint8_t*)0x20000289 = 0;
    *(uint8_t*)0x2000028a = 0;
    *(uint8_t*)0x2000028b = 0;
    *(uint8_t*)0x2000028c = 0;
    *(uint8_t*)0x2000028d = 0;
    *(uint8_t*)0x2000028e = 0;
    *(uint8_t*)0x2000028f = 0;
    *(uint8_t*)0x20000290 = 0;
    *(uint8_t*)0x20000291 = 0;
    *(uint8_t*)0x20000292 = 0;
    *(uint8_t*)0x20000293 = 0;
    *(uint8_t*)0x20000294 = 0;
    *(uint8_t*)0x20000295 = 0;
    *(uint8_t*)0x20000296 = 0;
    *(uint8_t*)0x20000297 = 0;
    *(uint8_t*)0x20000298 = 0;
    *(uint8_t*)0x20000299 = 0;
    *(uint8_t*)0x2000029a = 0;
    *(uint8_t*)0x2000029b = 0;
    *(uint8_t*)0x2000029c = 0;
    *(uint8_t*)0x2000029d = 0;
    *(uint8_t*)0x2000029e = 0;
    *(uint8_t*)0x2000029f = 0;
    *(uint8_t*)0x200002a0 = 0;
    *(uint8_t*)0x200002a1 = 0;
    *(uint8_t*)0x200002a2 = 0;
    *(uint8_t*)0x200002a3 = 0;
    *(uint8_t*)0x200002a4 = 0;
    *(uint8_t*)0x200002a5 = 0;
    *(uint8_t*)0x200002a6 = 0;
    *(uint8_t*)0x200002a7 = 0;
    *(uint8_t*)0x200002a8 = 0;
    *(uint8_t*)0x200002a9 = 0;
    *(uint8_t*)0x200002aa = 0;
    *(uint8_t*)0x200002ab = 0;
    *(uint8_t*)0x200002ac = 0;
    *(uint8_t*)0x200002ad = 0;
    *(uint8_t*)0x200002ae = 0;
    *(uint8_t*)0x200002af = 0;
    *(uint8_t*)0x200002b0 = 0;
    *(uint8_t*)0x200002b1 = 0;
    *(uint8_t*)0x200002b2 = 0;
    *(uint8_t*)0x200002b3 = 0;
    *(uint8_t*)0x200002b4 = 0;
    *(uint8_t*)0x200002b5 = 0;
    *(uint8_t*)0x200002b6 = 0;
    *(uint8_t*)0x200002b7 = 0;
    *(uint8_t*)0x200002b8 = 0;
    *(uint8_t*)0x200002b9 = 0;
    *(uint8_t*)0x200002ba = 0;
    *(uint8_t*)0x200002bb = 0;
    *(uint8_t*)0x200002bc = 0;
    *(uint8_t*)0x200002bd = 0;
    *(uint8_t*)0x200002be = 0;
    *(uint8_t*)0x200002bf = 0;
    *(uint8_t*)0x200002c0 = 0;
    *(uint8_t*)0x200002c1 = 0;
    *(uint8_t*)0x200002c2 = 0;
    *(uint8_t*)0x200002c3 = 0;
    *(uint8_t*)0x200002c4 = 0;
    *(uint8_t*)0x200002c5 = 0;
    *(uint8_t*)0x200002c6 = 0;
    *(uint8_t*)0x200002c7 = 0;
    *(uint8_t*)0x200002c8 = 0;
    *(uint8_t*)0x200002c9 = 0;
    *(uint8_t*)0x200002ca = 0;
    *(uint8_t*)0x200002cb = 0;
    *(uint32_t*)0x200002cc = 0;
    *(uint16_t*)0x200002d0 = 0x70;
    *(uint16_t*)0x200002d2 = 0xa8;
    *(uint32_t*)0x200002d4 = 0;
    *(uint64_t*)0x200002d8 = 0;
    *(uint64_t*)0x200002e0 = 0;
    *(uint16_t*)0x200002e8 = 0x38;
    memcpy((void*)0x200002ea, "\x4e\x45\x54\x4d\x41\x50\x00\x00\x00\x00\x00\x00"
                              "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                              "\x00\x00\x00\x00\x00",
           29);
    *(uint8_t*)0x20000307 = 0;
    *(uint32_t*)0x20000308 = 1;
    *(uint32_t*)0x2000030c = 5;
    *(uint8_t*)0x20000310 = 0xac;
    *(uint8_t*)0x20000311 = 0x14;
    *(uint8_t*)0x20000312 = -1;
    *(uint8_t*)0x20000313 = 0xaa;
    *(uint8_t*)0x20000314 = 0xac;
    *(uint8_t*)0x20000315 = 0x14;
    *(uint8_t*)0x20000316 = 0;
    *(uint8_t*)0x20000317 = 0;
    *(uint16_t*)0x20000318 = htobe16(0);
    *(uint16_t*)0x2000031a = 0;
    *(uint8_t*)0x20000320 = 0;
    *(uint8_t*)0x20000321 = 0;
    *(uint8_t*)0x20000322 = 0;
    *(uint8_t*)0x20000323 = 0;
    *(uint8_t*)0x20000324 = 0;
    *(uint8_t*)0x20000325 = 0;
    *(uint8_t*)0x20000326 = 0;
    *(uint8_t*)0x20000327 = 0;
    *(uint8_t*)0x20000328 = 0;
    *(uint8_t*)0x20000329 = 0;
    *(uint8_t*)0x2000032a = 0;
    *(uint8_t*)0x2000032b = 0;
    *(uint8_t*)0x2000032c = 0;
    *(uint8_t*)0x2000032d = 0;
    *(uint8_t*)0x2000032e = 0;
    *(uint8_t*)0x2000032f = 0;
    *(uint8_t*)0x20000330 = 0;
    *(uint8_t*)0x20000331 = 0;
    *(uint8_t*)0x20000332 = 0;
    *(uint8_t*)0x20000333 = 0;
    *(uint8_t*)0x20000334 = 0;
    *(uint8_t*)0x20000335 = 0;
    *(uint8_t*)0x20000336 = 0;
    *(uint8_t*)0x20000337 = 0;
    *(uint8_t*)0x20000338 = 0;
    *(uint8_t*)0x20000339 = 0;
    *(uint8_t*)0x2000033a = 0;
    *(uint8_t*)0x2000033b = 0;
    *(uint8_t*)0x2000033c = 0;
    *(uint8_t*)0x2000033d = 0;
    *(uint8_t*)0x2000033e = 0;
    *(uint8_t*)0x2000033f = 0;
    *(uint8_t*)0x20000340 = 0;
    *(uint8_t*)0x20000341 = 0;
    *(uint8_t*)0x20000342 = 0;
    *(uint8_t*)0x20000343 = 0;
    *(uint8_t*)0x20000344 = 0;
    *(uint8_t*)0x20000345 = 0;
    *(uint8_t*)0x20000346 = 0;
    *(uint8_t*)0x20000347 = 0;
    *(uint8_t*)0x20000348 = 0;
    *(uint8_t*)0x20000349 = 0;
    *(uint8_t*)0x2000034a = 0;
    *(uint8_t*)0x2000034b = 0;
    *(uint8_t*)0x2000034c = 0;
    *(uint8_t*)0x2000034d = 0;
    *(uint8_t*)0x2000034e = 0;
    *(uint8_t*)0x2000034f = 0;
    *(uint8_t*)0x20000350 = 0;
    *(uint8_t*)0x20000351 = 0;
    *(uint8_t*)0x20000352 = 0;
    *(uint8_t*)0x20000353 = 0;
    *(uint8_t*)0x20000354 = 0;
    *(uint8_t*)0x20000355 = 0;
    *(uint8_t*)0x20000356 = 0;
    *(uint8_t*)0x20000357 = 0;
    *(uint8_t*)0x20000358 = 0;
    *(uint8_t*)0x20000359 = 0;
    *(uint8_t*)0x2000035a = 0;
    *(uint8_t*)0x2000035b = 0;
    *(uint8_t*)0x2000035c = 0;
    *(uint8_t*)0x2000035d = 0;
    *(uint8_t*)0x2000035e = 0;
    *(uint8_t*)0x2000035f = 0;
    *(uint8_t*)0x20000360 = 0;
    *(uint8_t*)0x20000361 = 0;
    *(uint8_t*)0x20000362 = 0;
    *(uint8_t*)0x20000363 = 0;
    *(uint8_t*)0x20000364 = 0;
    *(uint8_t*)0x20000365 = 0;
    *(uint8_t*)0x20000366 = 0;
    *(uint8_t*)0x20000367 = 0;
    *(uint8_t*)0x20000368 = 0;
    *(uint8_t*)0x20000369 = 0;
    *(uint8_t*)0x2000036a = 0;
    *(uint8_t*)0x2000036b = 0;
    *(uint8_t*)0x2000036c = 0;
    *(uint8_t*)0x2000036d = 0;
    *(uint8_t*)0x2000036e = 0;
    *(uint8_t*)0x2000036f = 0;
    *(uint8_t*)0x20000370 = 0;
    *(uint8_t*)0x20000371 = 0;
    *(uint8_t*)0x20000372 = 0;
    *(uint8_t*)0x20000373 = 0;
    *(uint32_t*)0x20000374 = 0;
    *(uint16_t*)0x20000378 = 0x70;
    *(uint16_t*)0x2000037a = 0x98;
    *(uint32_t*)0x2000037c = 0;
    *(uint64_t*)0x20000380 = 0;
    *(uint64_t*)0x20000388 = 0;
    *(uint16_t*)0x20000390 = 0x28;
    memcpy((void*)0x20000392, "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                              "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                              "\x00\x00\x00\x00\x00",
           29);
    *(uint8_t*)0x200003af = 0;
    *(uint32_t*)0x200003b0 = 0xfffffffe;
    syscall(__NR_setsockopt, r[0], 0, 0x40, 0x20000000, 0x3b8);
    break;
  case 3:
    *(uint8_t*)0x20007000 = 0xaa;
    *(uint8_t*)0x20007001 = 0xaa;
    *(uint8_t*)0x20007002 = 0xaa;
    *(uint8_t*)0x20007003 = 0xaa;
    *(uint8_t*)0x20007004 = 0xaa;
    *(uint8_t*)0x20007005 = 0xaa;
    memcpy((void*)0x20007006, "\xcf\x2b\xb4\x3c\x40\xb8", 6);
    *(uint16_t*)0x2000700c = htobe16(0x800);
    STORE_BY_BITMASK(uint8_t, 0x2000700e, 5, 0, 4);
    STORE_BY_BITMASK(uint8_t, 0x2000700e, 4, 4, 4);
    STORE_BY_BITMASK(uint8_t, 0x2000700f, 0, 0, 2);
    STORE_BY_BITMASK(uint8_t, 0x2000700f, 0, 2, 6);
    *(uint16_t*)0x20007010 = htobe16(0x28);
    *(uint16_t*)0x20007012 = htobe16(0);
    *(uint16_t*)0x20007014 = htobe16(0);
    *(uint8_t*)0x20007016 = 0;
    *(uint8_t*)0x20007017 = 6;
    *(uint16_t*)0x20007018 = 0;
    *(uint8_t*)0x2000701a = 0xac;
    *(uint8_t*)0x2000701b = 0x23;
    *(uint8_t*)0x2000701c = -1;
    *(uint8_t*)0x2000701d = 0xaa;
    *(uint32_t*)0x2000701e = htobe32(0xe0000001);
    *(uint16_t*)0x20007022 = htobe16(0x4e20);
    *(uint16_t*)0x20007024 = htobe16(0x4e20);
    *(uint32_t*)0x20007026 = 0x42424242;
    *(uint32_t*)0x2000702a = 0x42424242;
    STORE_BY_BITMASK(uint8_t, 0x2000702e, 0, 0, 1);
    STORE_BY_BITMASK(uint8_t, 0x2000702e, 0, 1, 3);
    STORE_BY_BITMASK(uint8_t, 0x2000702e, 5, 4, 4);
    *(uint8_t*)0x2000702f = 0x22;
    *(uint16_t*)0x20007030 = htobe16(0);
    *(uint16_t*)0x20007032 = 0;
    *(uint16_t*)0x20007034 = htobe16(0);
    struct csum_inet csum_1;
    csum_inet_init(&csum_1);
    csum_inet_update(&csum_1, (const uint8_t*)0x2000701a, 4);
    csum_inet_update(&csum_1, (const uint8_t*)0x2000701e, 4);
    uint16_t csum_1_chunk_2 = 0x600;
    csum_inet_update(&csum_1, (const uint8_t*)&csum_1_chunk_2, 2);
    uint16_t csum_1_chunk_3 = 0x1400;
    csum_inet_update(&csum_1, (const uint8_t*)&csum_1_chunk_3, 2);
    csum_inet_update(&csum_1, (const uint8_t*)0x20007022, 20);
    *(uint16_t*)0x20007032 = csum_inet_digest(&csum_1);
    struct csum_inet csum_2;
    csum_inet_init(&csum_2);
    csum_inet_update(&csum_2, (const uint8_t*)0x2000700e, 20);
    *(uint16_t*)0x20007018 = csum_inet_digest(&csum_2);
    syz_emit_ethernet(0x230, 0x20007000, 0);
    break;
  case 4:
    res = syscall(__NR_socket, 2, 1, 0);
    if (res != -1)
      r[1] = res;
    break;
  case 5:
    *(uint16_t*)0x20000140 = 2;
    *(uint16_t*)0x20000142 = htobe16(0x4e20);
    *(uint32_t*)0x20000144 = htobe32(0xe0000001);
    *(uint8_t*)0x20000148 = 0;
    *(uint8_t*)0x20000149 = 0;
    *(uint8_t*)0x2000014a = 0;
    *(uint8_t*)0x2000014b = 0;
    *(uint8_t*)0x2000014c = 0;
    *(uint8_t*)0x2000014d = 0;
    *(uint8_t*)0x2000014e = 0;
    *(uint8_t*)0x2000014f = 0;
    syscall(__NR_bind, r[1], 0x20000140, 0x10);
    break;
  case 6:
    *(uint16_t*)0x20000100 = 2;
    *(uint16_t*)0x20000102 = htobe16(0x4e20);
    *(uint8_t*)0x20000104 = 0xac;
    *(uint8_t*)0x20000105 = 0x14;
    *(uint8_t*)0x20000106 = 0x14;
    *(uint8_t*)0x20000107 = 0xb;
    *(uint8_t*)0x20000108 = 0;
    *(uint8_t*)0x20000109 = 0;
    *(uint8_t*)0x2000010a = 0;
    *(uint8_t*)0x2000010b = 0;
    *(uint8_t*)0x2000010c = 0;
    *(uint8_t*)0x2000010d = 0;
    *(uint8_t*)0x2000010e = 0;
    *(uint8_t*)0x2000010f = 0;
    syscall(__NR_connect, r[1], 0x20000100, 0x10);
    break;
  case 7:
    memcpy((void*)0x20000040,
           "\x74\x75\x6e\x6c\x30\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
           16);
    syscall(__NR_setsockopt, r[1], 1, 0x19, 0x20000040, 0xc);
    break;
  }
}

void test()
{
  execute(8);
}

int main()
{
  syscall(__NR_mmap, 0x20000000, 0x1000000, 3, 0x32, -1, 0);
  for (procid = 0; procid < 8; procid++) {
    if (fork() == 0) {
      for (;;) {
        int pid = do_sandbox_none();
        int status = 0;
        while (waitpid(pid, &status, __WALL) != pid) {
        }
      }
    }
  }
  sleep(1000000);
  return 0;
}
