// general protection fault in SyS_bpf (2)
// https://syzkaller.appspot.com/bug?id=93893565471a04d11b547330072c0ee7babe0aaf
// status:fixed
// autogenerated by syzkaller (http://github.com/google/syzkaller)

#define _GNU_SOURCE
#include <endian.h>
#include <stdint.h>
#include <string.h>
#include <sys/syscall.h>
#include <unistd.h>

#ifndef __NR_bpf
#define __NR_bpf 321
#endif

void loop()
{
  syscall(__NR_mmap, 0x20000000, 0xeff000, 3, 0x32, -1, 0);
  *(uint32_t*)0x20efafd4 = 0xf;
  *(uint32_t*)0x20efafd8 = 4;
  *(uint32_t*)0x20efafdc = 4;
  *(uint32_t*)0x20efafe0 = -1;
  *(uint32_t*)0x20efafe4 = 0;
  *(uint32_t*)0x20efafe8 = -1;
  *(uint32_t*)0x20efafec = 0;
  *(uint8_t*)0x20efaff0 = 0;
  *(uint8_t*)0x20efaff1 = 0;
  *(uint8_t*)0x20efaff2 = 0;
  *(uint8_t*)0x20efaff3 = 0;
  *(uint8_t*)0x20efaff4 = 0;
  *(uint8_t*)0x20efaff5 = 0;
  *(uint8_t*)0x20efaff6 = 0;
  *(uint8_t*)0x20efaff7 = 0;
  *(uint8_t*)0x20efaff8 = 0;
  *(uint8_t*)0x20efaff9 = 0;
  *(uint8_t*)0x20efaffa = 0;
  *(uint8_t*)0x20efaffb = 0;
  *(uint8_t*)0x20efaffc = 0;
  *(uint8_t*)0x20efaffd = 0;
  *(uint8_t*)0x20efaffe = 0;
  *(uint8_t*)0x20efafff = 0;
  syscall(__NR_bpf, 0, 0x20efafd4, 0x2c);
}

int main()
{
  loop();
  return 0;
}
