// KASAN: use-after-free Read in kernfs_add_one
// https://syzkaller.appspot.com/bug?id=ef17b5b364116518fd65
// status:0
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <dirent.h>
#include <endian.h>
#include <errno.h>
#include <fcntl.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mount.h>
#include <sys/prctl.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

#include <linux/usb/ch9.h>

static unsigned long long procid;

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

static uint64_t current_time_ms(void)
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

static bool write_file(const char* file, const char* what, ...)
{
  char buf[1024];
  va_list args;
  va_start(args, what);
  vsnprintf(buf, sizeof(buf), what, args);
  va_end(args);
  buf[sizeof(buf) - 1] = 0;
  int len = strlen(buf);
  int fd = open(file, O_WRONLY | O_CLOEXEC);
  if (fd == -1)
    return false;
  if (write(fd, buf, len) != len) {
    int err = errno;
    close(fd);
    errno = err;
    return false;
  }
  close(fd);
  return true;
}

#define MAX_FDS 30

#define USB_MAX_IFACE_NUM 4
#define USB_MAX_EP_NUM 32
#define USB_MAX_FDS 6

struct usb_endpoint_index {
  struct usb_endpoint_descriptor desc;
  int handle;
};

struct usb_iface_index {
  struct usb_interface_descriptor* iface;
  uint8_t bInterfaceNumber;
  uint8_t bAlternateSetting;
  uint8_t bInterfaceClass;
  struct usb_endpoint_index eps[USB_MAX_EP_NUM];
  int eps_num;
};

struct usb_device_index {
  struct usb_device_descriptor* dev;
  struct usb_config_descriptor* config;
  uint8_t bDeviceClass;
  uint8_t bMaxPower;
  int config_length;
  struct usb_iface_index ifaces[USB_MAX_IFACE_NUM];
  int ifaces_num;
  int iface_cur;
};

struct usb_info {
  int fd;
  struct usb_device_index index;
};

static struct usb_info usb_devices[USB_MAX_FDS];
static int usb_devices_num;

static bool parse_usb_descriptor(const char* buffer, size_t length,
                                 struct usb_device_index* index)
{
  if (length < sizeof(*index->dev) + sizeof(*index->config))
    return false;
  memset(index, 0, sizeof(*index));
  index->dev = (struct usb_device_descriptor*)buffer;
  index->config = (struct usb_config_descriptor*)(buffer + sizeof(*index->dev));
  index->bDeviceClass = index->dev->bDeviceClass;
  index->bMaxPower = index->config->bMaxPower;
  index->config_length = length - sizeof(*index->dev);
  index->iface_cur = -1;
  size_t offset = 0;
  while (true) {
    if (offset + 1 >= length)
      break;
    uint8_t desc_length = buffer[offset];
    uint8_t desc_type = buffer[offset + 1];
    if (desc_length <= 2)
      break;
    if (offset + desc_length > length)
      break;
    if (desc_type == USB_DT_INTERFACE &&
        index->ifaces_num < USB_MAX_IFACE_NUM) {
      struct usb_interface_descriptor* iface =
          (struct usb_interface_descriptor*)(buffer + offset);
      index->ifaces[index->ifaces_num].iface = iface;
      index->ifaces[index->ifaces_num].bInterfaceNumber =
          iface->bInterfaceNumber;
      index->ifaces[index->ifaces_num].bAlternateSetting =
          iface->bAlternateSetting;
      index->ifaces[index->ifaces_num].bInterfaceClass = iface->bInterfaceClass;
      index->ifaces_num++;
    }
    if (desc_type == USB_DT_ENDPOINT && index->ifaces_num > 0) {
      struct usb_iface_index* iface = &index->ifaces[index->ifaces_num - 1];
      if (iface->eps_num < USB_MAX_EP_NUM) {
        memcpy(&iface->eps[iface->eps_num].desc, buffer + offset,
               sizeof(iface->eps[iface->eps_num].desc));
        iface->eps_num++;
      }
    }
    offset += desc_length;
  }
  return true;
}

static struct usb_device_index* add_usb_index(int fd, const char* dev,
                                              size_t dev_len)
{
  int i = __atomic_fetch_add(&usb_devices_num, 1, __ATOMIC_RELAXED);
  if (i >= USB_MAX_FDS)
    return NULL;
  if (!parse_usb_descriptor(dev, dev_len, &usb_devices[i].index))
    return NULL;
  __atomic_store_n(&usb_devices[i].fd, fd, __ATOMIC_RELEASE);
  return &usb_devices[i].index;
}

static struct usb_device_index* lookup_usb_index(int fd)
{
  for (int i = 0; i < USB_MAX_FDS; i++) {
    if (__atomic_load_n(&usb_devices[i].fd, __ATOMIC_ACQUIRE) == fd)
      return &usb_devices[i].index;
  }
  return NULL;
}

struct vusb_connect_string_descriptor {
  uint32_t len;
  char* str;
} __attribute__((packed));

struct vusb_connect_descriptors {
  uint32_t qual_len;
  char* qual;
  uint32_t bos_len;
  char* bos;
  uint32_t strs_len;
  struct vusb_connect_string_descriptor strs[0];
} __attribute__((packed));

static const char default_string[] = {8, USB_DT_STRING, 's', 0, 'y', 0, 'z', 0};

static const char default_lang_id[] = {4, USB_DT_STRING, 0x09, 0x04};

static bool
lookup_connect_response_in(int fd, const struct vusb_connect_descriptors* descs,
                           const struct usb_ctrlrequest* ctrl,
                           char** response_data, uint32_t* response_length)
{
  struct usb_device_index* index = lookup_usb_index(fd);
  uint8_t str_idx;
  if (!index)
    return false;
  switch (ctrl->bRequestType & USB_TYPE_MASK) {
  case USB_TYPE_STANDARD:
    switch (ctrl->bRequest) {
    case USB_REQ_GET_DESCRIPTOR:
      switch (ctrl->wValue >> 8) {
      case USB_DT_DEVICE:
        *response_data = (char*)index->dev;
        *response_length = sizeof(*index->dev);
        return true;
      case USB_DT_CONFIG:
        *response_data = (char*)index->config;
        *response_length = index->config_length;
        return true;
      case USB_DT_STRING:
        str_idx = (uint8_t)ctrl->wValue;
        if (descs && str_idx < descs->strs_len) {
          *response_data = descs->strs[str_idx].str;
          *response_length = descs->strs[str_idx].len;
          return true;
        }
        if (str_idx == 0) {
          *response_data = (char*)&default_lang_id[0];
          *response_length = default_lang_id[0];
          return true;
        }
        *response_data = (char*)&default_string[0];
        *response_length = default_string[0];
        return true;
      case USB_DT_BOS:
        *response_data = descs->bos;
        *response_length = descs->bos_len;
        return true;
      case USB_DT_DEVICE_QUALIFIER:
        if (!descs->qual) {
          struct usb_qualifier_descriptor* qual =
              (struct usb_qualifier_descriptor*)response_data;
          qual->bLength = sizeof(*qual);
          qual->bDescriptorType = USB_DT_DEVICE_QUALIFIER;
          qual->bcdUSB = index->dev->bcdUSB;
          qual->bDeviceClass = index->dev->bDeviceClass;
          qual->bDeviceSubClass = index->dev->bDeviceSubClass;
          qual->bDeviceProtocol = index->dev->bDeviceProtocol;
          qual->bMaxPacketSize0 = index->dev->bMaxPacketSize0;
          qual->bNumConfigurations = index->dev->bNumConfigurations;
          qual->bRESERVED = 0;
          *response_length = sizeof(*qual);
          return true;
        }
        *response_data = descs->qual;
        *response_length = descs->qual_len;
        return true;
      default:
        break;
      }
      break;
    default:
      break;
    }
    break;
  default:
    break;
  }
  return false;
}

typedef bool (*lookup_connect_out_response_t)(
    int fd, const struct vusb_connect_descriptors* descs,
    const struct usb_ctrlrequest* ctrl, bool* done);

static bool lookup_connect_response_out_generic(
    int fd, const struct vusb_connect_descriptors* descs,
    const struct usb_ctrlrequest* ctrl, bool* done)
{
  switch (ctrl->bRequestType & USB_TYPE_MASK) {
  case USB_TYPE_STANDARD:
    switch (ctrl->bRequest) {
    case USB_REQ_SET_CONFIGURATION:
      *done = true;
      return true;
    default:
      break;
    }
    break;
  }
  return false;
}

#define UDC_NAME_LENGTH_MAX 128

struct usb_raw_init {
  __u8 driver_name[UDC_NAME_LENGTH_MAX];
  __u8 device_name[UDC_NAME_LENGTH_MAX];
  __u8 speed;
};

enum usb_raw_event_type {
  USB_RAW_EVENT_INVALID = 0,
  USB_RAW_EVENT_CONNECT = 1,
  USB_RAW_EVENT_CONTROL = 2,
};

struct usb_raw_event {
  __u32 type;
  __u32 length;
  __u8 data[0];
};

struct usb_raw_ep_io {
  __u16 ep;
  __u16 flags;
  __u32 length;
  __u8 data[0];
};

#define USB_RAW_EPS_NUM_MAX 30
#define USB_RAW_EP_NAME_MAX 16
#define USB_RAW_EP_ADDR_ANY 0xff

struct usb_raw_ep_caps {
  __u32 type_control : 1;
  __u32 type_iso : 1;
  __u32 type_bulk : 1;
  __u32 type_int : 1;
  __u32 dir_in : 1;
  __u32 dir_out : 1;
};

struct usb_raw_ep_limits {
  __u16 maxpacket_limit;
  __u16 max_streams;
  __u32 reserved;
};

struct usb_raw_ep_info {
  __u8 name[USB_RAW_EP_NAME_MAX];
  __u32 addr;
  struct usb_raw_ep_caps caps;
  struct usb_raw_ep_limits limits;
};

struct usb_raw_eps_info {
  struct usb_raw_ep_info eps[USB_RAW_EPS_NUM_MAX];
};

#define USB_RAW_IOCTL_INIT _IOW('U', 0, struct usb_raw_init)
#define USB_RAW_IOCTL_RUN _IO('U', 1)
#define USB_RAW_IOCTL_EVENT_FETCH _IOR('U', 2, struct usb_raw_event)
#define USB_RAW_IOCTL_EP0_WRITE _IOW('U', 3, struct usb_raw_ep_io)
#define USB_RAW_IOCTL_EP0_READ _IOWR('U', 4, struct usb_raw_ep_io)
#define USB_RAW_IOCTL_EP_ENABLE _IOW('U', 5, struct usb_endpoint_descriptor)
#define USB_RAW_IOCTL_EP_DISABLE _IOW('U', 6, __u32)
#define USB_RAW_IOCTL_EP_WRITE _IOW('U', 7, struct usb_raw_ep_io)
#define USB_RAW_IOCTL_EP_READ _IOWR('U', 8, struct usb_raw_ep_io)
#define USB_RAW_IOCTL_CONFIGURE _IO('U', 9)
#define USB_RAW_IOCTL_VBUS_DRAW _IOW('U', 10, __u32)
#define USB_RAW_IOCTL_EPS_INFO _IOR('U', 11, struct usb_raw_eps_info)
#define USB_RAW_IOCTL_EP0_STALL _IO('U', 12)
#define USB_RAW_IOCTL_EP_SET_HALT _IOW('U', 13, __u32)
#define USB_RAW_IOCTL_EP_CLEAR_HALT _IOW('U', 14, __u32)
#define USB_RAW_IOCTL_EP_SET_WEDGE _IOW('U', 15, __u32)

static int usb_raw_open()
{
  return open("/dev/raw-gadget", O_RDWR);
}

static int usb_raw_init(int fd, uint32_t speed, const char* driver,
                        const char* device)
{
  struct usb_raw_init arg;
  strncpy((char*)&arg.driver_name[0], driver, sizeof(arg.driver_name));
  strncpy((char*)&arg.device_name[0], device, sizeof(arg.device_name));
  arg.speed = speed;
  return ioctl(fd, USB_RAW_IOCTL_INIT, &arg);
}

static int usb_raw_run(int fd)
{
  return ioctl(fd, USB_RAW_IOCTL_RUN, 0);
}

static int usb_raw_event_fetch(int fd, struct usb_raw_event* event)
{
  return ioctl(fd, USB_RAW_IOCTL_EVENT_FETCH, event);
}

static int usb_raw_ep0_write(int fd, struct usb_raw_ep_io* io)
{
  return ioctl(fd, USB_RAW_IOCTL_EP0_WRITE, io);
}

static int usb_raw_ep0_read(int fd, struct usb_raw_ep_io* io)
{
  return ioctl(fd, USB_RAW_IOCTL_EP0_READ, io);
}

static int usb_raw_ep_enable(int fd, struct usb_endpoint_descriptor* desc)
{
  return ioctl(fd, USB_RAW_IOCTL_EP_ENABLE, desc);
}

static int usb_raw_ep_disable(int fd, int ep)
{
  return ioctl(fd, USB_RAW_IOCTL_EP_DISABLE, ep);
}

static int usb_raw_configure(int fd)
{
  return ioctl(fd, USB_RAW_IOCTL_CONFIGURE, 0);
}

static int usb_raw_vbus_draw(int fd, uint32_t power)
{
  return ioctl(fd, USB_RAW_IOCTL_VBUS_DRAW, power);
}

static int usb_raw_ep0_stall(int fd)
{
  return ioctl(fd, USB_RAW_IOCTL_EP0_STALL, 0);
}

static void set_interface(int fd, int n)
{
  struct usb_device_index* index = lookup_usb_index(fd);
  if (!index)
    return;
  if (index->iface_cur >= 0 && index->iface_cur < index->ifaces_num) {
    for (int ep = 0; ep < index->ifaces[index->iface_cur].eps_num; ep++) {
      int rv = usb_raw_ep_disable(
          fd, index->ifaces[index->iface_cur].eps[ep].handle);
      if (rv < 0) {
      } else {
      }
    }
  }
  if (n >= 0 && n < index->ifaces_num) {
    for (int ep = 0; ep < index->ifaces[n].eps_num; ep++) {
      int rv = usb_raw_ep_enable(fd, &index->ifaces[n].eps[ep].desc);
      if (rv < 0) {
      } else {
        index->ifaces[n].eps[ep].handle = rv;
      }
    }
    index->iface_cur = n;
  }
}

static int configure_device(int fd)
{
  struct usb_device_index* index = lookup_usb_index(fd);
  if (!index)
    return -1;
  int rv = usb_raw_vbus_draw(fd, index->bMaxPower);
  if (rv < 0) {
    return rv;
  }
  rv = usb_raw_configure(fd);
  if (rv < 0) {
    return rv;
  }
  set_interface(fd, 0);
  return 0;
}

#define USB_MAX_PACKET_SIZE 4096

struct usb_raw_control_event {
  struct usb_raw_event inner;
  struct usb_ctrlrequest ctrl;
  char data[USB_MAX_PACKET_SIZE];
};

struct usb_raw_ep_io_data {
  struct usb_raw_ep_io inner;
  char data[USB_MAX_PACKET_SIZE];
};

static volatile long
syz_usb_connect_impl(uint64_t speed, uint64_t dev_len, const char* dev,
                     const struct vusb_connect_descriptors* descs,
                     lookup_connect_out_response_t lookup_connect_response_out)
{
  if (!dev) {
    return -1;
  }
  int fd = usb_raw_open();
  if (fd < 0) {
    return fd;
  }
  if (fd >= MAX_FDS) {
    close(fd);
    return -1;
  }
  struct usb_device_index* index = add_usb_index(fd, dev, dev_len);
  if (!index) {
    return -1;
  }
  char device[32];
  sprintf(&device[0], "dummy_udc.%llu", procid);
  int rv = usb_raw_init(fd, speed, "dummy_udc", &device[0]);
  if (rv < 0) {
    return rv;
  }
  rv = usb_raw_run(fd);
  if (rv < 0) {
    return rv;
  }
  bool done = false;
  while (!done) {
    struct usb_raw_control_event event;
    event.inner.type = 0;
    event.inner.length = sizeof(event.ctrl);
    rv = usb_raw_event_fetch(fd, (struct usb_raw_event*)&event);
    if (rv < 0) {
      return rv;
    }
    if (event.inner.type != USB_RAW_EVENT_CONTROL)
      continue;
    char* response_data = NULL;
    uint32_t response_length = 0;
    if (event.ctrl.bRequestType & USB_DIR_IN) {
      if (!lookup_connect_response_in(fd, descs, &event.ctrl, &response_data,
                                      &response_length)) {
        usb_raw_ep0_stall(fd);
        continue;
      }
    } else {
      if (!lookup_connect_response_out(fd, descs, &event.ctrl, &done)) {
        usb_raw_ep0_stall(fd);
        continue;
      }
      response_data = NULL;
      response_length = event.ctrl.wLength;
    }
    if ((event.ctrl.bRequestType & USB_TYPE_MASK) == USB_TYPE_STANDARD &&
        event.ctrl.bRequest == USB_REQ_SET_CONFIGURATION) {
      rv = configure_device(fd);
      if (rv < 0) {
        return rv;
      }
    }
    struct usb_raw_ep_io_data response;
    response.inner.ep = 0;
    response.inner.flags = 0;
    if (response_length > sizeof(response.data))
      response_length = 0;
    if (event.ctrl.wLength < response_length)
      response_length = event.ctrl.wLength;
    response.inner.length = response_length;
    if (response_data)
      memcpy(&response.data[0], response_data, response_length);
    else
      memset(&response.data[0], 0, response_length);
    if (event.ctrl.bRequestType & USB_DIR_IN) {
      rv = usb_raw_ep0_write(fd, (struct usb_raw_ep_io*)&response);
    } else {
      rv = usb_raw_ep0_read(fd, (struct usb_raw_ep_io*)&response);
    }
    if (rv < 0) {
      return rv;
    }
  }
  sleep_ms(200);
  return fd;
}

static volatile long syz_usb_connect(volatile long a0, volatile long a1,
                                     volatile long a2, volatile long a3)
{
  uint64_t speed = a0;
  uint64_t dev_len = a1;
  const char* dev = (const char*)a2;
  const struct vusb_connect_descriptors* descs =
      (const struct vusb_connect_descriptors*)a3;
  return syz_usb_connect_impl(speed, dev_len, dev, descs,
                              &lookup_connect_response_out_generic);
}

static void kill_and_wait(int pid, int* status)
{
  kill(-pid, SIGKILL);
  kill(pid, SIGKILL);
  for (int i = 0; i < 100; i++) {
    if (waitpid(-1, status, WNOHANG | __WALL) == pid)
      return;
    usleep(1000);
  }
  DIR* dir = opendir("/sys/fs/fuse/connections");
  if (dir) {
    for (;;) {
      struct dirent* ent = readdir(dir);
      if (!ent)
        break;
      if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
        continue;
      char abort[300];
      snprintf(abort, sizeof(abort), "/sys/fs/fuse/connections/%s/abort",
               ent->d_name);
      int fd = open(abort, O_WRONLY);
      if (fd == -1) {
        continue;
      }
      if (write(fd, abort, 1) < 0) {
      }
      close(fd);
    }
    closedir(dir);
  } else {
  }
  while (waitpid(-1, status, __WALL) != pid) {
  }
}

static void setup_test()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  write_file("/proc/self/oom_score_adj", "1000");
}

static void execute_one(void);

#define WAIT_FLAGS __WALL

static void loop(void)
{
  int iter = 0;
  for (;; iter++) {
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      setup_test();
      execute_one();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      sleep_ms(1);
      if (current_time_ms() - start < 5000)
        continue;
      kill_and_wait(pid, &status);
      break;
    }
  }
}

void execute_one(void)
{
  *(uint8_t*)0x20000d00 = 0x12;
  *(uint8_t*)0x20000d01 = 1;
  *(uint16_t*)0x20000d02 = 0;
  *(uint8_t*)0x20000d04 = 0xb9;
  *(uint8_t*)0x20000d05 = 0x54;
  *(uint8_t*)0x20000d06 = 0xc5;
  *(uint8_t*)0x20000d07 = 0x20;
  *(uint16_t*)0x20000d08 = 0x1110;
  *(uint16_t*)0x20000d0a = 0x9022;
  *(uint16_t*)0x20000d0c = 0xcb70;
  *(uint8_t*)0x20000d0e = 1;
  *(uint8_t*)0x20000d0f = 2;
  *(uint8_t*)0x20000d10 = 3;
  *(uint8_t*)0x20000d11 = 1;
  *(uint8_t*)0x20000d12 = 9;
  *(uint8_t*)0x20000d13 = 2;
  *(uint16_t*)0x20000d14 = 0x262;
  *(uint8_t*)0x20000d16 = 4;
  *(uint8_t*)0x20000d17 = 1;
  *(uint8_t*)0x20000d18 = 0;
  *(uint8_t*)0x20000d19 = 0x90;
  *(uint8_t*)0x20000d1a = 2;
  *(uint8_t*)0x20000d1b = 9;
  *(uint8_t*)0x20000d1c = 4;
  *(uint8_t*)0x20000d1d = 0xbd;
  *(uint8_t*)0x20000d1e = 0x8b;
  *(uint8_t*)0x20000d1f = 0xf;
  *(uint8_t*)0x20000d20 = 0xd0;
  *(uint8_t*)0x20000d21 = 0x72;
  *(uint8_t*)0x20000d22 = 0x9b;
  *(uint8_t*)0x20000d23 = 0x81;
  *(uint8_t*)0x20000d24 = 8;
  *(uint8_t*)0x20000d25 = 0x24;
  *(uint8_t*)0x20000d26 = 2;
  *(uint8_t*)0x20000d27 = 1;
  *(uint8_t*)0x20000d28 = 6;
  *(uint8_t*)0x20000d29 = 4;
  *(uint8_t*)0x20000d2a = 0x52;
  *(uint8_t*)0x20000d2b = 7;
  *(uint8_t*)0x20000d2c = 8;
  *(uint8_t*)0x20000d2d = 0x24;
  *(uint8_t*)0x20000d2e = 2;
  *(uint8_t*)0x20000d2f = 1;
  *(uint8_t*)0x20000d30 = 9;
  *(uint8_t*)0x20000d31 = 2;
  *(uint8_t*)0x20000d32 = 2;
  *(uint8_t*)0x20000d33 = 0x7a;
  *(uint8_t*)0x20000d34 = 8;
  *(uint8_t*)0x20000d35 = 0x24;
  *(uint8_t*)0x20000d36 = 2;
  *(uint8_t*)0x20000d37 = 1;
  *(uint8_t*)0x20000d38 = 3;
  *(uint8_t*)0x20000d39 = 4;
  *(uint8_t*)0x20000d3a = 5;
  *(uint8_t*)0x20000d3b = 0x81;
  *(uint8_t*)0x20000d3c = 7;
  *(uint8_t*)0x20000d3d = 0x24;
  *(uint8_t*)0x20000d3e = 1;
  *(uint8_t*)0x20000d3f = -1;
  *(uint8_t*)0x20000d40 = 1;
  *(uint16_t*)0x20000d41 = 3;
  *(uint8_t*)0x20000d43 = 9;
  *(uint8_t*)0x20000d44 = 0x24;
  *(uint8_t*)0x20000d45 = 2;
  *(uint8_t*)0x20000d46 = 2;
  *(uint16_t*)0x20000d47 = 0xe5;
  *(uint16_t*)0x20000d49 = 1;
  *(uint8_t*)0x20000d4b = 4;
  *(uint8_t*)0x20000d4c = 9;
  *(uint8_t*)0x20000d4d = 5;
  *(uint8_t*)0x20000d4e = 4;
  *(uint8_t*)0x20000d4f = 0;
  *(uint16_t*)0x20000d50 = 0x10;
  *(uint8_t*)0x20000d52 = 0x80;
  *(uint8_t*)0x20000d53 = 0xfa;
  *(uint8_t*)0x20000d54 = 8;
  *(uint8_t*)0x20000d55 = 2;
  *(uint8_t*)0x20000d56 = 4;
  *(uint8_t*)0x20000d57 = 9;
  *(uint8_t*)0x20000d58 = 5;
  *(uint8_t*)0x20000d59 = 5;
  *(uint8_t*)0x20000d5a = 0;
  *(uint16_t*)0x20000d5b = 0x40;
  *(uint8_t*)0x20000d5d = 0x8e;
  *(uint8_t*)0x20000d5e = 0x40;
  *(uint8_t*)0x20000d5f = 9;
  *(uint8_t*)0x20000d60 = 7;
  *(uint8_t*)0x20000d61 = 0x25;
  *(uint8_t*)0x20000d62 = 1;
  *(uint8_t*)0x20000d63 = 2;
  *(uint8_t*)0x20000d64 = 0x20;
  *(uint16_t*)0x20000d65 = 0x101;
  *(uint8_t*)0x20000d67 = 2;
  *(uint8_t*)0x20000d68 = 0x22;
  *(uint8_t*)0x20000d69 = 9;
  *(uint8_t*)0x20000d6a = 5;
  *(uint8_t*)0x20000d6b = 1;
  *(uint8_t*)0x20000d6c = 0;
  *(uint16_t*)0x20000d6d = 0x20;
  *(uint8_t*)0x20000d6f = 2;
  *(uint8_t*)0x20000d70 = 0;
  *(uint8_t*)0x20000d71 = 0x84;
  *(uint8_t*)0x20000d72 = 2;
  *(uint8_t*)0x20000d73 = 8;
  *(uint8_t*)0x20000d74 = 9;
  *(uint8_t*)0x20000d75 = 5;
  *(uint8_t*)0x20000d76 = 0;
  *(uint8_t*)0x20000d77 = 0x10;
  *(uint16_t*)0x20000d78 = 0x40;
  *(uint8_t*)0x20000d7a = 1;
  *(uint8_t*)0x20000d7b = 8;
  *(uint8_t*)0x20000d7c = 0x26;
  *(uint8_t*)0x20000d7d = 7;
  *(uint8_t*)0x20000d7e = 0x25;
  *(uint8_t*)0x20000d7f = 1;
  *(uint8_t*)0x20000d80 = 0x81;
  *(uint8_t*)0x20000d81 = 6;
  *(uint16_t*)0x20000d82 = 0xfff7;
  *(uint8_t*)0x20000d84 = 9;
  *(uint8_t*)0x20000d85 = 5;
  *(uint8_t*)0x20000d86 = 7;
  *(uint8_t*)0x20000d87 = 4;
  *(uint16_t*)0x20000d88 = 0x200;
  *(uint8_t*)0x20000d8a = 8;
  *(uint8_t*)0x20000d8b = 2;
  *(uint8_t*)0x20000d8c = 8;
  *(uint8_t*)0x20000d8d = 2;
  *(uint8_t*)0x20000d8e = 0x10;
  *(uint8_t*)0x20000d8f = 9;
  *(uint8_t*)0x20000d90 = 5;
  *(uint8_t*)0x20000d91 = 9;
  *(uint8_t*)0x20000d92 = 0;
  *(uint16_t*)0x20000d93 = 0x40;
  *(uint8_t*)0x20000d95 = 7;
  *(uint8_t*)0x20000d96 = 0;
  *(uint8_t*)0x20000d97 = 5;
  *(uint8_t*)0x20000d98 = 7;
  *(uint8_t*)0x20000d99 = 0x25;
  *(uint8_t*)0x20000d9a = 1;
  *(uint8_t*)0x20000d9b = 1;
  *(uint8_t*)0x20000d9c = 0x80;
  *(uint16_t*)0x20000d9d = 2;
  *(uint8_t*)0x20000d9f = 9;
  *(uint8_t*)0x20000da0 = 5;
  *(uint8_t*)0x20000da1 = 0xf;
  *(uint8_t*)0x20000da2 = 2;
  *(uint16_t*)0x20000da3 = 0x200;
  *(uint8_t*)0x20000da5 = 6;
  *(uint8_t*)0x20000da6 = 0xf8;
  *(uint8_t*)0x20000da7 = 0x20;
  *(uint8_t*)0x20000da8 = 7;
  *(uint8_t*)0x20000da9 = 0x25;
  *(uint8_t*)0x20000daa = 1;
  *(uint8_t*)0x20000dab = 0x81;
  *(uint8_t*)0x20000dac = 0x3f;
  *(uint16_t*)0x20000dad = 9;
  *(uint8_t*)0x20000daf = 7;
  *(uint8_t*)0x20000db0 = 0x25;
  *(uint8_t*)0x20000db1 = 1;
  *(uint8_t*)0x20000db2 = 2;
  *(uint8_t*)0x20000db3 = 6;
  *(uint16_t*)0x20000db4 = 1;
  *(uint8_t*)0x20000db6 = 9;
  *(uint8_t*)0x20000db7 = 5;
  *(uint8_t*)0x20000db8 = 0x80;
  *(uint8_t*)0x20000db9 = 0x12;
  *(uint16_t*)0x20000dba = 0xb4b0;
  *(uint8_t*)0x20000dbc = 9;
  *(uint8_t*)0x20000dbd = 1;
  *(uint8_t*)0x20000dbe = 0xb0;
  *(uint8_t*)0x20000dbf = 7;
  *(uint8_t*)0x20000dc0 = 0x25;
  *(uint8_t*)0x20000dc1 = 1;
  *(uint8_t*)0x20000dc2 = 0x82;
  *(uint8_t*)0x20000dc3 = 0x7f;
  *(uint16_t*)0x20000dc4 = 2;
  *(uint8_t*)0x20000dc6 = 7;
  *(uint8_t*)0x20000dc7 = 0x25;
  *(uint8_t*)0x20000dc8 = 1;
  *(uint8_t*)0x20000dc9 = 0;
  *(uint8_t*)0x20000dca = 9;
  *(uint16_t*)0x20000dcb = 4;
  *(uint8_t*)0x20000dcd = 9;
  *(uint8_t*)0x20000dce = 5;
  *(uint8_t*)0x20000dcf = 9;
  *(uint8_t*)0x20000dd0 = 0;
  *(uint16_t*)0x20000dd1 = 0x200;
  *(uint8_t*)0x20000dd3 = 0x20;
  *(uint8_t*)0x20000dd4 = 6;
  *(uint8_t*)0x20000dd5 = 0xc1;
  *(uint8_t*)0x20000dd6 = 2;
  *(uint8_t*)0x20000dd7 = 0x30;
  *(uint8_t*)0x20000dd8 = 9;
  *(uint8_t*)0x20000dd9 = 5;
  *(uint8_t*)0x20000dda = 9;
  *(uint8_t*)0x20000ddb = 0xc;
  *(uint16_t*)0x20000ddc = 0x20;
  *(uint8_t*)0x20000dde = 3;
  *(uint8_t*)0x20000ddf = 0xc1;
  *(uint8_t*)0x20000de0 = 4;
  *(uint8_t*)0x20000de1 = 7;
  *(uint8_t*)0x20000de2 = 0x25;
  *(uint8_t*)0x20000de3 = 1;
  *(uint8_t*)0x20000de4 = 0x83;
  *(uint8_t*)0x20000de5 = 3;
  *(uint16_t*)0x20000de6 = 0x3ff;
  *(uint8_t*)0x20000de8 = 2;
  *(uint8_t*)0x20000de9 = 1;
  *(uint8_t*)0x20000dea = 9;
  *(uint8_t*)0x20000deb = 5;
  *(uint8_t*)0x20000dec = 8;
  *(uint8_t*)0x20000ded = 2;
  *(uint16_t*)0x20000dee = 0x40;
  *(uint8_t*)0x20000df0 = 0x11;
  *(uint8_t*)0x20000df1 = 0;
  *(uint8_t*)0x20000df2 = 0x7d;
  *(uint8_t*)0x20000df3 = 7;
  *(uint8_t*)0x20000df4 = 0x25;
  *(uint8_t*)0x20000df5 = 1;
  *(uint8_t*)0x20000df6 = 2;
  *(uint8_t*)0x20000df7 = 0x3f;
  *(uint16_t*)0x20000df8 = 0x8001;
  *(uint8_t*)0x20000dfa = 2;
  *(uint8_t*)0x20000dfb = 5;
  *(uint8_t*)0x20000dfc = 9;
  *(uint8_t*)0x20000dfd = 5;
  *(uint8_t*)0x20000dfe = 8;
  *(uint8_t*)0x20000dff = 1;
  *(uint16_t*)0x20000e00 = 0x7af;
  *(uint8_t*)0x20000e02 = -1;
  *(uint8_t*)0x20000e03 = 9;
  *(uint8_t*)0x20000e04 = 9;
  *(uint8_t*)0x20000e05 = 9;
  *(uint8_t*)0x20000e06 = 5;
  *(uint8_t*)0x20000e07 = 0;
  *(uint8_t*)0x20000e08 = 0;
  *(uint16_t*)0x20000e09 = 0x20;
  *(uint8_t*)0x20000e0b = 9;
  *(uint8_t*)0x20000e0c = 0x1f;
  *(uint8_t*)0x20000e0d = 0x7f;
  *(uint8_t*)0x20000e0e = 9;
  *(uint8_t*)0x20000e0f = 5;
  *(uint8_t*)0x20000e10 = 7;
  *(uint8_t*)0x20000e11 = 0x10;
  *(uint16_t*)0x20000e12 = 0x400;
  *(uint8_t*)0x20000e14 = 1;
  *(uint8_t*)0x20000e15 = 7;
  *(uint8_t*)0x20000e16 = 0x4d;
  *(uint8_t*)0x20000e17 = 9;
  *(uint8_t*)0x20000e18 = 5;
  *(uint8_t*)0x20000e19 = 3;
  *(uint8_t*)0x20000e1a = 0x10;
  *(uint16_t*)0x20000e1b = 0x3ff;
  *(uint8_t*)0x20000e1d = 0xfd;
  *(uint8_t*)0x20000e1e = 6;
  *(uint8_t*)0x20000e1f = 0x81;
  *(uint8_t*)0x20000e20 = 9;
  *(uint8_t*)0x20000e21 = 4;
  *(uint8_t*)0x20000e22 = 0xaf;
  *(uint8_t*)0x20000e23 = 4;
  *(uint8_t*)0x20000e24 = 1;
  *(uint8_t*)0x20000e25 = 0xe6;
  *(uint8_t*)0x20000e26 = 0x43;
  *(uint8_t*)0x20000e27 = 0xd3;
  *(uint8_t*)0x20000e28 = 3;
  *(uint8_t*)0x20000e29 = 0xa;
  *(uint8_t*)0x20000e2a = 0x24;
  *(uint8_t*)0x20000e2b = 1;
  *(uint16_t*)0x20000e2c = 5;
  *(uint8_t*)0x20000e2e = 0x3f;
  *(uint8_t*)0x20000e2f = 2;
  *(uint8_t*)0x20000e30 = 1;
  *(uint8_t*)0x20000e31 = 2;
  *(uint8_t*)0x20000e32 = 9;
  *(uint8_t*)0x20000e33 = 0x24;
  *(uint8_t*)0x20000e34 = 3;
  *(uint8_t*)0x20000e35 = 4;
  *(uint16_t*)0x20000e36 = 0x301;
  *(uint8_t*)0x20000e38 = 5;
  *(uint8_t*)0x20000e39 = 3;
  *(uint8_t*)0x20000e3a = 0xf8;
  *(uint8_t*)0x20000e3b = 5;
  *(uint8_t*)0x20000e3c = 0x24;
  *(uint8_t*)0x20000e3d = 5;
  *(uint8_t*)0x20000e3e = 6;
  *(uint8_t*)0x20000e3f = 2;
  *(uint8_t*)0x20000e40 = 9;
  *(uint8_t*)0x20000e41 = 5;
  *(uint8_t*)0x20000e42 = 4;
  *(uint8_t*)0x20000e43 = 0;
  *(uint16_t*)0x20000e44 = 0x400;
  *(uint8_t*)0x20000e46 = 4;
  *(uint8_t*)0x20000e47 = 7;
  *(uint8_t*)0x20000e48 = 6;
  *(uint8_t*)0x20000e49 = 9;
  *(uint8_t*)0x20000e4a = 4;
  *(uint8_t*)0x20000e4b = 0xec;
  *(uint8_t*)0x20000e4c = 0xbe;
  *(uint8_t*)0x20000e4d = 2;
  *(uint8_t*)0x20000e4e = 0x95;
  *(uint8_t*)0x20000e4f = 0xb0;
  *(uint8_t*)0x20000e50 = 0x61;
  *(uint8_t*)0x20000e51 = 0xfd;
  *(uint8_t*)0x20000e52 = 2;
  *(uint8_t*)0x20000e53 = 0x21;
  *(uint8_t*)0x20000e54 = 2;
  *(uint8_t*)0x20000e55 = 0x11;
  *(uint8_t*)0x20000e56 = 9;
  *(uint8_t*)0x20000e57 = 5;
  *(uint8_t*)0x20000e58 = 4;
  *(uint8_t*)0x20000e59 = 1;
  *(uint16_t*)0x20000e5a = 0x40;
  *(uint8_t*)0x20000e5c = 4;
  *(uint8_t*)0x20000e5d = 0x20;
  *(uint8_t*)0x20000e5e = 0xe0;
  *(uint8_t*)0x20000e5f = 9;
  *(uint8_t*)0x20000e60 = 5;
  *(uint8_t*)0x20000e61 = 1;
  *(uint8_t*)0x20000e62 = 1;
  *(uint16_t*)0x20000e63 = 8;
  *(uint8_t*)0x20000e65 = 1;
  *(uint8_t*)0x20000e66 = 4;
  *(uint8_t*)0x20000e67 = 0x8f;
  *(uint8_t*)0x20000e68 = 7;
  *(uint8_t*)0x20000e69 = 0x25;
  *(uint8_t*)0x20000e6a = 1;
  *(uint8_t*)0x20000e6b = 0;
  *(uint8_t*)0x20000e6c = 0x33;
  *(uint16_t*)0x20000e6d = 2;
  *(uint8_t*)0x20000e6f = 9;
  *(uint8_t*)0x20000e70 = 4;
  *(uint8_t*)0x20000e71 = 0x91;
  *(uint8_t*)0x20000e72 = 0x20;
  *(uint8_t*)0x20000e73 = 0xe;
  *(uint8_t*)0x20000e74 = 0x2d;
  *(uint8_t*)0x20000e75 = 0x90;
  *(uint8_t*)0x20000e76 = 3;
  *(uint8_t*)0x20000e77 = -1;
  *(uint8_t*)0x20000e78 = 5;
  *(uint8_t*)0x20000e79 = 0x24;
  *(uint8_t*)0x20000e7a = 6;
  *(uint8_t*)0x20000e7b = 0;
  *(uint8_t*)0x20000e7c = 0;
  *(uint8_t*)0x20000e7d = 5;
  *(uint8_t*)0x20000e7e = 0x24;
  *(uint8_t*)0x20000e7f = 0;
  *(uint16_t*)0x20000e80 = 5;
  *(uint8_t*)0x20000e82 = 0xd;
  *(uint8_t*)0x20000e83 = 0x24;
  *(uint8_t*)0x20000e84 = 0xf;
  *(uint8_t*)0x20000e85 = 1;
  *(uint32_t*)0x20000e86 = 3;
  *(uint16_t*)0x20000e8a = 0x100;
  *(uint16_t*)0x20000e8c = 0x81;
  *(uint8_t*)0x20000e8e = 1;
  *(uint8_t*)0x20000e8f = 7;
  *(uint8_t*)0x20000e90 = 0x24;
  *(uint8_t*)0x20000e91 = 0x14;
  *(uint16_t*)0x20000e92 = 0x24;
  *(uint16_t*)0x20000e94 = 6;
  *(uint8_t*)0x20000e96 = 6;
  *(uint8_t*)0x20000e97 = 0x24;
  *(uint8_t*)0x20000e98 = 0x1a;
  *(uint16_t*)0x20000e99 = 0;
  *(uint8_t*)0x20000e9b = 0x3a;
  *(uint8_t*)0x20000e9c = 0xa;
  *(uint8_t*)0x20000e9d = 0x24;
  *(uint8_t*)0x20000e9e = 1;
  *(uint16_t*)0x20000e9f = 0x20;
  *(uint8_t*)0x20000ea1 = 0xfa;
  *(uint8_t*)0x20000ea2 = 2;
  *(uint8_t*)0x20000ea3 = 1;
  *(uint8_t*)0x20000ea4 = 2;
  *(uint8_t*)0x20000ea5 = 5;
  *(uint8_t*)0x20000ea6 = 0x24;
  *(uint8_t*)0x20000ea7 = 5;
  *(uint8_t*)0x20000ea8 = 2;
  *(uint8_t*)0x20000ea9 = 1;
  *(uint8_t*)0x20000eaa = 7;
  *(uint8_t*)0x20000eab = 0x24;
  *(uint8_t*)0x20000eac = 7;
  *(uint8_t*)0x20000ead = 1;
  *(uint16_t*)0x20000eae = 4;
  *(uint8_t*)0x20000eb0 = 0xfd;
  *(uint8_t*)0x20000eb1 = 5;
  *(uint8_t*)0x20000eb2 = 0x24;
  *(uint8_t*)0x20000eb3 = 5;
  *(uint8_t*)0x20000eb4 = 2;
  *(uint8_t*)0x20000eb5 = 3;
  *(uint8_t*)0x20000eb6 = 9;
  *(uint8_t*)0x20000eb7 = 5;
  *(uint8_t*)0x20000eb8 = 0xf;
  *(uint8_t*)0x20000eb9 = 0x10;
  *(uint16_t*)0x20000eba = 8;
  *(uint8_t*)0x20000ebc = 7;
  *(uint8_t*)0x20000ebd = 0x1f;
  *(uint8_t*)0x20000ebe = 0;
  *(uint8_t*)0x20000ebf = 2;
  *(uint8_t*)0x20000ec0 = 0x22;
  *(uint8_t*)0x20000ec1 = 7;
  *(uint8_t*)0x20000ec2 = 0x25;
  *(uint8_t*)0x20000ec3 = 1;
  *(uint8_t*)0x20000ec4 = 2;
  *(uint8_t*)0x20000ec5 = 0xf2;
  *(uint16_t*)0x20000ec6 = 8;
  *(uint8_t*)0x20000ec8 = 9;
  *(uint8_t*)0x20000ec9 = 5;
  *(uint8_t*)0x20000eca = 7;
  *(uint8_t*)0x20000ecb = 0;
  *(uint16_t*)0x20000ecc = 0x10;
  *(uint8_t*)0x20000ece = 0xc1;
  *(uint8_t*)0x20000ecf = 2;
  *(uint8_t*)0x20000ed0 = 0x3f;
  *(uint8_t*)0x20000ed1 = 7;
  *(uint8_t*)0x20000ed2 = 0x25;
  *(uint8_t*)0x20000ed3 = 1;
  *(uint8_t*)0x20000ed4 = 1;
  *(uint8_t*)0x20000ed5 = 0xa;
  *(uint16_t*)0x20000ed6 = 0x40;
  *(uint8_t*)0x20000ed8 = 9;
  *(uint8_t*)0x20000ed9 = 5;
  *(uint8_t*)0x20000eda = 6;
  *(uint8_t*)0x20000edb = 3;
  *(uint16_t*)0x20000edc = 8;
  *(uint8_t*)0x20000ede = 0x20;
  *(uint8_t*)0x20000edf = 3;
  *(uint8_t*)0x20000ee0 = 0;
  *(uint8_t*)0x20000ee1 = 7;
  *(uint8_t*)0x20000ee2 = 0x25;
  *(uint8_t*)0x20000ee3 = 1;
  *(uint8_t*)0x20000ee4 = 1;
  *(uint8_t*)0x20000ee5 = 2;
  *(uint16_t*)0x20000ee6 = 9;
  *(uint8_t*)0x20000ee8 = 9;
  *(uint8_t*)0x20000ee9 = 5;
  *(uint8_t*)0x20000eea = 7;
  *(uint8_t*)0x20000eeb = 0;
  *(uint16_t*)0x20000eec = 0x3ff;
  *(uint8_t*)0x20000eee = 0x5e;
  *(uint8_t*)0x20000eef = 0x40;
  *(uint8_t*)0x20000ef0 = 0x23;
  *(uint8_t*)0x20000ef1 = 9;
  *(uint8_t*)0x20000ef2 = 5;
  *(uint8_t*)0x20000ef3 = 9;
  *(uint8_t*)0x20000ef4 = 1;
  *(uint16_t*)0x20000ef5 = 0x40;
  *(uint8_t*)0x20000ef7 = 7;
  *(uint8_t*)0x20000ef8 = 0;
  *(uint8_t*)0x20000ef9 = 1;
  *(uint8_t*)0x20000efa = 2;
  *(uint8_t*)0x20000efb = 0x21;
  *(uint8_t*)0x20000efc = 9;
  *(uint8_t*)0x20000efd = 5;
  *(uint8_t*)0x20000efe = 0xa;
  *(uint8_t*)0x20000eff = 0;
  *(uint16_t*)0x20000f00 = 0x400;
  *(uint8_t*)0x20000f02 = 1;
  *(uint8_t*)0x20000f03 = 6;
  *(uint8_t*)0x20000f04 = 0x85;
  *(uint8_t*)0x20000f05 = 7;
  *(uint8_t*)0x20000f06 = 0x25;
  *(uint8_t*)0x20000f07 = 1;
  *(uint8_t*)0x20000f08 = 2;
  *(uint8_t*)0x20000f09 = 4;
  *(uint16_t*)0x20000f0a = 0x1f;
  *(uint8_t*)0x20000f0c = 9;
  *(uint8_t*)0x20000f0d = 5;
  *(uint8_t*)0x20000f0e = 0x80;
  *(uint8_t*)0x20000f0f = 2;
  *(uint16_t*)0x20000f10 = 0x40;
  *(uint8_t*)0x20000f12 = 6;
  *(uint8_t*)0x20000f13 = 0xfb;
  *(uint8_t*)0x20000f14 = 0;
  *(uint8_t*)0x20000f15 = 7;
  *(uint8_t*)0x20000f16 = 0x25;
  *(uint8_t*)0x20000f17 = 1;
  *(uint8_t*)0x20000f18 = 0x82;
  *(uint8_t*)0x20000f19 = 0;
  *(uint16_t*)0x20000f1a = 0xd3;
  *(uint8_t*)0x20000f1c = 7;
  *(uint8_t*)0x20000f1d = 0x25;
  *(uint8_t*)0x20000f1e = 1;
  *(uint8_t*)0x20000f1f = 0x83;
  *(uint8_t*)0x20000f20 = 5;
  *(uint16_t*)0x20000f21 = 8;
  *(uint8_t*)0x20000f23 = 9;
  *(uint8_t*)0x20000f24 = 5;
  *(uint8_t*)0x20000f25 = 4;
  *(uint8_t*)0x20000f26 = 0;
  *(uint16_t*)0x20000f27 = 8;
  *(uint8_t*)0x20000f29 = 5;
  *(uint8_t*)0x20000f2a = 0x81;
  *(uint8_t*)0x20000f2b = 5;
  *(uint8_t*)0x20000f2c = 9;
  *(uint8_t*)0x20000f2d = 5;
  *(uint8_t*)0x20000f2e = 7;
  *(uint8_t*)0x20000f2f = 0;
  *(uint16_t*)0x20000f30 = 0x20;
  *(uint8_t*)0x20000f32 = 1;
  *(uint8_t*)0x20000f33 = 1;
  *(uint8_t*)0x20000f34 = 0;
  *(uint8_t*)0x20000f35 = 9;
  *(uint8_t*)0x20000f36 = 5;
  *(uint8_t*)0x20000f37 = 8;
  *(uint8_t*)0x20000f38 = 3;
  *(uint16_t*)0x20000f39 = 0x200;
  *(uint8_t*)0x20000f3b = 0x20;
  *(uint8_t*)0x20000f3c = 1;
  *(uint8_t*)0x20000f3d = 0xb0;
  *(uint8_t*)0x20000f3e = 7;
  *(uint8_t*)0x20000f3f = 0x25;
  *(uint8_t*)0x20000f40 = 1;
  *(uint8_t*)0x20000f41 = 0x82;
  *(uint8_t*)0x20000f42 = 0xc1;
  *(uint16_t*)0x20000f43 = 5;
  *(uint8_t*)0x20000f45 = 9;
  *(uint8_t*)0x20000f46 = 5;
  *(uint8_t*)0x20000f47 = 3;
  *(uint8_t*)0x20000f48 = 0;
  *(uint16_t*)0x20000f49 = 0x10;
  *(uint8_t*)0x20000f4b = 3;
  *(uint8_t*)0x20000f4c = 9;
  *(uint8_t*)0x20000f4d = 0x40;
  *(uint8_t*)0x20000f4e = 9;
  *(uint8_t*)0x20000f4f = 5;
  *(uint8_t*)0x20000f50 = 2;
  *(uint8_t*)0x20000f51 = 2;
  *(uint16_t*)0x20000f52 = 0x40;
  *(uint8_t*)0x20000f54 = 1;
  *(uint8_t*)0x20000f55 = 1;
  *(uint8_t*)0x20000f56 = 0x2b;
  *(uint8_t*)0x20000f57 = 7;
  *(uint8_t*)0x20000f58 = 0x25;
  *(uint8_t*)0x20000f59 = 1;
  *(uint8_t*)0x20000f5a = 0x81;
  *(uint8_t*)0x20000f5b = 5;
  *(uint16_t*)0x20000f5c = 0x3ff;
  *(uint8_t*)0x20000f5e = 2;
  *(uint8_t*)0x20000f5f = 0x23;
  *(uint8_t*)0x20000f60 = 9;
  *(uint8_t*)0x20000f61 = 5;
  *(uint8_t*)0x20000f62 = 0;
  *(uint8_t*)0x20000f63 = 1;
  *(uint16_t*)0x20000f64 = 0x10;
  *(uint8_t*)0x20000f66 = 6;
  *(uint8_t*)0x20000f67 = 9;
  *(uint8_t*)0x20000f68 = 3;
  *(uint8_t*)0x20000f69 = 2;
  *(uint8_t*)0x20000f6a = 1;
  *(uint8_t*)0x20000f6b = 9;
  *(uint8_t*)0x20000f6c = 5;
  *(uint8_t*)0x20000f6d = 0xf;
  *(uint8_t*)0x20000f6e = 4;
  *(uint16_t*)0x20000f6f = 0x40;
  *(uint8_t*)0x20000f71 = 0x20;
  *(uint8_t*)0x20000f72 = 0x3f;
  *(uint8_t*)0x20000f73 = 0x3f;
  syz_usb_connect(5, 0x274, 0x20000d00, 0);
}
int main(void)
{
  syscall(__NR_mmap, 0x1ffff000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x20000000ul, 0x1000000ul, 7ul, 0x32ul, -1, 0ul);
  syscall(__NR_mmap, 0x21000000ul, 0x1000ul, 0ul, 0x32ul, -1, 0ul);
  loop();
  return 0;
}
