// KASAN: use-after-free Read in xfrm6_tunnel_destroy
// https://syzkaller.appspot.com/bug?id=fecd3274ae6917477cfd0a33b12e1f56da6223b6
// status:open
// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <dirent.h>
#include <endian.h>
#include <errno.h>
#include <sched.h>
#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mount.h>
#include <sys/prctl.h>
#include <sys/resource.h>
#include <sys/stat.h>
#include <sys/syscall.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <time.h>
#include <unistd.h>

unsigned long long procid;

static void sleep_ms(uint64_t ms)
{
  usleep(ms * 1000);
}

uint64_t current_time_ms()
{
  struct timespec ts;
  if (clock_gettime(CLOCK_MONOTONIC, &ts))
    exit(1);
  return (uint64_t)ts.tv_sec * 1000 + (uint64_t)ts.tv_nsec / 1000000;
}

static void use_temporary_dir()
{
  char tmpdir_template[] = "./syzkaller.XXXXXX";
  char* tmpdir = mkdtemp(tmpdir_template);
  if (!tmpdir)
    exit(1);
  if (chmod(tmpdir, 0777))
    exit(1);
  if (chdir(tmpdir))
    exit(1);
}

static void setup_common()
{
}

static void loop();

static void sandbox_common()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
  setsid();
  struct rlimit rlim;
  rlim.rlim_cur = rlim.rlim_max = 160 << 20;
  setrlimit(RLIMIT_AS, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 8 << 20;
  setrlimit(RLIMIT_MEMLOCK, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 136 << 20;
  setrlimit(RLIMIT_FSIZE, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 1 << 20;
  setrlimit(RLIMIT_STACK, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 0;
  setrlimit(RLIMIT_CORE, &rlim);
  rlim.rlim_cur = rlim.rlim_max = 256;
  setrlimit(RLIMIT_NOFILE, &rlim);
  if (unshare(CLONE_NEWNS)) {
  }
  if (unshare(CLONE_NEWIPC)) {
  }
  if (unshare(0x02000000)) {
  }
  if (unshare(CLONE_NEWUTS)) {
  }
  if (unshare(CLONE_SYSVSEM)) {
  }
}

int wait_for_loop(int pid)
{
  if (pid < 0)
    exit(1);
  int status = 0;
  while (waitpid(-1, &status, __WALL) != pid) {
  }
  return WEXITSTATUS(status);
}

static int do_sandbox_none(void)
{
  if (unshare(CLONE_NEWPID)) {
  }
  int pid = fork();
  if (pid != 0)
    return wait_for_loop(pid);
  setup_common();
  sandbox_common();
  if (unshare(CLONE_NEWNET)) {
  }
  loop();
  exit(1);
}

static void remove_dir(const char* dir)
{
  DIR* dp;
  struct dirent* ep;
  int iter = 0;
retry:
  while (umount2(dir, MNT_DETACH) == 0) {
  }
  dp = opendir(dir);
  if (dp == NULL) {
    if (errno == EMFILE) {
      exit(1);
    }
    exit(1);
  }
  while ((ep = readdir(dp))) {
    if (strcmp(ep->d_name, ".") == 0 || strcmp(ep->d_name, "..") == 0)
      continue;
    char filename[FILENAME_MAX];
    snprintf(filename, sizeof(filename), "%s/%s", dir, ep->d_name);
    while (umount2(filename, MNT_DETACH) == 0) {
    }
    struct stat st;
    if (lstat(filename, &st))
      exit(1);
    if (S_ISDIR(st.st_mode)) {
      remove_dir(filename);
      continue;
    }
    int i;
    for (i = 0;; i++) {
      if (unlink(filename) == 0)
        break;
      if (errno == EROFS) {
        break;
      }
      if (errno != EBUSY || i > 100)
        exit(1);
      if (umount2(filename, MNT_DETACH))
        exit(1);
    }
  }
  closedir(dp);
  int i;
  for (i = 0;; i++) {
    if (rmdir(dir) == 0)
      break;
    if (i < 100) {
      if (errno == EROFS) {
        break;
      }
      if (errno == EBUSY) {
        if (umount2(dir, MNT_DETACH))
          exit(1);
        continue;
      }
      if (errno == ENOTEMPTY) {
        if (iter < 100) {
          iter++;
          goto retry;
        }
      }
    }
    exit(1);
  }
}

#define SYZ_HAVE_SETUP_TEST 1
static void setup_test()
{
  prctl(PR_SET_PDEATHSIG, SIGKILL, 0, 0, 0);
  setpgrp();
}

#define SYZ_HAVE_RESET_TEST 1
static void reset_test()
{
  int fd;
  for (fd = 3; fd < 30; fd++)
    close(fd);
}

static void execute_one();

#define WAIT_FLAGS __WALL

static void loop()
{
  int iter;
  for (iter = 0;; iter++) {
    char cwdbuf[32];
    sprintf(cwdbuf, "./%d", iter);
    if (mkdir(cwdbuf, 0777))
      exit(1);
    int pid = fork();
    if (pid < 0)
      exit(1);
    if (pid == 0) {
      setup_test();
      if (chdir(cwdbuf))
        exit(1);
      execute_one();
      reset_test();
      exit(0);
    }
    int status = 0;
    uint64_t start = current_time_ms();
    for (;;) {
      if (waitpid(-1, &status, WNOHANG | WAIT_FLAGS) == pid)
        break;
      sleep_ms(1);
      if (current_time_ms() - start < 5 * 1000)
        continue;
      kill(-pid, SIGKILL);
      kill(pid, SIGKILL);
      while (waitpid(-1, &status, WAIT_FLAGS) != pid) {
      }
      break;
    }
    remove_dir(cwdbuf);
  }
}

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

void execute_one()
{
  long res = 0;
  memcpy((void*)0x20000440, "./file0", 8);
  res = syscall(__NR_creat, 0x20000440, 0);
  if (res != -1)
    r[0] = res;
  memcpy((void*)0x20000100, "?[", 2);
  syscall(__NR_ioctl, r[0], 0x40086602, 0x20000100);
  res = syscall(__NR_socket, 0xf, 3, 2);
  if (res != -1)
    r[1] = res;
  *(uint64_t*)0x20f56000 = 0;
  *(uint32_t*)0x20f56008 = 0;
  *(uint64_t*)0x20f56010 = 0x208feff0;
  *(uint64_t*)0x208feff0 = 0x20000040;
  *(uint8_t*)0x20000040 = 2;
  *(uint8_t*)0x20000041 = 3;
  *(uint8_t*)0x20000042 = 0;
  *(uint8_t*)0x20000043 = 9;
  *(uint16_t*)0x20000044 = 0x10;
  *(uint16_t*)0x20000046 = 0;
  *(uint32_t*)0x20000048 = 0;
  *(uint32_t*)0x2000004c = 0;
  *(uint16_t*)0x20000050 = 2;
  *(uint16_t*)0x20000052 = 0x13;
  *(uint8_t*)0x20000054 = 2;
  *(uint8_t*)0x20000055 = 0;
  *(uint16_t*)0x20000056 = 0;
  *(uint32_t*)0x20000058 = 0;
  *(uint32_t*)0x2000005c = 0;
  *(uint16_t*)0x20000060 = 5;
  *(uint16_t*)0x20000062 = 6;
  *(uint8_t*)0x20000064 = 0;
  *(uint8_t*)0x20000065 = 0;
  *(uint16_t*)0x20000066 = 0;
  *(uint16_t*)0x20000068 = 0xa;
  *(uint16_t*)0x2000006a = htobe16(0);
  *(uint32_t*)0x2000006c = 0;
  *(uint8_t*)0x20000070 = 0;
  *(uint8_t*)0x20000071 = 0;
  *(uint8_t*)0x20000072 = 0;
  *(uint8_t*)0x20000073 = 0;
  *(uint8_t*)0x20000074 = 0;
  *(uint8_t*)0x20000075 = 0;
  *(uint8_t*)0x20000076 = 0;
  *(uint8_t*)0x20000077 = 0;
  *(uint8_t*)0x20000078 = 0;
  *(uint8_t*)0x20000079 = 0;
  *(uint8_t*)0x2000007a = 0;
  *(uint8_t*)0x2000007b = 0;
  *(uint8_t*)0x2000007c = 0;
  *(uint8_t*)0x2000007d = 0;
  *(uint8_t*)0x2000007e = 0;
  *(uint8_t*)0x2000007f = 0;
  *(uint32_t*)0x20000080 = 0;
  *(uint16_t*)0x20000088 = 2;
  *(uint16_t*)0x2000008a = 1;
  *(uint32_t*)0x2000008c = htobe32(0);
  *(uint8_t*)0x20000090 = 0;
  *(uint8_t*)0x20000091 = 0;
  *(uint8_t*)0x20000092 = 0;
  *(uint8_t*)0x20000093 = 2;
  *(uint32_t*)0x20000094 = 0;
  *(uint16_t*)0x20000098 = 5;
  *(uint16_t*)0x2000009a = 5;
  *(uint8_t*)0x2000009c = 0;
  *(uint8_t*)0x2000009d = 0;
  *(uint16_t*)0x2000009e = 0;
  *(uint16_t*)0x200000a0 = 0xa;
  *(uint16_t*)0x200000a2 = htobe16(0);
  *(uint32_t*)0x200000a4 = 0;
  *(uint8_t*)0x200000a8 = -1;
  *(uint8_t*)0x200000a9 = 1;
  *(uint8_t*)0x200000aa = 0;
  *(uint8_t*)0x200000ab = 0;
  *(uint8_t*)0x200000ac = 0;
  *(uint8_t*)0x200000ad = 0;
  *(uint8_t*)0x200000ae = 0;
  *(uint8_t*)0x200000af = 0;
  *(uint8_t*)0x200000b0 = 0;
  *(uint8_t*)0x200000b1 = 0;
  *(uint8_t*)0x200000b2 = 0;
  *(uint8_t*)0x200000b3 = 0;
  *(uint8_t*)0x200000b4 = 0;
  *(uint8_t*)0x200000b5 = 0;
  *(uint8_t*)0x200000b6 = 0;
  *(uint8_t*)0x200000b7 = 1;
  *(uint32_t*)0x200000b8 = 0;
  *(uint64_t*)0x208feff8 = 0x80;
  *(uint64_t*)0x20f56018 = 1;
  *(uint64_t*)0x20f56020 = 0;
  *(uint64_t*)0x20f56028 = 0;
  *(uint32_t*)0x20f56030 = 0;
  syscall(__NR_sendmsg, r[1], 0x20f56000, 0);
}
int main()
{
  syscall(__NR_mmap, 0x20000000, 0x1000000, 3, 0x32, -1, 0);
  for (procid = 0; procid < 8; procid++) {
    if (fork() == 0) {
      use_temporary_dir();
      do_sandbox_none();
    }
  }
  sleep(1000000);
  return 0;
}
